-- Bestyrelsesmodul: møder, referater, beslutninger og opfølgning

create table if not exists public.board_meetings (
  id bigint generated by default as identity primary key,
  title text not null,
  meeting_date date not null,
  start_time time,
  location text,
  agenda text,
  minutes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.board_meetings add column if not exists minutes text;
alter table public.board_meetings add column if not exists updated_at timestamptz not null default now();

create table if not exists public.board_decisions (
  id bigint generated by default as identity primary key,
  meeting_id bigint not null references public.board_meetings(id) on delete cascade,
  decision text not null,
  responsible text,
  due_date date,
  completed boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists board_decisions_meeting_id_idx on public.board_decisions(meeting_id);

alter table public.board_meetings enable row level security;
alter table public.board_decisions enable row level security;

-- Adgang styres i appen via board/admin-rollen. Disse policies kræver blot login,
-- så eksisterende Supabase Auth-brugere kan læse bestyrelsesdata.
drop policy if exists "Authenticated users can read board meetings" on public.board_meetings;
create policy "Authenticated users can read board meetings"
on public.board_meetings for select
to authenticated
using (true);

drop policy if exists "Authenticated users can manage board meetings" on public.board_meetings;
create policy "Authenticated users can manage board meetings"
on public.board_meetings for all
to authenticated
using (true)
with check (true);

drop policy if exists "Authenticated users can read board decisions" on public.board_decisions;
create policy "Authenticated users can read board decisions"
on public.board_decisions for select
to authenticated
using (true);

drop policy if exists "Authenticated users can manage board decisions" on public.board_decisions;
create policy "Authenticated users can manage board decisions"
on public.board_decisions for all
to authenticated
using (true)
with check (true);