create table if not exists public.class_handover (
  id bigint generated by default as identity primary key,
  class_id bigint not null references public.classes(id) on delete cascade,
  student_id bigint references public.students(id) on delete set null,
  handover_date date not null default current_date,
  category text not null default 'practical' check (category in ('practical','teaching','student','substitute')),
  message text not null,
  author_id uuid not null,
  author_email text not null,
  created_at timestamptz not null default now()
);

create index if not exists class_handover_class_date_idx on public.class_handover(class_id, handover_date desc, created_at desc);

alter table public.class_handover enable row level security;

create policy "authenticated can read class handover" on public.class_handover
for select to authenticated using (true);

create policy "authenticated can create class handover" on public.class_handover
for insert to authenticated with check (auth.uid() = author_id);

create policy "authors can delete own class handover" on public.class_handover
for delete to authenticated using (auth.uid() = author_id);
