-- Klasseværelset: grammar module schema
-- Run this once in Supabase SQL Editor.

create table if not exists public.grammar_assignments (
  id bigint generated by default as identity primary key,
  class_id bigint not null references public.classes(id) on delete cascade,
  area text not null,
  topic text not null,
  level text not null check (level in ('basis','traening','udfordring')),
  title text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.grammar_questions (
  id bigint generated by default as identity primary key,
  grammar_assignment_id bigint not null references public.grammar_assignments(id) on delete cascade,
  position integer not null,
  prompt text not null,
  question_type text not null default 'multiple_choice',
  options jsonb not null default '[]'::jsonb,
  correct_answer text,
  explanation text,
  unique(grammar_assignment_id, position)
);

create table if not exists public.grammar_attempts (
  id bigint generated by default as identity primary key,
  grammar_assignment_id bigint not null references public.grammar_assignments(id) on delete cascade,
  student_id bigint not null references public.students(id) on delete cascade,
  answers jsonb not null default '{}'::jsonb,
  score integer,
  max_score integer,
  completed_at timestamptz,
  updated_at timestamptz not null default now(),
  unique(grammar_assignment_id, student_id)
);

create index if not exists grammar_assignments_class_idx on public.grammar_assignments(class_id);
create index if not exists grammar_questions_assignment_idx on public.grammar_questions(grammar_assignment_id);
create index if not exists grammar_attempts_student_idx on public.grammar_attempts(student_id);

alter table public.grammar_assignments enable row level security;
alter table public.grammar_questions enable row level security;
alter table public.grammar_attempts enable row level security;

-- Teachers use Supabase Auth. Student access will be exposed through narrowly scoped RPCs,
-- just like the existing student-code flow, rather than opening these tables publicly.
do $$ begin
  create policy "authenticated teachers manage grammar assignments" on public.grammar_assignments
    for all to authenticated using (true) with check (true);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "authenticated teachers manage grammar questions" on public.grammar_questions
    for all to authenticated using (true) with check (true);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "authenticated teachers view grammar attempts" on public.grammar_attempts
    for select to authenticated using (true);
exception when duplicate_object then null; end $$;

create or replace function public.student_grammar_assignments(p_access_code text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  s public.students;
begin
  select * into s from public.students where upper(access_code)=upper(trim(p_access_code)) limit 1;
  if s.id is null then return jsonb_build_object('ok',false); end if;
  return jsonb_build_object(
    'ok',true,
    'assignments',coalesce((select jsonb_agg(jsonb_build_object(
      'id',ga.id,'area',ga.area,'topic',ga.topic,'level',ga.level,'title',ga.title,
      'completed',a.completed_at is not null,'score',a.score,'max_score',a.max_score
    ) order by ga.created_at desc)
    from public.grammar_assignments ga
    left join public.grammar_attempts a on a.grammar_assignment_id=ga.id and a.student_id=s.id
    where ga.class_id=s.class_id),'[]'::jsonb)
  );
end $$;

grant execute on function public.student_grammar_assignments(text) to anon, authenticated;
