-- Klasseværelset: skema og elevfravær
create table if not exists public.schedule_entries (
  id bigint generated by default as identity primary key,
  class_id bigint not null references public.classes(id) on delete cascade,
  weekday smallint not null check (weekday between 1 and 5),
  start_time time not null,
  end_time time not null,
  subject text not null,
  teacher text,
  room text,
  created_at timestamptz not null default now()
);

create table if not exists public.student_absence (
  id bigint generated by default as identity primary key,
  student_id bigint not null references public.students(id) on delete cascade,
  absence_date date not null,
  status text not null default 'absent' check (status in ('absent','late','excused')),
  note text,
  created_at timestamptz not null default now()
);

create index if not exists schedule_entries_class_idx on public.schedule_entries(class_id,weekday,start_time);
create index if not exists student_absence_student_idx on public.student_absence(student_id,absence_date desc);

alter table public.schedule_entries enable row level security;
alter table public.student_absence enable row level security;
