-- Run this once in Supabase SQL Editor.
create table if not exists public.substitute_assignments (
  id bigint generated by default as identity primary key,
  school_id bigint not null references public.schools(id) on delete cascade,
  schedule_entry_id bigint not null references public.schedule_entries(id) on delete cascade,
  assignment_date date not null,
  absent_teacher_id uuid not null references auth.users(id) on delete cascade,
  substitute_teacher_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique(schedule_entry_id, assignment_date, absent_teacher_id)
);

alter table public.substitute_assignments enable row level security;

drop policy if exists "school_admins_manage_substitute_assignments" on public.substitute_assignments;
create policy "school_admins_manage_substitute_assignments"
on public.substitute_assignments
for all
to authenticated
using (
  exists (
    select 1 from public.school_memberships sm
    where sm.school_id = substitute_assignments.school_id
      and sm.user_id = auth.uid()
      and sm.active = true
      and sm.role in ('admin','leader')
  )
)
with check (
  exists (
    select 1 from public.school_memberships sm
    where sm.school_id = substitute_assignments.school_id
      and sm.user_id = auth.uid()
      and sm.active = true
      and sm.role in ('admin','leader')
  )
);

drop policy if exists "teachers_read_own_substitute_assignments" on public.substitute_assignments;
create policy "teachers_read_own_substitute_assignments"
on public.substitute_assignments
for select
to authenticated
using (substitute_teacher_id = auth.uid() or absent_teacher_id = auth.uid());
