"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {supabase} from "../../../lib/supabase";
import {hasRole} from "../../../lib/roles";
type ClosedDay={date:string;label:string};
const iso=(d:Date)=>{const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,"0"),day=String(d.getDate()).padStart(2,"0");return `${y}-${m}-${day}`};
function week(s:string){const d=new Date(s+"T12:00:00"),x=new Date(Date.UTC(d.getFullYear(),d.getMonth(),d.getDate())),day=x.getUTCDay()||7;x.setUTCDate(x.getUTCDate()+4-day);const ys=new Date(Date.UTC(x.getUTCFullYear(),0,1));return Math.ceil((((x.getTime()-ys.getTime())/86400000)+1)/7)}
const fmt=(s:string)=>new Date(s+"T12:00:00").toLocaleDateString("da-DK",{day:"numeric",month:"short"});
export default function Page(){
 const[ready,setReady]=useState(false),[start,setStart]=useState("2026-08-10"),[end,setEnd]=useState("2027-06-25"),[closed,setClosed]=useState<ClosedDay[]>([]),[message,setMessage]=useState("");
 const[selected,setSelected]=useState<string[]>([]),[label,setLabel]=useState("");
 useEffect(()=>{(async()=>{const{data}=await supabase.auth.getSession();const u=data.session?.user;if(!u){location.replace("/");return}if(!hasRole(u,"admin")){location.replace("/noticeboard");return}const{data:r}=await supabase.from("school_settings").select("school_year_start,school_year_end,closed_days").eq("id",1).maybeSingle();if(r){if(r.school_year_start)setStart(r.school_year_start);if(r.school_year_end)setEnd(r.school_year_end);if(Array.isArray(r.closed_days))setClosed(r.closed_days)}setReady(true)})()},[]);
 const excluded=useMemo(()=>new Map(closed.map(x=>[x.date,x.label])),[closed]);
 const schoolDays=useMemo(()=>{let n=0,d=new Date(start+"T12:00:00"),e=new Date(end+"T12:00:00");while(d<=e){if(d.getDay()>0&&d.getDay()<6&&!excluded.has(iso(d)))n++;d.setDate(d.getDate()+1)}return n},[start,end,excluded]);
 const weeks=useMemo(()=>{const out:{num:number;days:Date[]}[]=[];let d=new Date(start+"T12:00:00");d.setDate(d.getDate()-((d.getDay()+6)%7));const e=new Date(end+"T12:00:00");while(d<=e){const days=Array.from({length:7},(_,i)=>{const x=new Date(d);x.setDate(x.getDate()+i);return x});out.push({num:week(iso(d)),days});d.setDate(d.getDate()+7)}return out},[start,end]);
 const months=useMemo(()=>{const groups:{key:string;name:string;weeks:typeof weeks}[]=[];weeks.forEach(w=>{const anchor=w.days.find(d=>d.getDay()>=1&&d.getDay()<=5&&iso(d)>=start&&iso(d)<=end)||w.days[0];const key=`${anchor.getFullYear()}-${anchor.getMonth()}`;let g=groups.find(x=>x.key===key);if(!g){g={key,name:anchor.toLocaleDateString("da-DK",{month:"long",year:"numeric"}),weeks:[]};groups.push(g)}g.weeks.push(w)});return groups},[weeks,start,end]);
 function toggleDay(s:string){if(s<start||s>end)return;setSelected(v=>v.includes(s)?v.filter(x=>x!==s):[...v,s])}
 function toggleWeek(days:Date[]){const valid=days.filter(d=>d.getDay()>0&&d.getDay()<6&&iso(d)>=start&&iso(d)<=end).map(iso);const all=valid.every(x=>selected.includes(x));setSelected(v=>all?v.filter(x=>!valid.includes(x)):[...new Set([...v,...valid])])}
 function mark(){if(!selected.length)return;const l=label.trim()||"Lukkedag";const set=new Set(selected);setClosed(v=>[...v.filter(x=>!set.has(x.date)),...selected.map(date=>({date,label:l}))].sort((a,b)=>a.date.localeCompare(b.date)));setSelected([]);setLabel("")}
 function clearMarked(){const set=new Set(selected);setClosed(v=>v.filter(x=>!set.has(x.date)));setSelected([])}
 async function save(){setMessage("Gemmer…");const{error}=await supabase.from("school_settings").upsert({id:1,school_year_start:start,school_year_end:end,closed_days:closed,updated_at:new Date().toISOString()});setMessage(error?"Kunne ikke gemme.":"Skolekalenderen er gemt.")}
 if(!ready)return <main style={{padding:40}}>Henter skoleopsætning…</main>;
 return <main style={{minHeight:"100vh",background:"#f5f2ea"}}><header style={{background:"#486b59",color:"white",padding:"18px 6vw",display:"flex",justifyContent:"space-between"}}><strong style={{fontSize:22}}>Administration · Skoleopsætning</strong><Link href="/admin" style={{color:"white"}}>← Administration</Link></header><section style={{maxWidth:1150,margin:"auto",padding:"42px 24px"}}><p className="eyebrow">SKOLEÅR</p><h1 style={{fontSize:44,margin:"0 0 8px"}}>Skolens kalender</h1><p style={{fontSize:18,color:"#626a63"}}>Klik på enkelte dage eller på et ugenummer for at markere en hel skoleuge som ferie eller lukkedage.</p>
 <div style={{display:"grid",gridTemplateColumns:"2fr 1fr",gap:18,margin:"28px 0"}}><section style={card}><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:14}}><label style={lab}>Første skoledag<input style={inp} type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label style={lab}>Sidste skoledag<input style={inp} type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label></div></section><section style={card}><span className="eyebrow">BEREGNET</span><strong style={{display:"block",fontSize:48,color:"#294a3c"}}>{schoolDays}</strong><b>skoledage</b></section></div>
 <section style={card}><div style={{display:"flex",gap:10,alignItems:"end",flexWrap:"wrap",marginBottom:24}}><label style={{...lab,flex:1,minWidth:230}}>Navn på markering<input style={inp} value={label} onChange={e=>setLabel(e.target.value)} placeholder="Fx Efterårsferie"/></label><button style={btn} onClick={mark}>Marker valgte dage</button><button style={secondary} onClick={clearMarked}>Gør valgte til skoledage</button></div>{selected.length>0&&<p style={{color:"#486b59",fontWeight:700}}>{selected.length} dag(e) valgt · {fmt(selected.sort()[0])}{selected.length>1?` – ${fmt(selected.sort()[selected.length-1])}`:""}</p>}
 <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(320px,1fr))",gap:22}}>{months.map(m=><div key={m.key}><h2 style={{textTransform:"capitalize",marginBottom:10}}>{m.name}</h2><div style={{display:"grid",gridTemplateColumns:"48px repeat(5,1fr)",gap:4,fontSize:13}}><b style={head}>Uge</b>{["Man","Tir","Ons","Tor","Fre"].map(x=><b key={x} style={head}>{x}</b>)}{m.weeks.map(w=><div key={`${m.key}-${w.num}`} style={{display:"contents"}}><button onClick={()=>toggleWeek(w.days)} style={weekBtn}>{w.num}</button>{w.days.slice(0,5).map(d=>{const s=iso(d),outside=s<start||s>end,sel=selected.includes(s),off=excluded.get(s);return <button key={s} disabled={outside} onClick={()=>toggleDay(s)} title={off||"Skoledag"} style={{...dayBtn,opacity:outside?.25:1,background:sel?"#d8c08c":off?"#efe0b7":"#fff",borderColor:sel?"#a57c2b":off?"#d3b66e":"#ddd8ce"}}><strong>{d.getDate()}</strong>{off&&<small style={{display:"block",fontSize:9,overflow:"hidden",whiteSpace:"nowrap",textOverflow:"ellipsis"}}>{off}</small>}</button>})}</div>)}</div></div>)}</div></section>
 <div style={{display:"flex",gap:15,alignItems:"center",marginTop:20}}><button style={btn} onClick={save}>Gem skolekalender</button>{message&&<span>{message}</span>}</div></section></main>
}
const card:React.CSSProperties={background:"white",border:"1px solid #dedbd2",borderRadius:14,padding:24};const lab:React.CSSProperties={display:"grid",gap:7,fontWeight:700};const inp:React.CSSProperties={padding:"11px 12px",border:"1px solid #cbc7bd",borderRadius:8,fontSize:16};const btn:React.CSSProperties={padding:"11px 16px",border:"1px solid #486b59",borderRadius:8,background:"#486b59",color:"white",fontWeight:700,cursor:"pointer",height:44};const secondary:React.CSSProperties={...btn,background:"white",color:"#486b59"};const head:React.CSSProperties={textAlign:"center",padding:6,color:"#69716a"};const weekBtn:React.CSSProperties={border:0,borderRadius:7,background:"#f0eadc",fontWeight:800,color:"#486b59",cursor:"pointer",minHeight:48};const dayBtn:React.CSSProperties={border:"1px solid",borderRadius:7,minHeight:48,cursor:"pointer",padding:4,color:"#263b31"};