"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {supabase} from "../../../lib/supabase";
import {hasRole} from "../../../lib/roles";

type ClosedDay={date:string;label:string};
type EventKind="pedagogical"|"special_week"|"project"|"trip"|"event"|"other";
type CalendarEvent={date:string;label:string;kind:EventKind};
const eventKinds:{value:EventKind;label:string}[]=[
 {value:"pedagogical",label:"Pædagogisk dag"},
 {value:"special_week",label:"Specialuge / temauge"},
 {value:"project",label:"Projekt-/faguge"},
 {value:"trip",label:"Lejrskole / tur"},
 {value:"event",label:"Arrangement"},
 {value:"other",label:"Andet"}
];
const kindLabel=(kind:EventKind)=>eventKinds.find(x=>x.value===kind)?.label||"Andet";
const iso=(d:Date)=>{const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,"0"),day=String(d.getDate()).padStart(2,"0");return `${y}-${m}-${day}`};
function week(s:string){const d=new Date(s+"T12:00:00"),x=new Date(Date.UTC(d.getFullYear(),d.getMonth(),d.getDate())),day=x.getUTCDay()||7;x.setUTCDate(x.getUTCDate()+4-day);const ys=new Date(Date.UTC(x.getUTCFullYear(),0,1));return Math.ceil((((x.getTime()-ys.getTime())/86400000)+1)/7)}
const fmt=(s:string)=>new Date(s+"T12:00:00").toLocaleDateString("da-DK",{day:"numeric",month:"short"});

export default function Page(){
 const[ready,setReady]=useState(false),[schoolId,setSchoolId]=useState<number|null>(null),[start,setStart]=useState("2026-08-10"),[end,setEnd]=useState("2027-06-25"),[closed,setClosed]=useState<ClosedDay[]>([]),[events,setEvents]=useState<CalendarEvent[]>([]),[message,setMessage]=useState(""),[loadError,setLoadError]=useState("");
 const[selected,setSelected]=useState<string[]>([]),[label,setLabel]=useState(""),[eventKind,setEventKind]=useState<EventKind>("pedagogical"),[view,setView]=useState(new Date(2026,7,1));

 useEffect(()=>{(async()=>{
  const{data}=await supabase.auth.getSession();const u=data.session?.user;
  if(!u){location.replace("/");return}
  if(!hasRole(u,"admin")){location.replace("/noticeboard");return}
  const{data:m,error:mErr}=await supabase.from("school_memberships").select("school_id").eq("user_id",u.id).eq("role","admin").eq("active",true).limit(1).maybeSingle();
  if(mErr||!m?.school_id){setLoadError(mErr?.message||"Din administratorkonto er ikke knyttet til en aktiv skole.");setReady(true);return}
  setSchoolId(m.school_id);
  const{data:r,error:rErr}=await supabase.from("school_settings").select("school_year_start,school_year_end,closed_days,calendar_events").eq("school_id",m.school_id).maybeSingle();
  if(rErr){setLoadError(rErr.message);setReady(true);return}
  if(r){if(r.school_year_start){setStart(r.school_year_start);const d=new Date(r.school_year_start+"T12:00:00");setView(new Date(d.getFullYear(),d.getMonth(),1))}if(r.school_year_end)setEnd(r.school_year_end);if(Array.isArray(r.closed_days))setClosed(r.closed_days as ClosedDay[]);if(Array.isArray(r.calendar_events))setEvents(r.calendar_events as CalendarEvent[])}
  setReady(true)
 })()},[]);

 const excluded=useMemo(()=>new Map(closed.map(x=>[x.date,x.label])),[closed]);
 const eventsByDate=useMemo(()=>{const map=new Map<string,CalendarEvent[]>();for(const event of events){const list=map.get(event.date)||[];list.push(event);map.set(event.date,list)}return map},[events]);
 const schoolDays=useMemo(()=>{let n=0,d=new Date(start+"T12:00:00"),e=new Date(end+"T12:00:00");while(d<=e){if(d.getDay()>0&&d.getDay()<6&&!excluded.has(iso(d)))n++;d.setDate(d.getDate()+1)}return n},[start,end,excluded]);
 const monthWeeks=useMemo(()=>{const first=new Date(view.getFullYear(),view.getMonth(),1);let d=new Date(first);d.setDate(d.getDate()-((d.getDay()+6)%7));const last=new Date(view.getFullYear(),view.getMonth()+1,0),out:{num:number;days:Date[]}[]=[];while(d<=last){const days=Array.from({length:7},(_,i)=>{const x=new Date(d);x.setDate(x.getDate()+i);return x});out.push({num:week(iso(d)),days});d.setDate(d.getDate()+7)}return out},[view]);
 function toggleDay(s:string){if(s<start||s>end)return;setSelected(v=>v.includes(s)?v.filter(x=>x!==s):[...v,s])}
 function toggleWeek(days:Date[]){const valid=days.filter(d=>iso(d)>=start&&iso(d)<=end).map(iso);const all=valid.every(x=>selected.includes(x));setSelected(v=>all?v.filter(x=>!valid.includes(x)):[...new Set([...v,...valid])])}
 function markClosed(){if(!selected.length)return;const l=label.trim()||"Lukkedag",set=new Set(selected);setClosed(v=>[...v.filter(x=>!set.has(x.date)),...selected.map(date=>({date,label:l}))].sort((a,b)=>a.date.localeCompare(b.date)));setSelected([]);setLabel("")}
 function markEvent(){if(!selected.length)return;const l=label.trim()||kindLabel(eventKind),set=new Set(selected);setEvents(v=>[...v.filter(x=>!(set.has(x.date)&&x.kind===eventKind)),...selected.map(date=>({date,label:l,kind:eventKind}))].sort((a,b)=>a.date.localeCompare(b.date)||a.kind.localeCompare(b.kind)));setSelected([]);setLabel("")}
 function clearMarked(){const set=new Set(selected);setClosed(v=>v.filter(x=>!set.has(x.date)));setEvents(v=>v.filter(x=>!set.has(x.date)));setSelected([])}
 function move(n:number){setSelected([]);setView(v=>new Date(v.getFullYear(),v.getMonth()+n,1))}
 async function save(){if(!schoolId){setMessage("Skolen kunne ikke bestemmes.");return}setMessage("Gemmer…");const{error}=await supabase.from("school_settings").upsert({school_id:schoolId,school_year_start:start||null,school_year_end:end||null,closed_days:closed,calendar_events:events},{onConflict:"school_id"});setMessage(error?`Kunne ikke gemme: ${error.message}`:"Skolekalenderen er gemt ✓")}

 if(!ready)return <main style={{padding:40}}>Henter skoleopsætning…</main>;
 if(loadError)return <main style={{minHeight:"100vh",background:"#f5f2ea",padding:40}}><section style={{...card,maxWidth:720,margin:"0 auto"}}><h1>Skolekalenderen kunne ikke åbnes</h1><p>{loadError}</p><Link href="/admin">← Administration</Link></section></main>;
 const monthName=view.toLocaleDateString("da-DK",{month:"long",year:"numeric"});
 return <main style={{minHeight:"100vh",background:"#f5f2ea"}}><header style={{background:"#486b59",color:"white",padding:"18px 6vw",display:"flex",justifyContent:"space-between",gap:12,alignItems:"center"}}><div><strong style={{fontSize:22}}>Administration · Skoleopsætning</strong><small style={{display:"block",opacity:.8}}>Skoleår, ferier, specialuger og fælles dage</small></div><Link href="/admin" style={{color:"white"}}>← Administration</Link></header><section style={{maxWidth:1050,margin:"auto",padding:"42px 24px"}}><p className="eyebrow">SKOLEÅR</p><h1 style={{fontSize:44,margin:"0 0 8px"}}>Skolens kalender</h1><p style={{fontSize:18,color:"#626a63"}}>Kalenderen kan både markere dage, hvor skolen er lukket, og dage hvor der sker noget særligt. Weekender er med, fordi en friskole også kan have undervisning, ture og arbejdsdage lørdag eller søndag.</p>
 <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(240px,1fr))",gap:18,margin:"28px 0"}}><section style={card}><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))",gap:14}}><label style={lab}>Første skoledag<input style={inp} type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label style={lab}>Sidste skoledag<input style={inp} type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label></div></section><section style={card}><span className="eyebrow">BEREGNET</span><strong style={{display:"block",fontSize:48,color:"#294a3c"}}>{schoolDays}</strong><b>almindelige hverdags-skoledage</b><small style={{display:"block",marginTop:5,color:"#777"}}>Weekenddage tælles ikke automatisk med.</small></section></div>
 <section style={card}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,marginBottom:20}}><button type="button" style={nav} onClick={()=>move(-1)}>←</button><h2 style={{textTransform:"capitalize",fontSize:27,margin:0}}>{monthName}</h2><button type="button" style={nav} onClick={()=>move(1)}>→</button></div><div style={{display:"grid",gridTemplateColumns:"52px repeat(7,minmax(92px,1fr))",gap:6,overflowX:"auto",paddingBottom:4}}><b style={head}>Uge</b>{["Mandag","Tirsdag","Onsdag","Torsdag","Fredag","Lørdag","Søndag"].map(x=><b key={x} style={head}>{x}</b>)}{monthWeeks.map(w=><div key={w.num} style={{display:"contents"}}><button type="button" onClick={()=>toggleWeek(w.days)} style={weekBtn}>{w.num}</button>{w.days.map(d=>{const s=iso(d),other=d.getMonth()!==view.getMonth(),outside=s<start||s>end,sel=selected.includes(s),off=excluded.get(s),dayEvents=eventsByDate.get(s)||[];return <button type="button" key={s} disabled={outside} onClick={()=>toggleDay(s)} title={[off?`Lukket: ${off}`:"",...dayEvents.map(e=>`${kindLabel(e.kind)}: ${e.label}`)].filter(Boolean).join(" · ")||"Almindelig dag"} style={{...dayBtn,opacity:outside?.25:other?.45:1,background:sel?"#d8c08c":off?"#efe0b7":dayEvents.length?"#e7eef2":"#fff",borderColor:sel?"#a57c2b":off?"#d3b66e":dayEvents.length?"#b9cbd5":"#ddd8ce"}}><strong style={{fontSize:16}}>{d.getDate()}</strong>{off&&<small style={closedTag}>Lukket · {off}</small>}{dayEvents.slice(0,2).map((event,i)=><small key={`${event.kind}-${i}`} style={eventTag}>{event.label}</small>)}{dayEvents.length>2&&<small style={moreTag}>+{dayEvents.length-2}</small>}</button>})}</div>)}</div>
 <div style={{borderTop:"1px solid #e7e2d8",marginTop:22,paddingTop:18,display:"grid",gap:12}}><div style={{display:"grid",gridTemplateColumns:"minmax(220px,1fr) minmax(190px,260px)",gap:10}}><label style={lab}>Navn på markering<input style={inp} value={label} onChange={e=>setLabel(e.target.value)} placeholder="Fx Teateruge, pædagogisk dag eller efterårsferie"/></label><label style={lab}>Type<select style={inp} value={eventKind} onChange={e=>setEventKind(e.target.value as EventKind)}>{eventKinds.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select></label></div><div style={{display:"flex",gap:10,flexWrap:"wrap"}}><button type="button" style={btn} onClick={markEvent}>Tilføj markering</button><button type="button" style={closedButton} onClick={markClosed}>Marker som ferie/lukkedag</button><button type="button" style={secondary} onClick={clearMarked}>Fjern markeringer på valgte dage</button></div></div>{selected.length>0&&<p style={{color:"#486b59",fontWeight:700}}>{selected.length} dag(e) valgt · {fmt([...selected].sort()[0])}{selected.length>1?` – ${fmt([...selected].sort().at(-1)! )}`:""}</p>}</section>
 <section style={{...card,marginTop:18}}><p className="eyebrow">TYPER</p><div style={{display:"flex",gap:8,flexWrap:"wrap",marginTop:8}}><span style={legendClosed}>Ferie / lukket</span>{eventKinds.map(x=><span key={x.value} style={legendEvent}>{x.label}</span>)}</div><p style={{color:"#6f756f",marginBottom:0}}>En markering som fx <b>Teateruge</b> lukker ikke skolen. Den vises bare som kontekst i kalenderen. Ferie/lukkedag beholder sin særlige betydning.</p></section>
 <div style={{display:"flex",gap:15,alignItems:"center",marginTop:20,flexWrap:"wrap"}}><button type="button" style={btn} onClick={save}>Gem skolekalender</button>{message&&<span style={{fontWeight:700}}>{message}</span>}</div></section></main>
}
const card:React.CSSProperties={background:"white",border:"1px solid #dedbd2",borderRadius:14,padding:24};const lab:React.CSSProperties={display:"grid",gap:7,fontWeight:700};const inp:React.CSSProperties={padding:"11px 12px",border:"1px solid #cbc7bd",borderRadius:8,fontSize:16,minWidth:0};const btn:React.CSSProperties={padding:"11px 16px",border:"1px solid #486b59",borderRadius:8,background:"#486b59",color:"white",fontWeight:700,cursor:"pointer",minHeight:44};const closedButton:React.CSSProperties={...btn,background:"#8a6a2e",borderColor:"#8a6a2e"};const secondary:React.CSSProperties={...btn,background:"white",color:"#486b59"};const nav:React.CSSProperties={width:42,height:38,border:"1px solid #d5d0c6",borderRadius:8,background:"#faf8f3",fontSize:20,cursor:"pointer"};const head:React.CSSProperties={textAlign:"center",padding:7,color:"#69716a",fontSize:12};const weekBtn:React.CSSProperties={border:0,borderRadius:7,background:"#f0eadc",fontWeight:800,color:"#486b59",cursor:"pointer",minHeight:76};const dayBtn:React.CSSProperties={border:"1px solid",borderRadius:8,minHeight:76,cursor:"pointer",padding:6,color:"#263b31",textAlign:"left"};const closedTag:React.CSSProperties={display:"block",fontSize:9,marginTop:4,fontWeight:900,overflow:"hidden",whiteSpace:"nowrap",textOverflow:"ellipsis",color:"#795d28"};const eventTag:React.CSSProperties={display:"block",fontSize:9,marginTop:3,overflow:"hidden",whiteSpace:"nowrap",textOverflow:"ellipsis",color:"#47626e"};const moreTag:React.CSSProperties={display:"block",fontSize:9,marginTop:3,color:"#6d777d"};const legendClosed:React.CSSProperties={padding:"5px 8px",borderRadius:999,background:"#efe0b7",fontSize:11,fontWeight:800};const legendEvent:React.CSSProperties={padding:"5px 8px",borderRadius:999,background:"#e7eef2",fontSize:11,fontWeight:800};
