"use client";
import {useEffect,useState} from "react";
import {supabase} from "../../lib/supabase";

export default function ParentPage(){
 const[ready,setReady]=useState(false),[email,setEmail]=useState("");
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{const user=data.session?.user;if(!user){window.location.replace("/");return}const role=user.user_metadata?.role||user.app_metadata?.role;if(role!=="parent"){window.location.replace("/");return}setEmail(user.email||"");setReady(true)})},[]);
 async function logout(){await supabase.auth.signOut();window.location.href="/"}
 if(!ready)return <main className="login"><div className="loginCard"><h1>Forældreportalen</h1><p>Henter dit område…</p></div></main>;
 const cards=[{icon:"▦",title:"Skema",text:"Se dit barns skema og dagens undervisning."},{icon:"✓",title:"Fravær",text:"Få overblik over registreret fravær."},{icon:"✎",title:"Opgaver",text:"Se aktuelle opgaver og afleveringer."},{icon:"✦",title:"Beskeder",text:"Information fra skolen og barnets lærere."}];
 return <main style={{minHeight:"100vh",background:"#f5f3ee",color:"#26342e"}}><header style={{background:"#243d33",color:"white",padding:"22px 32px"}}><div style={{maxWidth:1100,margin:"0 auto",display:"flex",justifyContent:"space-between",alignItems:"center",gap:18,flexWrap:"wrap"}}><div><strong style={{fontFamily:"Georgia,serif",fontSize:25}}>Klasseværelset · Forældre</strong><small style={{display:"block",opacity:.75,marginTop:3}}>{email}</small></div><button onClick={logout} style={{padding:"10px 16px",borderRadius:8,border:"1px solid rgba(255,255,255,.5)",background:"transparent",color:"white",cursor:"pointer"}}>Log ud</button></div></header><section style={{maxWidth:1100,margin:"0 auto",padding:"52px 24px"}}><p className="eyebrow">FORÆLDREPORTAL</p><h1 style={{fontFamily:"Georgia,serif",fontSize:42,margin:"8px 0"}}>Velkommen</h1><p style={{maxWidth:720,fontSize:18,color:"#6d746f",lineHeight:1.55}}>Her får du ét roligt overblik over dit barns skolehverdag. Du ser kun oplysninger om de børn, din konto er knyttet til.</p><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(230px,1fr))",gap:18,marginTop:36}}>{cards.map(c=><article key={c.title} style={{background:"white",border:"1px solid #ddd9d0",borderRadius:14,padding:24,minHeight:165}}><div style={{fontSize:30}}>{c.icon}</div><h2 style={{fontFamily:"Georgia,serif",margin:"14px 0 8px"}}>{c.title}</h2><p style={{color:"#687068",lineHeight:1.5}}>{c.text}</p></article>)}</div><div style={{marginTop:34,padding:20,background:"#e7eee9",borderRadius:12,color:"#3e594b"}}><strong>Forældreområdet er klar som fundament.</strong><div style={{marginTop:6}}>Næste trin er at koble hver forælder sikkert til deres barn eller børn og derefter hente skema, fravær, opgaver og beskeder fra databasen.</div></div></section></main>
}