"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { supabase } from "../../lib/supabase";
import {hasRole} from "../../lib/roles";
import RoleNoticeboard from "../RoleNoticeboard";

export default function AdminPage(){
 const[ready,setReady]=useState(false),[email,setEmail]=useState(""),[canParent,setCanParent]=useState(false),[canBoard,setCanBoard]=useState(false);
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{const user=data.session?.user;if(!user){window.location.replace("/");return}if(!hasRole(user,"admin")){window.location.replace("/noticeboard");return}setEmail(user.email||"");setCanParent(hasRole(user,"parent"));setCanBoard(hasRole(user,"board"));setReady(true)})},[]);
 async function logout(){await supabase.auth.signOut();window.location.href="/"}
 if(!ready)return <main className="login"><div className="loginCard"><h1>Administration</h1><p>Henter administratorområdet…</p></div></main>;
 const cards=[{icon:"▦",title:"Skemaer",text:"Opret og redigér klassernes skemaer.",href:"/admin/schedule"},{icon:"✓",title:"Fravær",text:"Før fravær og se fraværsstatistik for skolens elever.",href:"/admin/absence"},{icon:"♙",title:"Brugere & klasser",text:"Opret klasser og elever, og administrér skolens brugere.",href:"/admin/users"},{icon:"↔",title:"Lærere & klasser",text:"Tilknyt en eller flere lærere til skolens klasser.",href:"/admin/teacher-classes"},{icon:"⚙",title:"Skoleopsætning",text:"Skoleår, skoledage og ferie-/lukkedage.",href:"/admin/settings"}];
 return <main style={{minHeight:"100vh",background:"#f5f2ea"}}><header style={{background:"#486b59",color:"white",padding:"18px 6vw",display:"flex",justifyContent:"space-between",alignItems:"center",gap:18,flexWrap:"wrap"}}><div><strong style={{fontSize:22}}>Klasseværelset · Administration</strong><div style={{fontSize:13,opacity:.85}}>{email}</div></div><div style={{display:"flex",gap:10,alignItems:"center",flexWrap:"wrap"}}><button onClick={()=>window.location.href="/noticeboard"} style={{padding:"10px 16px",borderRadius:8,border:"1px solid rgba(255,255,255,.65)",background:"white",color:"#486b59",fontWeight:700,cursor:"pointer"}}>✎ Lærerområdet</button>{canParent&&<button onClick={()=>window.location.href="/parent"} style={{padding:"10px 16px",borderRadius:8,border:"1px solid rgba(255,255,255,.65)",background:"white",color:"#486b59",fontWeight:700,cursor:"pointer"}}>⌂ Forældreområdet</button>}{canBoard&&<button onClick={()=>window.location.href="/board"} style={{padding:"10px 16px",borderRadius:8,border:"1px solid rgba(255,255,255,.65)",background:"white",color:"#486b59",fontWeight:700,cursor:"pointer"}}>✦ Bestyrelse</button>}<button onClick={logout} style={{padding:"10px 16px",borderRadius:8,border:"1px solid rgba(255,255,255,.5)",background:"transparent",color:"white",cursor:"pointer"}}>Log ud</button></div></header><section style={{maxWidth:1100,margin:"0 auto",padding:"52px 24px"}}><p className="eyebrow">ADMINISTRATOR</p><h1 style={{fontSize:42,marginBottom:8}}>Skolens administration</h1><p style={{maxWidth:700,fontSize:18,color:"#5f665f"}}>Her samler vi de funktioner, der gælder hele skolen.</p><RoleNoticeboard audience="admin"/><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(230px,1fr))",gap:18,marginTop:38}}>{cards.map(x=>{const card=<article style={{background:"white",border:"1px solid #dedbd2",borderRadius:14,padding:24,minHeight:170,boxSizing:"border-box",height:"100%"}}><div style={{fontSize:30}}>{x.icon}</div><h2 style={{margin:"15px 0 8px"}}>{x.title}</h2><p style={{color:"#687068",lineHeight:1.5}}>{x.text}</p>{x.href&&<strong style={{color:"#486b59"}}>Åbn →</strong>}</article>;return x.href?<Link key={x.title} href={x.href} style={{textDecoration:"none",color:"inherit"}}>{card}</Link>:<div key={x.title}>{card}</div>})}</div></section></main>
}
