"use client";

import { useEffect, useState } from "react";
import { supabase } from "../../lib/supabase";

export default function AdminPage(){
 const[ready,setReady]=useState(false),[email,setEmail]=useState("");
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{const user=data.session?.user;if(!user){window.location.replace("/");return}const role=user.user_metadata?.role||user.app_metadata?.role;if(role!=="admin"){window.location.replace("/noticeboard");return}setEmail(user.email||"");setReady(true)})},[]);
 async function logout(){await supabase.auth.signOut();window.location.href="/"}
 if(!ready)return <main className="login"><div className="loginCard"><h1>Administration</h1><p>Henter administratorområdet…</p></div></main>;
 return <main style={{minHeight:"100vh",background:"#f5f2ea"}}><header style={{background:"#486b59",color:"white",padding:"18px 6vw",display:"flex",justifyContent:"space-between",alignItems:"center",gap:18,flexWrap:"wrap"}}><div><strong style={{fontSize:22}}>Klasseværelset · Administration</strong><div style={{fontSize:13,opacity:.85}}>{email}</div></div><div style={{display:"flex",gap:10,alignItems:"center",flexWrap:"wrap"}}><button onClick={()=>window.location.href="/noticeboard"} style={{padding:"10px 16px",borderRadius:8,border:"1px solid rgba(255,255,255,.65)",background:"white",color:"#486b59",fontWeight:700,cursor:"pointer"}}>✎ Gå til lærerområdet</button><button onClick={logout} style={{padding:"10px 16px",borderRadius:8,border:"1px solid rgba(255,255,255,.5)",background:"transparent",color:"white",cursor:"pointer"}}>Log ud</button></div></header><section style={{maxWidth:1100,margin:"0 auto",padding:"52px 24px"}}><p className="eyebrow">ADMINISTRATOR</p><h1 style={{fontSize:42,marginBottom:8}}>Skolens administration</h1><p style={{maxWidth:700,fontSize:18,color:"#5f665f"}}>Her samler vi de funktioner, der gælder hele skolen. Første version gør plads til skemaer, fravær og skolens grundopsætning.</p><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(230px,1fr))",gap:18,marginTop:38}}>{[{icon:"▦",title:"Skemaer",text:"Opret og redigér klassernes og lærernes skemaer."},{icon:"✓",title:"Sygefravær",text:"Registrér fravær og få overblik over dagens bemanding."},{icon:"♙",title:"Brugere",text:"Administrér lærere, elever og adgang til systemet."},{icon:"⚙",title:"Skoleopsætning",text:"Klasser, skoleår og fælles indstillinger."}].map(x=><article key={x.title} style={{background:"white",border:"1px solid #dedbd2",borderRadius:14,padding:24,minHeight:170}}><div style={{fontSize:30}}>{x.icon}</div><h2 style={{margin:"15px 0 8px"}}>{x.title}</h2><p style={{color:"#687068",lineHeight:1.5}}>{x.text}</p></article>)}</div><div style={{marginTop:36,padding:22,background:"#e7eee9",borderRadius:12,color:"#3e594b"}}><strong>Du kan nu skifte direkte mellem administrator- og lærerområdet.</strong><div style={{marginTop:6}}>Du behøver kun logge ud, når du faktisk vil afslutte din session.</div></div></section></main>
}