"use client";

import Link from "next/link";
import {useEffect,useState} from "react";
import {supabase} from "../../lib/supabase";
import {hasRole} from "../../lib/roles";

const cards=[
 {icon:"▤",title:"Møder & dagsordener",text:"Se kommende bestyrelsesmøder og dagsordener.",href:"/board/meetings",status:"Åbn →"},
 {icon:"✓",title:"Referater & beslutninger",text:"Find referater og få overblik over bestyrelsens beslutninger.",status:"Næste modul →"},
 {icon:"▱",title:"Dokumentarkiv",text:"Vedtægter, politikker, budgetter og øvrige bestyrelsesdokumenter.",status:"Kommer →"},
 {icon:"→",title:"Opgaver & opfølgning",text:"Hold styr på aftaler, ansvarlige og det, der skal følges op på.",status:"Kommer →"}
];

export default function BoardPage(){
 const[ready,setReady]=useState(false),[email,setEmail]=useState(""),[isAdmin,setIsAdmin]=useState(false),[isTeacher,setIsTeacher]=useState(false),[isParent,setIsParent]=useState(false),[nextMeeting,setNextMeeting]=useState<any>(null);
 useEffect(()=>{(async()=>{const{data}=await supabase.auth.getSession();const user=data.session?.user;if(!user){window.location.replace("/");return}if(!hasRole(user,"board")&&!hasRole(user,"admin")){window.location.replace("/");return}setEmail(user.email||"");setIsAdmin(hasRole(user,"admin"));setIsTeacher(hasRole(user,"teacher"));setIsParent(hasRole(user,"parent"));const today=new Date().toISOString().slice(0,10);const{data:m}=await supabase.from("board_meetings").select("*").gte("meeting_date",today).order("meeting_date",{ascending:true}).order("start_time",{ascending:true}).limit(1).maybeSingle();setNextMeeting(m||null);setReady(true)})()},[]);
 async function logout(){await supabase.auth.signOut();window.location.href="/"}
 if(!ready)return <main style={{padding:50}}>Åbner bestyrelsesområdet…</main>;
 return <main style={{minHeight:"100vh",background:"#f5f3ee",color:"#26342e"}}><header style={{background:"#243d33",color:"white",padding:"22px 6vw"}}><div style={{maxWidth:1160,margin:"0 auto",display:"flex",justifyContent:"space-between",alignItems:"center",gap:18,flexWrap:"wrap"}}><div><strong style={{fontFamily:"Georgia,serif",fontSize:27}}>Klasseværelset · Bestyrelsen</strong><div style={{fontSize:13,opacity:.75}}>{email}</div></div><div style={{display:"flex",gap:9,flexWrap:"wrap"}}>{isTeacher&&<Link href="/noticeboard" style={nav}>Lærerområdet</Link>}{isParent&&<Link href="/parent" style={nav}>Forældre</Link>}{isAdmin&&<Link href="/admin" style={nav}>Administration</Link>}<button onClick={logout} style={{...nav,cursor:"pointer"}}>Log ud</button></div></div></header><section style={{maxWidth:1160,margin:"0 auto",padding:"54px 26px"}}><p style={{fontSize:11,fontWeight:800,letterSpacing:1.7,color:"#718077"}}>BESTYRELSESPORTAL</p><h1 style={{fontFamily:"Georgia,serif",fontSize:46,margin:"8px 0 10px"}}>Bestyrelsen</h1><p style={{fontSize:18,color:"#707670",maxWidth:720,lineHeight:1.55}}>Et roligt arbejdsrum til skolens bestyrelse. Her samles møder, dokumenter, beslutninger og opfølgning uden adgang til elevernes eller lærernes interne oplysninger.</p><Link href="/board/meetings" style={{textDecoration:"none",color:"inherit"}}><section style={{background:"#e8dfca",borderRadius:16,padding:24,marginTop:30,border:"1px solid #d8ccb2"}}><p style={{margin:0,fontSize:12,fontWeight:800,letterSpacing:1.3,color:"#6f756e"}}>NÆSTE MØDE</p>{nextMeeting?<><h2 style={{fontFamily:"Georgia,serif",margin:"8px 0"}}>{nextMeeting.title}</h2><p style={{margin:0,color:"#687068"}}>{new Date(nextMeeting.meeting_date+"T12:00:00").toLocaleDateString("da-DK",{weekday:"long",day:"numeric",month:"long",year:"numeric"})}{nextMeeting.start_time?` · kl. ${nextMeeting.start_time.slice(0,5)}`:""}{nextMeeting.location?` · ${nextMeeting.location}`:""}</p></>:<><h2 style={{fontFamily:"Georgia,serif",margin:"8px 0"}}>Ingen kommende møder</h2><p style={{margin:0,color:"#687068"}}>Åbn mødemodulet for at oprette det næste bestyrelsesmøde.</p></>}</section></Link><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(240px,1fr))",gap:18,marginTop:24}}>{cards.map(x=>{const card=<article style={{background:"white",border:"1px solid #dedbd2",borderRadius:14,padding:24,minHeight:180,height:"100%",boxSizing:"border-box"}}><div style={{fontSize:29,color:"#486b59"}}>{x.icon}</div><h2 style={{fontFamily:"Georgia,serif",margin:"15px 0 8px"}}>{x.title}</h2><p style={{color:"#687068",lineHeight:1.5}}>{x.text}</p><span style={{fontWeight:800,color:x.href?"#486b59":"#8a8f89"}}>{x.status}</span></article>;return x.href?<Link key={x.title} href={x.href} style={{textDecoration:"none",color:"inherit"}}>{card}</Link>:<div key={x.title}>{card}</div>})}</div></section></main>
}
const nav={padding:"9px 13px",borderRadius:8,border:"1px solid rgba(255,255,255,.4)",background:"transparent",color:"white",textDecoration:"none",fontWeight:700 as const,fontSize:13};