"use client";
import Link from "next/link";
import {useEffect,useState,type ReactNode} from "react";
import {useParams,useSearchParams} from "next/navigation";
import {supabase} from "../../../../../lib/supabase";
import {hasRole} from "../../../../../lib/roles";
import UnitMaterials from "./UnitMaterials";

type Room={id:number;class_id:number;subject_id:number;title:string|null};
type Unit={id:number;title:string;driving_question:string|null;summary:string|null;learning_goals:string[];start_date:string|null;end_date:string|null;status:"planned"|"active"|"completed"|"archived";visible_to_students:boolean;visible_to_guardians:boolean;position:number};
type Assignment={id:number;title:string;type:string};
type LinkRow={subject_unit_id:number;assignment_id:number;position:number};
type LessonLink={id:number;schedule_entry_id:number;lesson_date:string;subject_unit_id:number|null;status:"planned"|"active"|"completed"|"cancelled"};
type Form={title:string;question:string;summary:string;goals:string;start:string;end:string;status:Unit["status"];students:boolean;guardians:boolean};
const blank:Form={title:"",question:"",summary:"",goals:"",start:"",end:"",status:"planned",students:false,guardians:false};
const statuses:Record<Unit["status"],string>={planned:"Planlagt",active:"I gang",completed:"Afsluttet",archived:"Arkiveret"};
const lessonStatuses:Record<LessonLink["status"],string>={planned:"Planlagt",active:"I gang",completed:"Afsluttet",cancelled:"Aflyst"};

export default function UnitsPage(){
 const roomId=Number(useParams<{roomId:string}>().roomId);
 const search=useSearchParams();
 const newUnitId=Number(search.get("new")||0);
 const focusUnitId=Number(search.get("focus")||0);
 const highlightedUnitId=newUnitId||focusUnitId;
 const[ready,setReady]=useState(false),[room,setRoom]=useState<Room|null>(null),[className,setClassName]=useState(""),[subjectName,setSubjectName]=useState(""),[units,setUnits]=useState<Unit[]>([]),[assignments,setAssignments]=useState<Assignment[]>([]),[links,setLinks]=useState<LinkRow[]>([]),[lessonLinks,setLessonLinks]=useState<LessonLink[]>([]),[canEdit,setCanEdit]=useState(false),[form,setForm]=useState<Form>(blank),[editing,setEditing]=useState<number|null>(null),[showForm,setShowForm]=useState(false),[saving,setSaving]=useState(false),[message,setMessage]=useState(""),[openedNew,setOpenedNew]=useState(false),[focused,setFocused]=useState(false);
 async function load(){
  const{data:auth}=await supabase.auth.getSession();const user=auth.session?.user;if(!user){location.replace("/?teacher=1");return}
  const[r,u,a,t]=await Promise.all([supabase.from("class_subjects").select("id,class_id,subject_id,title").eq("id",roomId).eq("active",true).maybeSingle(),supabase.from("subject_units").select("id,title,driving_question,summary,learning_goals,start_date,end_date,status,visible_to_students,visible_to_guardians,position").eq("class_subject_id",roomId).order("start_date",{ascending:true,nullsFirst:false}).order("position"),supabase.from("assignments").select("id,title,type").eq("class_subject_id",roomId).order("id",{ascending:false}),supabase.from("class_subject_teachers").select("user_id").eq("class_subject_id",roomId).eq("user_id",user.id).maybeSingle()]);
  if(r.error||!r.data){setMessage("Du har ikke adgang til faglokalet.");setReady(true);return}const rr=r.data as Room,uu=(u.data||[]) as Unit[];
  const ids=uu.map(x=>x.id);
  const[c,s,l,ll]=await Promise.all([supabase.from("classes").select("name").eq("id",rr.class_id).maybeSingle(),supabase.from("subjects").select("name").eq("id",rr.subject_id).maybeSingle(),ids.length?supabase.from("subject_unit_assignments").select("subject_unit_id,assignment_id,position").in("subject_unit_id",ids):Promise.resolve({data:[]}),ids.length?supabase.from("lesson_instances").select("id,schedule_entry_id,lesson_date,subject_unit_id,status").in("subject_unit_id",ids).order("lesson_date",{ascending:true}):Promise.resolve({data:[]})]);
  setRoom(rr);setUnits(uu);setAssignments((a.data||[]) as Assignment[]);setLinks((l.data||[]) as LinkRow[]);setLessonLinks((ll.data||[]) as LessonLink[]);setClassName(String(c.data?.name||""));setSubjectName(String(s.data?.name||""));setCanEdit(hasRole(user,"admin")||!!t.data);setReady(true);
 }
 useEffect(()=>{if(Number.isFinite(roomId)&&roomId>0)load();else{setMessage("Faglokalet er ugyldigt.");setReady(true)}},[roomId]);
 useEffect(()=>{if(!ready||openedNew||!newUnitId||!canEdit)return;const unit=units.find(x=>x.id===newUnitId);if(!unit)return;setEditing(unit.id);setForm({title:unit.title,question:unit.driving_question||"",summary:unit.summary||"",goals:unit.learning_goals.join("\n"),start:unit.start_date||"",end:unit.end_date||"",status:unit.status,students:unit.visible_to_students,guardians:unit.visible_to_guardians});setShowForm(true);setMessage("Nyt forløb oprettet ✓ Byg videre herfra.");setOpenedNew(true);requestAnimationFrame(()=>document.getElementById("unit-editor")?.scrollIntoView({behavior:"smooth",block:"start"}))},[ready,openedNew,newUnitId,canEdit,units]);
 useEffect(()=>{if(!ready||focused||newUnitId||!focusUnitId)return;if(!units.some(x=>x.id===focusUnitId))return;setFocused(true);requestAnimationFrame(()=>document.getElementById(`unit-${focusUnitId}`)?.scrollIntoView({behavior:"smooth",block:"center"}))},[ready,focused,newUnitId,focusUnitId,units]);
 function begin(unit?:Unit){setEditing(unit?.id||null);setForm(unit?{title:unit.title,question:unit.driving_question||"",summary:unit.summary||"",goals:unit.learning_goals.join("\n"),start:unit.start_date||"",end:unit.end_date||"",status:unit.status,students:unit.visible_to_students,guardians:unit.visible_to_guardians}:blank);setShowForm(true);setMessage("")}
 function close(){setShowForm(false);setEditing(null);setForm(blank)}
 async function save(){if(!canEdit||!form.title.trim()||saving)return;if(form.start&&form.end&&form.end<form.start){setMessage("Slutdato kan ikke ligge før startdato.");return}setSaving(true);const payload={class_subject_id:roomId,title:form.title.trim(),driving_question:form.question.trim()||null,summary:form.summary.trim()||null,learning_goals:form.goals.split("\n").map(x=>x.trim()).filter(Boolean),start_date:form.start||null,end_date:form.end||null,status:form.status,visible_to_students:form.students,visible_to_guardians:form.guardians,position:editing?units.find(x=>x.id===editing)?.position||0:units.length};const res=editing?await supabase.from("subject_units").update(payload).eq("id",editing):await supabase.from("subject_units").insert(payload);setSaving(false);if(res.error){setMessage(res.error.message);return}close();setMessage("Forløbet er gemt ✓");await load()}
 async function remove(u:Unit){if(!canEdit||!confirm(`Slet forløbet “${u.title}”? Opgaver, materialer og lektioner bevares, men forløbskoblingen fjernes.`))return;const{error}=await supabase.from("subject_units").delete().eq("id",u.id);if(error)setMessage(error.message);else{setMessage("Forløbet er slettet.");await load()}}
 async function attach(unitId:number,assignmentId:number){if(!assignmentId)return;const{error}=await supabase.from("subject_unit_assignments").insert({subject_unit_id:unitId,assignment_id:assignmentId,position:links.filter(x=>x.subject_unit_id===unitId).length});if(error)setMessage(error.message);else await load()}
 async function detach(unitId:number,assignmentId:number){const{error}=await supabase.from("subject_unit_assignments").delete().eq("subject_unit_id",unitId).eq("assignment_id",assignmentId);if(error)setMessage(error.message);else await load()}
 if(!ready)return <main style={{padding:50}}>Åbner forløb…</main>;if(!room)return <main style={{padding:50}}><h1>Forløb kunne ikke åbnes</h1><p>{message}</p></main>;
 const shown=units.filter(x=>x.status!=="archived"),archived=units.filter(x=>x.status==="archived");
 return <main style={{minHeight:"100vh",background:"#f5f3ee",color:"#26342e"}}><header style={{background:"#243d33",color:"white",padding:"24px 32px"}}><div style={{maxWidth:1080,margin:"auto"}}><Link href={`/students/subjects/${room.id}`} style={{color:"#e7ddd0",fontWeight:850,textDecoration:"none"}}>← {room.title||subjectName||"Faglokalet"}</Link><p style={{fontSize:11,fontWeight:900,letterSpacing:1.3,opacity:.68,margin:"18px 0 0"}}>{className.toUpperCase()} · {subjectName.toUpperCase()}</p><h1 style={{fontFamily:"Georgia,serif",fontSize:36,margin:"5px 0"}}>Forløb & årsplan</h1><p style={{margin:0,opacity:.8,maxWidth:760}}>Ét levende forløb kan samle periode, mål, materialer, opgaver og konkrete lektioner. Årsplanen er visningen af de samme forløb.</p></div></header><section style={{maxWidth:1080,margin:"auto",padding:"26px 24px 80px"}}>{message&&<div style={{padding:10,background:message.includes("✓")?"#e6eee8":"#fff3cd",borderRadius:9,marginBottom:12}}>{message}</div>}<section style={{...card,background:"#eef2ed",display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,flexWrap:"wrap"}}><div><small style={eyebrow}>ÅRSPLAN SOM ARBEJDSFLADE</small><strong style={{display:"block",fontFamily:"Georgia,serif",fontSize:22}}>{shown.length} aktive/planlagte forløb</strong></div>{canEdit&&<button onClick={()=>begin()} style={primary}>+ Nyt forløb</button>}</section>
 {showForm&&canEdit&&<section id="unit-editor" style={{...card,marginTop:14,boxShadow:editing===newUnitId?"0 0 0 3px #d8e4d9":undefined}}><div style={{display:"flex",justifyContent:"space-between"}}><h2 style={{fontFamily:"Georgia,serif",margin:0}}>{editing?"Redigér forløb":"Nyt forløb"}</h2><button onClick={close} style={secondary}>Luk</button></div>{editing===newUnitId&&<div style={{marginTop:9,padding:"8px 10px",borderRadius:8,background:"#eef5ef",color:"#486b59",fontSize:12,fontWeight:850}}>NYT FORLØB · tilføj det, du har brug for nu. Resten kan vente.</div>}<div style={grid}><Field label="Titel"><input value={form.title} onChange={e=>setForm(x=>({...x,title:e.target.value}))} style={input}/></Field><Field label="Styrende spørgsmål"><input value={form.question} onChange={e=>setForm(x=>({...x,question:e.target.value}))} style={input}/></Field><Field label="Start"><input type="date" value={form.start} onChange={e=>setForm(x=>({...x,start:e.target.value}))} style={input}/></Field><Field label="Slut"><input type="date" value={form.end} onChange={e=>setForm(x=>({...x,end:e.target.value}))} style={input}/></Field><Field label="Status"><select value={form.status} onChange={e=>setForm(x=>({...x,status:e.target.value as Unit["status"]}))} style={input}>{Object.entries(statuses).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></Field></div><Field label="Kort beskrivelse"><textarea rows={3} value={form.summary} onChange={e=>setForm(x=>({...x,summary:e.target.value}))} style={input}/></Field><Field label="Læringsmål — ét pr. linje"><textarea rows={4} value={form.goals} onChange={e=>setForm(x=>({...x,goals:e.target.value}))} style={input}/></Field><div style={{display:"flex",gap:14,marginTop:10,flexWrap:"wrap"}}><label style={check}><input type="checkbox" checked={form.students} onChange={e=>setForm(x=>({...x,students:e.target.checked}))}/> Må vises til elever</label><label style={check}><input type="checkbox" checked={form.guardians} onChange={e=>setForm(x=>({...x,guardians:e.target.checked}))}/> Må vises til forældre</label></div><small style={{display:"block",color:"#777",marginTop:5}}>Kun forløb du markerer, bliver vist i elev- eller forældreportalen.</small><button disabled={saving||!form.title.trim()} onClick={save} style={{...primary,marginTop:12,opacity:(saving||!form.title.trim())?0.55:1}}>{saving?"Gemmer…":"Gem forløb"}</button></section>}
 <div style={{display:"grid",gap:12,marginTop:14}}>{shown.length?shown.map(u=><UnitCard key={u.id} unit={u} roomId={room.id} assignments={assignments} links={links} lessons={lessonLinks.filter(l=>l.subject_unit_id===u.id)} canEdit={canEdit} highlight={u.id===highlightedUnitId} edit={()=>begin(u)} remove={()=>remove(u)} attach={id=>attach(u.id,id)} detach={id=>detach(u.id,id)}/>):<section style={card}><h2>Årsplanen er tom endnu</h2><p>Opret det første forløb. Datoer er valgfrie.</p></section>}</div>{archived.length>0&&<details style={{marginTop:20}}><summary>Arkiverede forløb ({archived.length})</summary><div style={{display:"grid",gap:12,marginTop:10}}>{archived.map(u=><UnitCard key={u.id} unit={u} roomId={room.id} assignments={assignments} links={links} lessons={lessonLinks.filter(l=>l.subject_unit_id===u.id)} canEdit={canEdit} highlight={u.id===highlightedUnitId} edit={()=>begin(u)} remove={()=>remove(u)} attach={id=>attach(u.id,id)} detach={id=>detach(u.id,id)}/>)}</div></details>}</section></main>;
}
function Field({label,children}:{label:string;children:ReactNode}){return <label style={{display:"block",fontSize:12,fontWeight:900,marginTop:10}}>{label}{children}</label>}
function UnitCard({unit,roomId,assignments,links,lessons,canEdit,highlight,edit,remove,attach,detach}:{unit:Unit;roomId:number;assignments:Assignment[];links:LinkRow[];lessons:LessonLink[];canEdit:boolean;highlight:boolean;edit:()=>void;remove:()=>void;attach:(id:number)=>void;detach:(id:number)=>void}){const rows=links.filter(x=>x.subject_unit_id===unit.id),linked=rows.map(x=>assignments.find(a=>a.id===x.assignment_id)).filter(Boolean) as Assignment[],available=assignments.filter(a=>!rows.some(x=>x.assignment_id===a.id));return <article id={`unit-${unit.id}`} style={{...card,borderLeft:unit.status==="active"?"5px solid #486b59":undefined,boxShadow:highlight?"0 0 0 3px #d8e4d9":undefined,background:highlight?"#fbfdfb":"white"}}><div style={{display:"flex",justifyContent:"space-between",gap:10,flexWrap:"wrap"}}><div><div style={{display:"flex",gap:5,flexWrap:"wrap"}}><Tag>{statuses[unit.status]}</Tag><Tag>{period(unit)}</Tag>{unit.visible_to_students&&<Tag>Elev</Tag>}{unit.visible_to_guardians&&<Tag>Forælder</Tag>}</div><h2 style={{fontFamily:"Georgia,serif",margin:"8px 0 3px"}}>{unit.title}</h2>{unit.driving_question&&<strong>“{unit.driving_question}”</strong>}{unit.summary&&<p style={{color:"#68716b"}}>{unit.summary}</p>}</div>{canEdit&&<div><button onClick={edit} style={secondary}>Redigér</button> <button onClick={remove} style={danger}>Slet</button></div>}</div>{unit.learning_goals.length>0&&<ul>{unit.learning_goals.map((x,i)=><li key={i}>{x}</li>)}</ul>}{lessons.length>0&&<div style={{borderTop:"1px solid #e4e0d7",paddingTop:10,marginTop:10}}><small style={eyebrow}>LEKTIONER I FORLØBET</small><div style={{display:"flex",gap:7,flexWrap:"wrap",marginTop:7}}>{lessons.map(lesson=><Link key={lesson.id} href={`/calendar/lesson/${lesson.schedule_entry_id}?date=${lesson.lesson_date}`} style={{padding:"7px 9px",border:"1px solid #d7ddd7",borderRadius:8,background:lesson.status==="active"?"#e8f0ea":"#faf9f6",color:"#486b59",fontSize:12,fontWeight:850,textDecoration:"none"}}>{formatLessonDate(lesson.lesson_date)} · {lessonStatuses[lesson.status]} →</Link>)}</div></div>}<UnitMaterials unitId={unit.id} roomId={roomId} canEdit={canEdit}/><div style={{borderTop:"1px solid #e4e0d7",paddingTop:10,marginTop:10}}><strong>{linked.length?`${linked.length} opgave${linked.length===1?"":"r"} koblet`:"Ingen opgaver koblet"}</strong>{canEdit&&available.length>0&&<select defaultValue="" onChange={e=>{const id=Number(e.target.value);if(id)attach(id);e.currentTarget.value=""}} style={{...input,width:"auto",marginLeft:10,display:"inline-block"}}><option value="">+ Kobl opgave…</option>{available.map(a=><option key={a.id} value={a.id}>{a.title}</option>)}</select>}{linked.map(a=><div key={a.id} style={{marginTop:6,padding:7,background:"#faf9f6",borderRadius:7}}><strong>{a.title}</strong> <small>· {a.type}</small>{canEdit&&<button onClick={()=>detach(a.id)} style={{...secondary,float:"right",padding:"3px 6px",fontSize:10}}>Fjern</button>}</div>)}</div></article>}
function Tag({children}:{children:ReactNode}){return <span style={{fontSize:10,fontWeight:900,padding:"4px 7px",borderRadius:999,background:"#e7ece7"}}>{children}</span>}
function period(u:Unit){if(!u.start_date&&!u.end_date)return"Ingen fast periode";const f=(v:string)=>new Date(`${v}T12:00:00`).toLocaleDateString("da-DK",{day:"numeric",month:"short"});return`${u.start_date?f(u.start_date):"?"} → ${u.end_date?f(u.end_date):"?"}`}
function formatLessonDate(v:string){return new Date(`${v}T12:00:00`).toLocaleDateString("da-DK",{weekday:"short",day:"numeric",month:"short"})}
const card:React.CSSProperties={background:"white",border:"1px solid #ddd9d0",borderRadius:14,padding:18},grid:React.CSSProperties={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(210px,1fr))",gap:8},input:React.CSSProperties={boxSizing:"border-box",display:"block",width:"100%",marginTop:5,padding:"8px 9px",border:"1px solid #d5d1c7",borderRadius:8,background:"white",font:"inherit"},primary:React.CSSProperties={padding:"9px 12px",border:0,borderRadius:8,background:"#365044",color:"white",fontWeight:900,cursor:"pointer"},secondary:React.CSSProperties={padding:"7px 9px",border:"1px solid #d5d1c7",borderRadius:8,background:"white",fontWeight:850,cursor:"pointer"},danger:React.CSSProperties={...secondary,border:"1px solid #dfb8b2",background:"#fff3ef",color:"#8a3c34"},eyebrow:React.CSSProperties={fontSize:10,fontWeight:900,letterSpacing:1.1,color:"#718077"},check:React.CSSProperties={display:"flex",gap:6,fontWeight:800,fontSize:13};
