"use client";

import { useEffect, useState } from "react";
import { usePathname } from "next/navigation";
import { supabase } from "../lib/supabase";

export default function Enhancements(){
 const pathname=usePathname();const[saved,setSaved]=useState(false);
 useEffect(()=>{if(pathname!=="/")return;let feedbackLoading=false,grammarLoading=false;
  const captureStudentCode=()=>{const input=document.querySelector('input[placeholder="Skriv din kode"]') as HTMLInputElement|null;const form=input?.closest("form");if(form&&!form.getAttribute("data-code-capture")){form.setAttribute("data-code-capture","1");form.addEventListener("submit",()=>{const code=input?.value.trim().toUpperCase();if(code)sessionStorage.setItem("klassevaerelset-student-code",code)})}};
  const addFeedback=async(writing:Element)=>{if(feedbackLoading||document.getElementById("student-teacher-feedback"))return;const code=sessionStorage.getItem("klassevaerelset-student-code");if(!code)return;feedbackLoading=true;const{data,error}=await supabase.rpc("student_feedback",{p_access_code:code});feedbackLoading=false;if(error)return;const items=Array.isArray(data?.feedback)?data.feedback:[];const item=items.length===1?items[0]:null;if(!item?.text?.trim())return;const card=document.createElement("div");card.id="student-teacher-feedback";card.style.cssText="margin-top:22px;padding:20px 22px;border:1px solid #d8c79e;border-radius:13px;background:#fffaf0;color:#27352d";card.innerHTML='<div style="font-size:10px;font-weight:800;letter-spacing:1.6px;color:#8a7045;margin-bottom:8px">FEEDBACK FRA DIN LÆRER</div><strong style="display:block;font-family:Georgia,serif;font-size:20px;margin-bottom:8px">Din lærers kommentar</strong>';const p=document.createElement("p");p.textContent=item.text;p.style.cssText="white-space:pre-wrap;line-height:1.6;margin:0;color:#4f554f";card.appendChild(p);writing.appendChild(card)};
  const addGrammar=async()=>{if(grammarLoading||document.getElementById("student-grammar-assignments"))return;const content=document.querySelector("main.studentShell .studentContent") as HTMLElement|null;if(!content||content.querySelector(".writing"))return;const heading=content.querySelector("h1");if(!heading||heading.textContent?.trim()!=="Dine opgaver")return;const code=sessionStorage.getItem("klassevaerelset-student-code");if(!code)return;grammarLoading=true;const{data,error}=await supabase.rpc("student_grammar_assignments",{p_access_code:code});grammarLoading=false;if(error||!data?.ok)return;const items=Array.isArray(data.assignments)?data.assignments:[];if(!items.length)return;const box=document.createElement("section");box.id="student-grammar-assignments";box.style.cssText="margin-top:32px;padding-top:26px;border-top:1px solid #dedbd3";box.innerHTML='<div style="font-size:11px;font-weight:800;letter-spacing:1.6px;color:#718077;margin-bottom:7px">GRAMMATIK</div><h2 style="font-family:Georgia,serif;font-size:28px;margin:0 0 8px;color:#27352d">Din grammatik</h2><p style="color:#707670;margin:0 0 16px">Her ligger de grammatikopgaver, din lærer har tildelt klassen.</p>';const list=document.createElement("div");list.style.cssText="display:grid;gap:10px";items.forEach((item:any)=>{const a=document.createElement("a");a.href=`/student-grammar?assignment=${item.id}`;a.style.cssText="display:flex;align-items:center;justify-content:space-between;gap:14px;padding:16px 18px;border:1px solid #ddd9d0;border-radius:11px;background:#fff;text-decoration:none;color:#27352d";const left=document.createElement("div");const title=document.createElement("strong");title.textContent=item.title;title.style.cssText="display:block;font-size:16px";const meta=document.createElement("small");meta.textContent=`${item.area} · ${item.completed?'Færdig':'Ikke startet'}`;meta.style.cssText="display:block;color:#777;margin-top:4px";left.append(title,meta);const arrow=document.createElement("b");arrow.textContent=item.completed&&item.max_score?`${item.score}/${item.max_score}`:"Åbn →";arrow.style.cssText="white-space:nowrap;color:#526b60";a.append(left,arrow);list.appendChild(a)});box.appendChild(list);content.appendChild(box)};
  const enhance=()=>{captureStudentCode();addGrammar();const writing=document.querySelector(".writing section");if(writing&&!document.getElementById("manual-save-wrap")){const old=writing.querySelector(".saved");const wrap=document.createElement("div");wrap.id="manual-save-wrap";wrap.style.cssText="display:flex;align-items:center;gap:12px;justify-content:space-between;margin-top:18px;flex-wrap:wrap";const progress=document.createElement("span");progress.style.cssText="font-size:14px;color:#657068;font-weight:700";const actions=document.createElement("div");actions.style.cssText="display:flex;align-items:center;gap:12px;margin-left:auto";const status=document.createElement("span");status.textContent="Alt er gemt ✓";status.style.cssText="font-size:14px;color:#55705d;font-weight:700";const button=document.createElement("button");button.type="button";button.textContent="Gem opgave";button.style.cssText="border:0;border-radius:9px;background:#435c4a;color:white;padding:11px 18px;font-weight:800;cursor:pointer;font-size:14px";const update=()=>{const fields=Array.from(writing.querySelectorAll("textarea")) as HTMLTextAreaElement[];progress.textContent=`${fields.filter(f=>f.value.trim()).length} af ${fields.length} felter udfyldt`};button.onclick=()=>{if(document.activeElement instanceof HTMLElement)document.activeElement.blur();status.textContent="Gemt ✓";button.textContent="Gemt ✓";setSaved(true);setTimeout(()=>{button.textContent="Gem opgave";status.textContent="Alt er gemt ✓";setSaved(false)},1800)};writing.addEventListener("input",()=>{status.textContent="Gemmer…";update();setTimeout(()=>{if(status.textContent==="Gemmer…")status.textContent="Alt er gemt ✓"},700)});old?.remove();actions.append(status,button);wrap.append(progress,actions);writing.appendChild(wrap);update()}if(writing)addFeedback(writing);
   const content=document.querySelector("main.shell section.content") as HTMLElement|null;const header=content?.querySelector("header");if(content&&header&&!document.getElementById("teacher-dashboard-nav")){document.getElementById("teacher-overview-link")?.remove();const nav=document.createElement("nav");nav.id="teacher-dashboard-nav";nav.style.cssText="display:flex;gap:10px;flex-wrap:wrap;margin:18px 0 28px";const links=[["Elever","/students"],["+ Opret opgave","/create-assignment"],["Opgaver & besvarelser","/teacher-overview"],["Grammatik","/grammar"],["Lærerværelset","/teacher-room"]];links.forEach(([label,href],i)=>{const a=document.createElement("a");a.href=href;a.textContent=label;a.style.cssText=`display:inline-flex;align-items:center;padding:11px 15px;border-radius:9px;text-decoration:none;font-weight:800;font-size:14px;border:1px solid ${i===4?'#365044':'#d8d5cd'};background:${i===4?'#365044':'#fff'};color:${i===4?'#fff':'#27352d'}`;nav.appendChild(a)});header.insertAdjacentElement("afterend",nav)}
   if(content){const grid=content.querySelector(":scope > .grid");grid?.remove()}
  };enhance();const observer=new MutationObserver(enhance);observer.observe(document.body,{childList:true,subtree:true});return()=>observer.disconnect()},[pathname,saved]);return null;
}
