"use client";
import {useEffect,useState} from "react";
import {supabase} from "../lib/supabase";

type Audience="teacher"|"parent"|"board"|"admin"|"student";
type Note={id:string;text:string;author_email:string;author_id:string;created_at:string;audiences:Audience[]|null};
type FileRow={id:string;noticeboard_post_id:string;display_name:string;object_path:string;size_bytes:number|null};
const colors=["#fff2a8","#f8d7c4","#dcefcf","#dce8f7","#f1d9ee"];
const fileSize=(size:number|null)=>size===null?"":size<1024*1024?`${Math.max(1,Math.round(size/1024))} KB`:`${(size/(1024*1024)).toFixed(1)} MB`;

export default function RoleNoticeboard({audience,title="Opslagstavlen"}:{audience:Audience;title?:string}){
 const[notes,setNotes]=useState<Note[]>([]),[files,setFiles]=useState<Record<string,FileRow[]>>({}),[userId,setUserId]=useState(""),[message,setMessage]=useState("");
 const load=async()=>{
  const{data}=await supabase.from("noticeboard_posts").select("id,text,author_email,author_id,created_at,audiences").contains("audiences",[audience]).order("created_at",{ascending:false});const rows=(data||[]) as Note[];setNotes(rows);
  if(!rows.length){setFiles({});return}
  const{data:fileData}=await supabase.from("school_files").select("id,noticeboard_post_id,display_name,object_path,size_bytes").eq("area","noticeboard").in("noticeboard_post_id",rows.map(n=>n.id)).order("created_at");const grouped:Record<string,FileRow[]>={};for(const file of (fileData||[]) as FileRow[])(grouped[file.noticeboard_post_id]||=[]).push(file);setFiles(grouped);
 };
 useEffect(()=>{supabase.auth.getSession().then(({data})=>setUserId(data.session?.user.id||""));load()},[audience]);
 const openFile=async(file:FileRow)=>{setMessage("");const{data,error}=await supabase.storage.from("school-files").createSignedUrl(file.object_path,120);if(error||!data?.signedUrl){setMessage("Dokumentet kunne ikke åbnes lige nu.");return}window.open(data.signedUrl,"_blank","noopener,noreferrer")};
 const remove=async(id:string)=>{if(!confirm("Fjern opslaget og dets dokumenter?"))return;setMessage("");const paths=(files[id]||[]).map(f=>f.object_path);if(paths.length){const{error}=await supabase.storage.from("school-files").remove(paths);if(error){setMessage("Dokumenterne kunne ikke slettes sikkert, så opslaget er bevaret.");return}}await supabase.from("noticeboard_posts").delete().eq("id",id).eq("author_id",userId);await load()};
 return <section style={{marginTop:30}}><h2 style={{fontFamily:"Georgia,serif",fontSize:30,margin:"0 0 14px"}}>{title}</h2>{message&&<div style={{marginBottom:10,padding:10,background:"#fff3cd",borderRadius:8,color:"#715827"}}>{message}</div>}<div style={{background:"#b98552",backgroundImage:"radial-gradient(rgba(84,50,25,.15) 1px, transparent 1px)",backgroundSize:"7px 7px",border:"10px solid #8b5e34",borderRadius:12,padding:24,minHeight:230}}>{notes.length===0?<div style={{padding:16,background:"#fff2a8",width:190,minHeight:190,boxSizing:"border-box"}}>Der er ingen opslag til dig lige nu.</div>:<div style={{display:"flex",flexWrap:"wrap",gap:22,alignItems:"flex-start"}}>{notes.map((n,i)=>{const noteFiles=files[n.id]||[];return <article key={n.id} style={{background:colors[i%colors.length],padding:"18px 16px 14px",width:215,minHeight:190,boxSizing:"border-box",position:"relative",boxShadow:"2px 5px 10px rgba(50,35,20,.24)",transform:`rotate(${[-1.4,.8,-.5,1.2][i%4]}deg)`,display:"flex",flexDirection:"column"}}>{n.author_id===userId&&<button aria-label="Fjern opslag" onClick={()=>remove(n.id)} style={{position:"absolute",right:7,top:5,border:0,background:"transparent",fontSize:17,cursor:"pointer"}}>×</button>}<p style={{margin:"0 18px 10px 0",fontSize:15,lineHeight:1.4,whiteSpace:"pre-wrap",flex:noteFiles.length?"0 0 auto":1}}>{n.text}</p>{noteFiles.length>0&&<div style={{display:"grid",gap:5,margin:"2px 0 12px"}}>{noteFiles.map(file=><button key={file.id} onClick={()=>openFile(file)} style={{border:"1px solid rgba(55,70,60,.2)",background:"rgba(255,255,255,.5)",borderRadius:7,padding:"7px 8px",textAlign:"left",cursor:"pointer",color:"#31473d"}}><strong style={{display:"block",fontSize:11,overflow:"hidden",textOverflow:"ellipsis"}}>📎 {file.display_name}</strong>{file.size_bytes!==null&&<small>{fileSize(file.size_bytes)}</small>}</button>)}</div>}<small style={{borderTop:"1px solid rgba(50,50,40,.16)",paddingTop:7,color:"#62645d",fontSize:11,marginTop:"auto"}}>{n.author_email?.split("@")[0]} · {new Date(n.created_at).toLocaleString("da-DK")}</small></article>})}</div>}</div></section>
}
