export type DanishCommunicationTemplate={
 id:string;
 name:string;
 minGrade:number;
 description:string;
 planning:string[];
 checklist:string[];
};

export type DanishCommunicationSupport={
 band:string;
 coach:string;
 planning:string[];
 checklist:string[];
 focus:string[];
};

export const danishCommunicationTemplates:DanishCommunicationTemplate[]=[
 {id:"mundtlig-fortaelling",name:"Mundtlig fortælling",minGrade:2,description:"Fortæl en oplevelse eller historie, så andre kan følge med og danne billeder undervejs.",planning:["Hvad vil du fortælle, og hvad er det vigtigste?","Hvordan begynder du, så lytteren kommer med?","Hvilke 2–4 vigtige øjeblikke skal med?","Hvordan slutter du, så fortællingen får en tydelig virkning?"],checklist:["Jeg har en tydelig begyndelse, midte og slutning","Jeg bruger konkrete detaljer frem for at fortælle alt","Jeg taler tydeligt og i et tempo, andre kan følge"]},
 {id:"faglig-forklaring",name:"Faglig forklaring",minGrade:3,description:"Forklar et emne, en proces eller et begreb, så modtageren faktisk forstår det.",planning:["Hvad skal modtageren forstå, når du er færdig?","Hvilke faglige begreber er nødvendige?","Hvilket eksempel, billede eller sammenligning kan gøre forklaringen tydelig?","I hvilken rækkefølge giver forklaringen mest mening?"],checklist:["Jeg forklarer fagord, som modtageren ikke nødvendigvis kender","Jeg bruger mindst ét konkret eksempel","Min rækkefølge hjælper modtageren med at forstå"]},
 {id:"praesentation",name:"Præsentation / fremlæggelse",minGrade:4,description:"Planlæg en mundtlig præsentation med tydelig struktur, relevante eksempler og bevidst kontakt til publikum.",planning:["Hvad er præsentationens hovedpointe og mål?","Hvordan åbner du og viser publikum, hvor I skal hen?","Hvilke hovedpunkter, eksempler eller belæg skal med?","Hvilke billeder, stikord eller andre hjælpemidler støtter forståelsen?","Hvordan samler og afslutter du præsentationen?"],checklist:["Jeg har en tydelig rød tråd","Mine slides eller stikord støtter mig i stedet for at være et manuskript","Jeg ser op og taler til publikum","Jeg prioriterer de vigtigste pointer frem for at tage alt med"]},
 {id:"samtale-dialog",name:"Samtale & dialog",minGrade:2,description:"Deltag i en faglig samtale ved både at lytte, spørge, reagere og bygge videre på andres bidrag.",planning:["Hvad er samtalens spørgsmål eller emne?","Hvilke egne tanker eller eksempler kan du bidrage med?","Hvilke spørgsmål kan hjælpe andre med at uddybe?","Hvordan kan du vise, at du har lyttet, før du svarer?"],checklist:["Jeg lytter færdigt før jeg svarer","Jeg bygger videre på eller forholder mig til det, andre siger","Jeg stiller spørgsmål, der åbner samtalen","Jeg giver plads til andre"]},
 {id:"respons",name:"Mundtlig respons & feedback",minGrade:3,description:"Giv konkret, respektfuld og brugbar respons, som hjælper en anden med næste skridt.",planning:["Hvad fungerer allerede godt, og hvor kan du være konkret?","Hvad er det vigtigste næste skridt for modtageren?","Hvilket eksempel kan vise, hvad du mener?","Hvordan formulerer du responsen, så den kan bruges?"],checklist:["Jeg er konkret frem for bare at sige godt/dårligt","Jeg peger på noget, modtageren kan gøre videre med","Jeg begrunder min respons med et eksempel","Min tone passer til situationen"]},
 {id:"debat",name:"Debat & mundtlig argumentation",minGrade:6,description:"Fremsæt et synspunkt, underbyg det og forhold dig sagligt til modargumenter.",planning:["Hvad er dit præcise standpunkt?","Hvilke 2–3 argumenter og belæg er stærkest?","Hvilket relevant modargument forventer du?","Hvordan vil du svare på modargumentet uden at fordreje det?","Hvad vil du have tilhørerne til at tænke eller gøre?"],checklist:["Mine argumenter har belæg","Jeg skelner mellem påstand, eksempel og begrundelse","Jeg gengiver modargumenter rimeligt","Jeg reagerer på det, der faktisk bliver sagt"]},
 {id:"oplaesning-performance",name:"Oplæsning & performance",minGrade:3,description:"Brug stemme, pauser, betoning og tempo til at formidle en tekst eller et budskab.",planning:["Hvad skal publikum især lægge mærke til?","Hvor skal tempoet ændres?","Hvilke ord eller sætninger skal have særlig betoning?","Hvor giver pauser mening?","Hvordan bruger du krop og blik uden at overdrive?"],checklist:["Min stemme kan høres og forstås","Jeg varierer tempo og betoning med en grund","Mine pauser hjælper betydningen","Jeg har øvet teksten højt mere end én gang"]},
 {id:"podcast",name:"Podcast / lydformidling",minGrade:5,description:"Planlæg lydformidling, hvor stemme, struktur, interview, klip og eventuel lyd understøtter indholdet.",planning:["Hvem er lytteren, og hvad skal episoden give dem?","Hvad er den røde tråd fra åbning til afslutning?","Hvilke stemmer, eksempler eller interviewbidrag skal med?","Hvor kan lyd, pause eller klipning støtte indholdet?","Hvad skal redigeres væk for at holde fokus?"],checklist:["Man forstår formålet tidligt","Lydvalg og klipning har en funktion","Samtale eller interview lyder som kommunikation – ikke oplæsning af spørgsmål","Episoden er strammere efter redigering end før"]},
 {id:"video-multimodal",name:"Video & multimodal præsentation",minGrade:5,description:"Kombinér tale, billede, tekst, lyd og klip, så udtryksformerne arbejder sammen om budskabet.",planning:["Hvad er budskabet og målgruppen?","Hvad bør siges, og hvad bør vises?","Hvilke billeder, tekstbidder eller klip har en tydelig funktion?","Hvordan skaber du en klar rækkefølge og overgang mellem dele?","Hvad skal publikum sidde tilbage med?"],checklist:["Billede og lyd gentager ikke bare hinanden unødigt","Jeg vælger udtryksform efter funktion","Tekst på skærmen kan læses og er kort","Klip og overgange hjælper den røde tråd"]},
 {id:"mundtlig-proeve",name:"Mundtlig prøveforberedelse",minGrade:8,description:"Træn en selvstændig faglig fremlæggelse og den efterfølgende samtale med fokus på tekst, belæg og perspektiv.",planning:["Hvad er dit fokus eller din problemstilling?","Hvilke tekststeder, eksempler eller faglige begreber er vigtigst?","Hvordan bevæger du dig fra iagttagelse til analyse og fortolkning?","Hvilken perspektivering er fagligt relevant – og hvorfor?","Hvilke spørgsmål kan du få, og hvordan kan du tænke højt fagligt i samtalen?"],checklist:["Min præsentation har et tydeligt fagligt fokus","Jeg bruger konkrete belæg frem for løse påstande","Jeg kan forklare mine faglige valg","Jeg kan indgå fleksibelt i samtalen uden at falde tilbage i et manuskript"]}
];

export function danishCommunicationByName(value:string|undefined|null){return danishCommunicationTemplates.find(x=>x.name===value||x.id===value)||null}

function simplify(text:string){return text.replace(/^Hvordan /,"Hvordan ").replace(/^Hvilke /,"Hvilke ").replace(/modtageren/g,"den, der lytter").replace(/publikum/g,"dem, der lytter").replace(/hovedpointe/g,"vigtigste pointe")}

export function danishCommunicationSupport(template:DanishCommunicationTemplate,grade:number|null|undefined):DanishCommunicationSupport{
 if(grade==null)return{band:"Åben progression",coach:"Planlæg det vigtigste først. Brug stikord frem for et fuldt manuskript, og tænk hele tiden på den, der skal lytte eller deltage.",planning:template.planning,checklist:template.checklist,focus:["formål","modtager","rød tråd","lytning og nærvær"]};
 if(grade<=4)return{band:"1.–4. klasse",coach:"Find ud af, hvad du især vil fortælle. Lav få stikord, øv dig højt, og hjælp dem, der lytter, med at følge med.",planning:template.planning.slice(0,Math.min(3,template.planning.length)).map(simplify),checklist:["Jeg ved, hvad det vigtigste er","Jeg bruger stikord i stedet for at læse alt op","Jeg taler tydeligt og lytter, når andre taler"],focus:["tydelighed","rækkefølge","stikord","lytning"]};
 if(grade<=6)return{band:"5.–6. klasse",coach:"Planlæg en tydelig rød tråd og vælg eksempler, der hjælper modtageren. Øv formidlingen højt og justér efter det, der virker.",planning:template.planning.slice(0,Math.min(4,template.planning.length)),checklist:[...template.checklist,"Jeg bruger stikord og kan formulere mig frit omkring dem"],focus:["rød tråd","eksempler","modtager","mundtligt sprog"]};
 return{band:grade<=9?"7.–9. klasse":"10. klasse",coach:"Behandl mundtlig kommunikation som et bevidst valg af indhold, struktur, stemme og respons på situationen. Prioritér, øv, lyt og tilpas undervejs.",planning:template.planning,checklist:[...template.checklist,"Jeg kan begrunde mine formidlingsvalg i forhold til formål og modtager","Jeg tilpasser mig publikum eller samtalen i stedet for kun at gennemføre en plan"],focus:["kommunikationssituation","prioritering","belæg","retoriske valg","respons og tilpasning"]};
}
