export type DanishGenreCategory="Fiktion"|"Refleksion"|"Opinion"|"Information"|"Andre formater";

export type DanishGenre={
 id:string;
 name:string;
 category:DanishGenreCategory;
 purpose:string;
 audience:string;
 structure:string[];
 features:string[];
 checklist:string[];
};

export const danishGenres:DanishGenre[]=[
 {id:"novelle",name:"Novelle",category:"Fiktion",purpose:"Fortæl en koncentreret fiktiv historie med en tydelig konflikt eller forandring.",audience:"En læser, der skal opleve og fortolke historien.",structure:["Anslag","Præsentér person, situation og miljø","Lad konflikten udvikle sig","Skab et eller flere vendepunkter","Afslut med en virkning eller pointe"],features:["Få personer","Afgrænset tid og sted","Konflikt","Fortæller og synsvinkel","Sanseligt og præcist sprog"],checklist:["Har historien en konflikt?","Er der noget, der ændrer sig?","Har du valgt en tydelig synsvinkel?","Er slutningen bevidst?"]},
 {id:"eventyr",name:"Eventyr",category:"Fiktion",purpose:"Fortæl en enkel, symbolsk historie hvor en hovedperson møder prøvelser og forandres.",audience:"En læser, der forventer en tydelig fortælling og eventyrlige mønstre.",structure:["Præsentér udgangspunktet","Send hovedpersonen ud på en opgave eller rejse","Lad hovedpersonen møde prøver og hjælpere","Skab klimaks","Afslut med konsekvens eller ny orden"],features:["Modsætninger","Gentagelser","Prøver","Hjælpere og modstandere","Eventyrlige eller magiske elementer"],checklist:["Er målet tydeligt?","Er der prøvelser?","Bruger du gentagelser eller symbolik?","Har slutningen en konsekvens?"]},
 {id:"kortprosa",name:"Kortprosa",category:"Fiktion",purpose:"Skab en meget kort litterær tekst, hvor få detaljer åbner for meget fortolkning.",audience:"En læser, der skal læse mellem linjerne.",structure:["Gå hurtigt ind i en situation","Vælg få betydningsfulde detaljer","Skab et brud, en spænding eller en undren","Stop mens teksten stadig arbejder videre hos læseren"],features:["Knaphed","Undertekst","Åbne huller","Fortættet sprog","Ofte åben slutning"],checklist:["Kan noget skæres væk?","Har detaljerne betydning?","Er der plads til fortolkning?"]},
 {id:"lyrik",name:"Lyrik / digt",category:"Fiktion",purpose:"Udtryk en stemning, tanke eller erfaring gennem koncentreret og sanseligt sprog.",audience:"En læser, der skal mærke, forestille sig og fortolke.",structure:["Vælg et centralt billede eller tema","Byg strofer eller en fri form","Udvikl billeder, lyd og rytme","Slut med et billede, brud eller perspektiv"],features:["Billedsprog","Rytme","Gentagelse","Lyd","Linjeskift og grafisk form"],checklist:["Har ordene flere lag?","Understøtter formen indholdet?","Er billederne konkrete?","Har du læst teksten højt?"]},
 {id:"manuskript",name:"Manuskript / skuespil",category:"Fiktion",purpose:"Skriv en historie, der skal kunne fremføres eller filmes.",audience:"Skuespillere, instruktør og et publikum.",structure:["Scene og situation","Replikker og handling","Konflikt udvikles gennem scener","Vendepunkt","Afsluttende scene"],features:["Replikker","Sceneanvisninger","Handling frem for forklaring","Tydelige personer","Visuelle situationer"],checklist:["Kan man se og høre det, du skriver?","Har hver scene en funktion?","Lyder replikkerne naturlige?"]},
 {id:"tegneserie",name:"Tegneserie / graphic novel",category:"Fiktion",purpose:"Fortæl gennem samspillet mellem billeder, tekst og sekvenser.",audience:"En læser, der afkoder både billeder og ord.",structure:["Planlæg scenen i felter","Skab progression fra felt til felt","Brug replikker, billedbeskæring og handling","Afslut sekvensen med pointe eller bevægelse videre"],features:["Paneler","Talebobler","Billedvinkler","Visuelle symboler","Samspil mellem tekst og billede"],checklist:["Fortæller billederne noget selv?","Er rækkefølgen tydelig?","Er teksten kort nok til formatet?"]},
 {id:"blog",name:"Blogindlæg",category:"Refleksion",purpose:"Del oplevelser, tanker eller viden i en personlig og direkte form.",audience:"Læsere med interesse for emnet og afsenderens perspektiv.",structure:["Fængende overskrift","Personlig indgang","Udfold emnet med oplevelse, refleksion eller viden","Tal direkte til læseren","Afrund med pointe, spørgsmål eller perspektiv"],features:["Personlig stemme","Direkte læserkontakt","Afsnit og mellemoverskrifter","Konkrete eksempler"],checklist:["Kan man høre din stemme?","Er emnet tydeligt?","Er teksten let at orientere sig i?"]},
 {id:"dagbog",name:"Dagbog",category:"Refleksion",purpose:"Fasthold en oplevelse og de tanker og følelser, den sætter i gang.",audience:"Typisk skriveren selv eller en tænkt privat læser.",structure:["Dato eller situation","Hvad skete der?","Hvordan oplevede du det?","Hvad tænker du om det nu?"],features:["Jeg-fortæller","Personlig tone","Følelser og tanker","Konkrete detaljer"],checklist:["Er perspektivet personligt?","Er der både begivenhed og refleksion?","Lyder det som et menneske og ikke en rapport?"]},
 {id:"erindring",name:"Erindring",category:"Refleksion",purpose:"Genskab en betydningsfuld oplevelse fra fortiden og forstå den fra nutiden.",audience:"En læser, der skal opleve både dengang og den senere refleksion.",structure:["Åbn med et minde eller sanseindtryk","Genskab situationen konkret","Udfold mennesker og detaljer","Skift mellem dengang og nu","Reflektér over betydningen"],features:["Erindrende jeg","Sanser","Tidsafstand","Refleksion","Udvalgte detaljer"],checklist:["Kan læseren se situationen?","Er forskellen mellem dengang og nu tydelig?","Forklarer du ikke mere end nødvendigt?"]},
 {id:"essay",name:"Essay",category:"Refleksion",purpose:"Undersøg et emne gennem nysgerrighed, erfaringer og tanker frem for at bevise én konklusion.",audience:"En læser, der inviteres med ind i dine overvejelser.",structure:["Åbn konkret eller overraskende","Tag udgangspunkt i en oplevelse, iagttagelse eller tanke","Undersøg emnet fra flere vinkler","Forbind det personlige med noget større","Slut åbent eller eftertænksomt"],features:["Skrivetænkning","Konkrete erfaringer","Refleksion","Perspektivskift","Personlig men undersøgende stemme"],checklist:["Undersøger du mere end du konkluderer?","Er der konkrete billeder eller erfaringer?","Kommer emnet rundt om flere perspektiver?"]},
 {id:"formelt-brev",name:"Formelt brev / mail",category:"Refleksion",purpose:"Henvend dig sagligt og præcist til en person eller institution om et bestemt formål.",audience:"En bestemt modtager i en officiel eller professionel relation.",structure:["Emne eller overskrift","Høflig indledning","Forklar dit ærinde","Giv nødvendige oplysninger eller argumenter","Skriv hvad du ønsker skal ske","Høflig afslutning og afsender"],features:["Klar modtager","Saglig tone","Præcise oplysninger","Høflighed"],checklist:["Ved modtageren straks, hvorfor du skriver?","Er tonen passende?","Er dit ønske tydeligt?"]},
 {id:"personligt-brev",name:"Personligt brev",category:"Refleksion",purpose:"Skriv direkte og personligt til en bestemt person.",audience:"En kendt eller tydeligt forestillet modtager.",structure:["Hilsen","Anledning til at skrive","Fortæl, spørg eller reflekter","Skab direkte kontakt til modtageren","Afslutning og hilsen"],features:["Du-tiltale","Personlig stemme","Relation til modtageren","Spørgsmål og reaktioner"],checklist:["Kan man mærke relationen?","Er det tydeligt, hvorfor brevet skrives?"]},
 {id:"personlig-beretning",name:"Personlig beretning",category:"Refleksion",purpose:"Fortæl om en virkelig oplevelse set fra dit eget perspektiv.",audience:"En læser, der skal forstå hvad der skete og hvordan det blev oplevet.",structure:["Sæt scenen","Fortæl forløbet i en tydelig rækkefølge","Zoom ind på vigtige øjeblikke","Beskriv tanker og reaktioner","Afrund med betydning eller eftertanke"],features:["Jeg-perspektiv","Virkelige hændelser","Kronologi","Sansning","Efterrefleksion"],checklist:["Er hændelsesforløbet forståeligt?","Har du valgt de vigtigste øjeblikke?","Er oplevelsen mere end bare en liste over hændelser?"]},
 {id:"anmeldelse",name:"Anmeldelse",category:"Opinion",purpose:"Vurdér et værk, produkt eller en oplevelse og begrund vurderingen.",audience:"En læser, der overvejer eller vil forstå værket/oplevelsen.",structure:["Præsentér det, du anmelder","Giv nødvendig kontekst","Fremhæv centrale kvaliteter og problemer","Dokumentér vurderinger med eksempler","Saml vurderingen og evt. anbefaling"],features:["Vurdering","Begrundelser","Konkrete eksempler","Faglige kriterier","Tydelig afsender"],checklist:["Begrunder du dine vurderinger?","Skelner du mellem referat og vurdering?","Får læseren et klart indtryk?"]},
 {id:"debatindlaeg",name:"Debatindlæg",category:"Opinion",purpose:"Sæt et aktuelt problem til debat og overbevis læseren om et synspunkt eller en handling.",audience:"Offentligheden eller en bestemt gruppe, der kan påvirkes af argumenterne.",structure:["Skarp rubrik eller åbning","Præsentér problemet","Gør dit standpunkt tydeligt","Argumentér med eksempler og belæg","Forhold dig til modargumenter","Foreslå løsning eller handling","Afrund markant"],features:["Tydelig holdning","Argumentation","Eksempler","Modargument","Appel til læseren"],checklist:["Ved læseren, hvad du mener?","Har argumenterne belæg?","Har du taget et modargument alvorligt?","Er løsningen tydelig?"]},
 {id:"klumme",name:"Klumme",category:"Opinion",purpose:"Kommentér et emne med en tydelig personlig stemme, skarp iagttagelse og ofte humor eller kant.",audience:"Læsere, der både vil underholdes og udfordres.",structure:["Start i en konkret observation","Udfold din personlige vinkel","Lav forbindelser og skarpe pointer","Overrask eller vend perspektivet","Slut med en tydelig efterklang"],features:["Personlig stemme","Holdning","Sproglig stil","Iagttagelser","Ironi eller humor kan bruges"],checklist:["Har teksten en tydelig stemme?","Er pointen mere end bare en mening?","Er sproget levende?"]},
 {id:"kommentar",name:"Kommentar",category:"Opinion",purpose:"Forklar og vurder betydningen af en aktuel sag fra et tydeligt perspektiv.",audience:"Læsere, der allerede kender sagen eller hurtigt skal sættes ind i den.",structure:["Præsentér sagen kort","Gør din hovedvurdering tydelig","Analyser hvorfor sagen betyder noget","Underbyg med eksempler eller viden","Afrund med konsekvens eller perspektiv"],features:["Aktualitet","Tydelig vurdering","Analyse","Argumentation"],checklist:["Er sagen forklaret kort nok?","Er din vurdering begrundet?","Går du fra hændelse til betydning?"]},
 {id:"kronik",name:"Kronik",category:"Opinion",purpose:"Udfold og diskutér et samfundsrelevant emne grundigt og nuanceret.",audience:"En bred offentlighed med interesse for emnet.",structure:["Fængende indledning og problemstilling","Baggrund og kontekst","Udfold flere perspektiver","Argumentér og nuancér","Brug viden, eksempler og evt. kilder","Saml perspektivet i en stærk afslutning"],features:["Længere argumenterende tekst","Nuancer","Faglig eller erfaringsbaseret viden","Tydelig afsender"],checklist:["Er problemstillingen tydelig?","Er flere perspektiver med?","Er påstande underbygget?","Har teksten en samlet bevægelse?"]},
 {id:"laeserbrev",name:"Læserbrev",category:"Opinion",purpose:"Reagér kort og direkte på en sag og forsøg at påvirke andre læsere.",audience:"Læsere af et medie samt evt. en konkret beslutningstager.",structure:["Rubrik","Anledning","Dit synspunkt","Et eller to stærke argumenter","Konkret ønske eller afslutning"],features:["Kort form","Tydelig holdning","Aktuelt emne","Direkte tone"],checklist:["Kommer pointen hurtigt?","Er teksten fokuseret på én sag?","Er slutningen tydelig?"]},
 {id:"baggrundsartikel",name:"Baggrundsartikel",category:"Information",purpose:"Giv læseren viden og sammenhæng bag en aktuel sag.",audience:"Læsere, der vil forstå mere end selve nyheden.",structure:["Rubrik og manchet","Præsentér spørgsmålet eller sagen","Forklar baggrund og årsager","Inddrag fakta, kilder og perspektiver","Vis konsekvenser eller mulige udviklinger","Afrund med overblik"],features:["Fakta","Kilder","Forklaring","Kontekst","Saglig tone"],checklist:["Besvarer teksten hvorfor og hvordan?","Er kilderne tydelige?","Skelner du mellem fakta og vurderinger?"]},
 {id:"feature",name:"Feature",category:"Information",purpose:"Gør et virkeligt emne levende gennem scener, mennesker, sanser og dokumenteret viden.",audience:"En læser, der både skal informeres og opleve historien.",structure:["Scenisk anslag","Præsentér menneske eller miljø","Veksle mellem scene, fakta og citater","Udfold emnets større sammenhæng","Vend tilbage til en scene eller pointe"],features:["Scener","Sanselige beskrivelser","Citater","Fakta","Journalistisk fortælling"],checklist:["Kan læseren mærke stedet?","Er fakta stadig dokumenterede?","Er der balance mellem scene og information?"]},
 {id:"interview",name:"Interview",category:"Information",purpose:"Få en person til at bidrage med viden, erfaringer eller synspunkter.",audience:"Læsere eller lyttere, der vil tættere på personen eller emnet.",structure:["Præsentér personen og anledningen","Start med åbne spørgsmål","Følg op på interessante svar","Skift mellem hovedemner","Afrund med et perspektiv eller fremadrettet spørgsmål"],features:["Spørgsmål","Svar eller citater","Opfølgning","Tydelig kontekst"],checklist:["Er spørgsmålene åbne?","Følger du faktisk op?","Er citaterne loyale mod det sagte?"]},
 {id:"kampagnetekst",name:"Kampagnetekst",category:"Information",purpose:"Få en bestemt målgruppe til at vide, føle eller gøre noget bestemt.",audience:"En nøje udvalgt målgruppe.",structure:["Fang opmærksomheden","Gør problemet eller behovet tydeligt","Giv et enkelt hovedbudskab","Underbyg med argument, fakta eller følelse","Slut med en klar opfordring til handling"],features:["Målgruppe","Budskab","Slogan eller nøglesætning","Call to action","Samspil med grafik"],checklist:["Er målgruppen tydelig?","Kan budskabet huskes?","Ved modtageren præcis, hvad de skal gøre?"]},
 {id:"nyhedsartikel",name:"Nyhedsartikel",category:"Information",purpose:"Informer hurtigt og præcist om en aktuel begivenhed.",audience:"Læsere, der skal forstå det vigtigste hurtigt.",structure:["Rubrik","Manchet","Det vigtigste først: hvem, hvad, hvor og hvornår","Uddyb hvordan og hvorfor","Citater og kilder","Baggrund efter behov"],features:["Aktualitet","Nyhedsvinkel","Kilder","Citater","Prioritering af vigtigste information"],checklist:["Står det vigtigste øverst?","Er kilderne tydelige?","Er fakta adskilt fra holdninger?"]},
 {id:"portraetartikel",name:"Portrætartikel",category:"Information",purpose:"Tegn et nuanceret billede af et menneske gennem fakta, scener, citater og iagttagelser.",audience:"Læsere, der vil forstå personen som mere end en række fakta.",structure:["Scenisk eller karakteristisk åbning","Præsentér personen","Veksle mellem baggrund, citater og observationer","Vis flere sider af personen","Afrund med et billede eller perspektiv"],features:["Personfokus","Citater","Observationer","Baggrund","Karakteristik"],checklist:["Viser du personen gennem konkrete detaljer?","Er portrættet nuanceret?","Er fakta korrekte?"]},
 {id:"pressemeddelelse",name:"Pressemeddelelse",category:"Information",purpose:"Giv medier en præcis og brugbar nyhed fra en organisation.",audience:"Journalister og medier.",structure:["Tydelig nyhedsrubrik","Kort manchet","Vigtigste oplysninger først","Et brugbart citat","Baggrund og fakta","Kontaktoplysninger"],features:["Nyhedsvinkel","Klar afsender","Citater","Kontaktinformation","Kort og faktatung form"],checklist:["Er der en reel nyhed?","Kan journalisten forstå sagen hurtigt?","Er kontaktpersonen tydelig?"]},
 {id:"reportage",name:"Reportage",category:"Information",purpose:"Tag læseren med til et virkeligt sted og en virkelig begivenhed.",audience:"En læser, der skal opleve situationen gennem journalistens tilstedeværelse.",structure:["Gå ind i en konkret scene","Beskriv miljø og mennesker","Veksle mellem observationer, handling og citater","Giv nødvendig baggrund","Afrund scenisk eller perspektiverende"],features:["Tilstedeværelse","Sanser","Scener","Citater","Virkelige hændelser"],checklist:["Kan læseren se og høre stedet?","Er det observerede adskilt fra dine antagelser?","Er der en tydelig bevægelse gennem teksten?"]},
 {id:"oejenvidneberetning",name:"Øjenvidneberetning",category:"Information",purpose:"Fortæl om en virkelig hændelse fra en persons direkte oplevelse.",audience:"Læsere, der skal forstå hændelsen tæt på.",structure:["Hvor var du og hvad skete først?","Fortæl hændelserne i en forståelig rækkefølge","Zoom ind på afgørende øjeblikke","Beskriv hvad du så, hørte og gjorde","Afrund med hvad der skete bagefter"],features:["Førstehåndsperspektiv","Kronologi","Sanseindtryk","Konkrete observationer"],checklist:["Holder du dig til det, du faktisk kunne opleve?","Er rækkefølgen klar?","Er detaljer relevante?"]},
 {id:"brochure",name:"Folder / brochure",category:"Information",purpose:"Formidl information hurtigt og overskueligt i en visuel flade.",audience:"En bestemt målgruppe, der typisk skimmer før den læser.",structure:["Forside med tydeligt budskab","Korte sektioner med overskrifter","Vigtig information og evt. fakta","Praktiske oplysninger","Kontakt eller næste skridt"],features:["Kort tekst","Mellemoverskrifter","Grafisk hierarki","Billeder eller ikoner","Praktiske oplysninger"],checklist:["Kan indholdet skimmes?","Er vigtigste budskab synligt med det samme?","Arbejder tekst og grafik sammen?"]},
 {id:"podcast",name:"Podcast / lydfortælling",category:"Andre formater",purpose:"Formidl en fortælling, samtale eller viden gennem lyd.",audience:"Lyttere, der ikke kan se det, du beskriver.",structure:["Kort intro og løfte til lytteren","Præsentér emne og stemmer","Byg segmenter eller scener","Brug speak, interview og lyd bevidst","Afrund med pointe eller perspektiv"],features:["Mundtligt sprog","Speak","Lydmiljø","Interview eller fortælling","Tydelig dramaturgi"],checklist:["Kan man forstå det uden billeder?","Er lyden med til at fortælle?","Er introen kort og klar?"]},
 {id:"reklame",name:"Reklame",category:"Andre formater",purpose:"Påvirk en målgruppe til at vælge, købe, mene eller huske noget.",audience:"En afgrænset målgruppe med bestemte behov eller værdier.",structure:["Fang opmærksomheden","Vis behov, problem eller drøm","Knyt produkt/budskab til en fordel","Skab troværdighed eller følelse","Slut med brand og handling"],features:["Målgruppe","Appelformer","Slogan","Visuelt budskab","Call to action"],checklist:["Hvem prøver du at påvirke?","Hvad lover reklamen?","Hvordan arbejder ord og billeder sammen?"]},
 {id:"tale",name:"Tale",category:"Andre formater",purpose:"Påvirk, samle, informere eller bevæge et publikum gennem mundtligt sprog.",audience:"Et konkret publikum i en konkret situation.",structure:["Skab kontakt fra starten","Gør anledning og hovedbudskab tydeligt","Udfold få stærke pointer","Brug eksempler, billeder eller gentagelser","Slut med en sætning, publikum kan huske"],features:["Mundtlighed","Publikumskontakt","Gentagelser","Retoriske virkemidler","Tydelig afslutning"],checklist:["Lyder teksten godt højt?","Er hovedbudskabet tydeligt?","Er der for mange pointer?","Har afslutningen kraft?"]}
];

export const danishGenreCategories:DanishGenreCategory[]=["Fiktion","Refleksion","Opinion","Information","Andre formater"];
export const danishGenreByName=(name:string)=>danishGenres.find(g=>g.name===name)||danishGenres.find(g=>g.id===name);
