export type DanishAnalysisTemplate={
 id:string;
 name:string;
 minGrade:number;
 description:string;
 prompts:string[];
 checklist:string[];
};

export type DanishAnalysisSupport={
 band:string;
 coach:string;
 prompts:string[];
 checklist:string[];
};

export const danishAnalysisTemplates:DanishAnalysisTemplate[]=[
 {id:"tekstspor",name:"Tekstnære spor",minGrade:3,description:"Find konkrete steder i teksten og brug dem som belæg for det, du siger.",prompts:["Find 2–3 steder i teksten, som du lægger mærke til","Beskriv helt konkret, hvad der står eller sker","Hvad får tekststedet dig til at tænke?","Hvilken idé om teksten kan dine spor støtte?"],checklist:["Jeg peger på konkrete steder i teksten","Jeg skelner mellem det teksten viser, og det jeg fortolker","Mine tekstspor passer til min forklaring"]},
 {id:"personer",name:"Personer & relationer",minGrade:3,description:"Undersøg hvad personer gør, siger, tænker og betyder for hinanden.",prompts:["Hvad får vi direkte at vide om personen/personerne?","Hvad viser handlinger, replikker eller tanker?","Hvordan er relationen mellem personerne?","Forandrer en person eller relation sig? Vis hvor."],checklist:["Jeg bruger handlinger eller citatnære tekstspor","Jeg forklarer egenskaber i stedet for kun at sætte etiketter på","Jeg viser udvikling eller relation, når teksten giver belæg for det"]},
 {id:"miljo",name:"Miljø & stemning",minGrade:4,description:"Undersøg sted, tid, sociale rammer og hvordan miljøet påvirker teksten.",prompts:["Hvor og hvornår foregår teksten?","Hvilke detaljer skaber miljø eller stemning?","Hvordan påvirker miljøet personerne eller handlingen?","Hvilken virkning har miljøet på dig som læser?"],checklist:["Jeg bruger konkrete detaljer fra teksten","Jeg forklarer både miljø og virkning","Jeg kobler miljø til handling, personer eller tema"]},
 {id:"fortaeller",name:"Fortæller & synsvinkel",minGrade:5,description:"Se hvem der fortæller, hvad vi får adgang til, og hvad det gør ved læsningen.",prompts:["Hvem fortæller historien?","Hvem får vi tanker eller oplevelser fra?","Hvad ved fortælleren – og hvad ved fortælleren ikke?","Hvordan påvirker synsvinklen vores forståelse eller sympati?"],checklist:["Jeg kan pege på tekstspor, der viser fortæller/synsvinkel","Jeg skelner mellem forfatter og fortæller","Jeg forklarer virkningen af synsvinklen"]},
 {id:"komposition",name:"Komposition & opbygning",minGrade:5,description:"Undersøg hvordan teksten er bygget op, og hvorfor rækkefølgen betyder noget.",prompts:["Del teksten i vigtige dele eller vendepunkter","Hvordan begynder teksten, og hvad sætter den i gang?","Hvor ændrer noget sig?","Hvordan virker slutningen i forhold til begyndelsen og resten af teksten?"],checklist:["Jeg beskriver tekstens opbygning med konkrete nedslag","Jeg forklarer virkningen af rækkefølge eller vendepunkt","Jeg bruger slutningen i min forståelse af teksten"]},
 {id:"sprog-virkemidler",name:"Sprog & virkemidler",minGrade:5,description:"Undersøg sproglige valg og forbind form, funktion og virkning.",prompts:["Find ord, billeder, gentagelser eller sætningsvalg, der skiller sig ud","Beskriv det sproglige valg præcist","Hvilken funktion har valget i teksten?","Hvilken virkning kan det have på læseren?"],checklist:["Jeg navngiver kun et virkemiddel, når det hjælper analysen","Jeg forklarer virkningen – ikke kun formen","Mine eksempler kommer fra teksten"]},
 {id:"tema-konflikt",name:"Tema & konflikt",minGrade:5,description:"Undersøg hvad teksten kredser om, og hvilke spændinger der driver den.",prompts:["Hvad er den vigtigste konflikt eller spænding?","Hvilke situationer eller valg viser konflikten?","Hvilke større spørgsmål kredser teksten om?","Formulér et muligt tema som mere end ét enkelt ord."],checklist:["Mit tema bygger på flere steder i teksten","Jeg skelner mellem emne og tema","Jeg kobler konflikt og tema sammen"]},
 {id:"fortolkning",name:"Fortolkning med belæg",minGrade:6,description:"Saml dine iagttagelser til en begrundet forståelse af teksten.",prompts:["Hvilke 2–4 observationer er vigtigst for din forståelse?","Hvad peger observationerne samlet på?","Formulér din fortolkning i 1–3 tydelige sætninger","Gå tilbage til teksten: Hvilke belæg støtter fortolkningen, og er der noget, der udfordrer den?"],checklist:["Min fortolkning kan spores tilbage til teksten","Jeg bruger flere typer belæg","Jeg forklarer, hvordan belæg og fortolkning hænger sammen","Jeg er åben for, at teksten kan rumme mere end én rimelig fortolkning"]},
 {id:"sagprosa",name:"Sagprosa: afsender, modtager & formål",minGrade:5,description:"Undersøg hvem der kommunikerer, til hvem, hvorfor og med hvilke valg.",prompts:["Hvem er afsender, og hvem er den tænkte modtager?","Hvad vil afsenderen have modtageren til at vide, mene eller gøre?","Hvordan er teksten bygget og sproget valgt til formålet?","Hvad virker overbevisende eller mindre overbevisende – og hvorfor?"],checklist:["Jeg skelner mellem afsender, modtager og emne","Jeg bruger konkrete valg i teksten som belæg","Jeg vurderer virkning ud fra formål og situation"]},
 {id:"argumentation",name:"Argumentation",minGrade:6,description:"Find påstande, belæg og måder teksten forsøger at overbevise på.",prompts:["Hvad er tekstens vigtigste påstand eller synspunkt?","Hvilke belæg eller eksempler bruges?","Hvilke antagelser skal man acceptere, for at argumentet virker?","Hvordan bruges sprog eller appel til at påvirke modtageren?","Vurder styrken i argumentationen."],checklist:["Jeg kan skelne påstand og belæg","Jeg undersøger argumentets styrke – ikke kun om jeg er enig","Jeg bruger eksempler fra teksten"]},
 {id:"perspektivering",name:"Perspektivering",minGrade:7,description:"Sæt teksten i forbindelse med andre tekster, temaer, tid eller samfund på en fagligt begrundet måde.",prompts:["Hvad vil du perspektivere til?","Hvilken konkret lighed eller forskel er relevant?","Hvordan gør sammenligningen din forståelse af teksten skarpere?","Hvad kan de to tekster/forhold vise forskelligt om det samme spørgsmål?"],checklist:["Min perspektivering har en tydelig faglig grund","Jeg sammenligner konkrete forhold","Perspektiveringen gør mere end bare at nævne en anden tekst"]},
 {id:"multimodal",name:"Billede, lyd & multimodal tekst",minGrade:5,description:"Undersøg hvordan tekst, billede, lyd, layout eller filmiske valg arbejder sammen.",prompts:["Hvilke udtryksformer bruges?","Hvad bidrager hver udtryksform med?","Hvor støtter eller modsiger udtryksformerne hinanden?","Hvordan styrer samspillet din opmærksomhed eller forståelse?"],checklist:["Jeg analyserer mere end selve ordene","Jeg forklarer samspillet mellem udtryksformer","Jeg kobler formvalg til formål og virkning"]}
];

export function danishAnalysisByName(value:string|undefined|null){return danishAnalysisTemplates.find(x=>x.name===value||x.id===value)||null}

function simplify(prompt:string){return prompt.replace(/^Undersøg\s+/i,"Se på ").replace(/^Formulér\s+/i,"Skriv ").replace(/^Beskriv\s+/i,"Fortæl ").replace(/^Hvilken virkning kan/i,"Hvad gør")}

export function danishAnalysisSupport(template:DanishAnalysisTemplate,grade:number|null|undefined):DanishAnalysisSupport{
 if(grade==null)return{band:"Åben progression",coach:"Arbejd tekstnært: se først, forklar derefter, og fortolk til sidst. Brug konkrete steder i teksten som belæg.",prompts:template.prompts,checklist:template.checklist};
 if(grade<=4)return{band:"3.–4. klasse",coach:"Find først noget helt konkret i teksten. Fortæl, hvad du ser, og forklar bagefter, hvad det kan betyde.",prompts:template.prompts.slice(0,Math.min(3,template.prompts.length)).map(simplify),checklist:["Jeg har fundet et sted i teksten, der passer til mit svar","Jeg forklarer med mine egne ord","Jeg har læst mit svar igennem"]};
 if(grade<=6)return{band:"5.–6. klasse",coach:"Brug rækkefølgen: tekstspor → faglig iagttagelse → forklaring. Din pointe skal kunne findes tilbage i teksten.",prompts:template.prompts.slice(0,Math.min(4,template.prompts.length)),checklist:[...template.checklist,"Jeg forklarer forbindelsen mellem mit tekstspor og min pointe"]};
 return{band:grade<=9?"7.–9. klasse":"10. klasse",coach:"Byg analysen som et argument: præcis iagttagelse → tekstligt belæg → faglig forklaring → fortolkende pointe. Overvej også alternative læsninger, hvor teksten giver mulighed for det.",prompts:template.prompts,checklist:[...template.checklist,"Jeg går fra observation til analyse i stedet for at genfortælle","Mine konklusioner er proportionale med det belæg, teksten faktisk giver"]};
}
