import type {DanishGenre} from "./danishGenres";

export const danishGenreExtras:DanishGenre[]=[
 {id:"billedbog",name:"Billedbog",category:"Fiktion",purpose:"Fortæl gennem et bevidst samspil mellem billeder, korte tekststykker og opslag.",audience:"En læser, der oplever historien gennem både det skrevne og det visuelle.",structure:["Planlæg historiens begyndelse og hovedperson","Fordel forløbet på opslag eller sider","Beslut hvad billedet fortæller, og hvad teksten fortæller","Skab vendepunkt eller udvikling","Afslut med et stærkt sidste opslag"],features:["Samspil mellem tekst og billede","Sidevendinger","Visuel fortælling","Korte tekstmængder","Gentagelser eller billedmotiver"],checklist:["Fortæller billeder og tekst forskellige ting?","Er hvert opslag nødvendigt?","Er der en tydelig udvikling?"]},
 {id:"drama",name:"Drama / skuespil",category:"Fiktion",purpose:"Skab en dramatisk fortælling, der udfolder sig gennem scener, handling og replikker.",audience:"Et publikum samt de personer, der skal opføre teksten.",structure:["Etabler scene og konflikt","Lad personer handle og tale","Byg spænding gennem flere scener","Skab et afgørende vendepunkt","Afslut konflikten eller lad den stå meningsfuldt åben"],features:["Replikker","Sceneanvisninger","Konflikt","Handling i nutid","Undertekst"],checklist:["Kan historien forstås gennem det, der sker på scenen?","Har replikkerne en funktion?","Er konflikterne tydelige?"]},
 {id:"fantasy",name:"Fantasy",category:"Fiktion",purpose:"Fortæl en historie i en verden, hvor fantastiske elementer følger deres egne troværdige regler.",audience:"En læser, der skal kunne leve sig ind i både verden, personer og konflikt.",structure:["Etabler verden og hovedperson","Vis det fantastiske gennem handling","Introducér opgave, trussel eller konflikt","Lad valgene få konsekvenser","Skab klimaks og ny balance"],features:["Verdensbygning","Fantastiske elementer","Regler for universet","Konflikt","Helte, modstandere eller prøvelser"],checklist:["Har verden forståelige regler?","Undgår du at forklare alt på én gang?","Driver personernes valg historien frem?"]},
 {id:"graphic-novel",name:"Graphic novel",category:"Fiktion",purpose:"Fortæl en længere, nuanceret historie gennem sekventielle billeder og tekst.",audience:"En læser, der fortolker billedside, komposition, replikker og fortælling samlet.",structure:["Planlæg historie og kapitler","Lav storyboard og visuel rytme","Veksle mellem nærbilleder, totaler og pauser","Udvikl konflikt og personer over flere sekvenser","Afslut den samlede fortællebue"],features:["Paneler","Visuel dramaturgi","Talebobler og tekstbokse","Billedsymbolik","Længere fortællebue"],checklist:["Er billedrækkefølgen let at følge?","Fortæller billedsiden noget teksten ikke gør?","Er tempoet varieret?"]},
 {id:"kortfilm",name:"Kortfilm",category:"Fiktion",purpose:"Fortæl en koncentreret historie gennem levende billeder, lyd, handling og få scener.",audience:"Et publikum, der skal forstå historien visuelt og auditivt.",structure:["Formulér idé og konflikt","Lav kort synopsis og storyboard","Planlæg scener og billedudsnit","Optag med fokus på handling og lyd","Redigér til et præcist forløb og en stærk slutning"],features:["Billedbeskæring","Klipning","Lyd","Mise-en-scène","Vis frem for at forklare"],checklist:["Kan historien forstås uden lange forklaringer?","Har hver scene en funktion?","Er lyd og billeder bevidste valg?"]},
 {id:"roman",name:"Roman",category:"Fiktion",purpose:"Udvikl en længere fiktiv fortælling med personer, konflikter og flere forløb over tid.",audience:"En læser, der skal kunne følge og engagere sig i en længere fortælleverden.",structure:["Planlæg hovedkonflikt og personer","Skab kapitler med delmål og udvikling","Lad relationer og konflikter forandre sig","Byg mod centrale vendepunkter","Saml fortællebuerne i en afslutning"],features:["Længere tidsforløb","Personudvikling","Miljø","Flere scener eller spor","Fortæller og synsvinkel"],checklist:["Har hovedpersonen en udvikling?","Hænger kapitlerne sammen?","Er der progression gennem hele fortællingen?"]},
 {id:"spillefilm",name:"Spillefilm",category:"Fiktion",purpose:"Udvikl en længere filmfortælling med en bæredygtig konflikt, karakterudvikling og visuel dramaturgi.",audience:"Et publikum, der følger en længere audiovisuel fortælling.",structure:["Idé, præmis og hovedperson","Synopsis og aktstruktur","Scener med mål og konflikt","Vendepunkter og klimaks","Afslutning og konsekvens"],features:["Dramaturgi","Karakterbue","Visuel fortælling","Lyd og musik","Scenisk handling"],checklist:["Kan hovedkonflikten bære hele filmen?","Udvikler karaktererne sig?","Er scenerne visuelt fortalt?"]},
 {id:"science-fiction",name:"Science fiction",category:"Fiktion",purpose:"Undersøg mennesker og samfund gennem teknologi, videnskab eller mulige fremtider.",audience:"En læser eller seer, der både skal leve sig ind i fortællingen og tænke over dens idé.",structure:["Tag udgangspunkt i et 'hvad nu hvis?'","Etabler verden og dens teknologi eller vilkår","Vis konsekvenser gennem personer og konflikt","Skærp det etiske eller samfundsmæssige spørgsmål","Afslut med en konsekvens eller ny erkendelse"],features:["Fremtid eller alternativ virkelighed","Teknologi eller videnskab","Samfundsperspektiv","Etisk dilemma","Konsekvenstænkning"],checklist:["Er idéen konsekvent gennemført?","Handler historien også om mennesker?","Får teknologien konsekvenser?"]},
 {id:"artikel",name:"Artikel",category:"Information",purpose:"Formidl et emne klart og struktureret til en bestemt læsergruppe.",audience:"Læsere, der søger viden, overblik eller perspektiv om emnet.",structure:["Rubrik","Manchet eller kort indledning","Præsentér det vigtigste","Udfold stoffet i afsnit med mellemoverskrifter","Brug eksempler, fakta, citater eller kilder","Afrund eller perspektivér"],features:["Tydelig vinkel","Rubrik og evt. manchet","Afsnit","Kilder eller eksempler","Tilpasset modtager"],checklist:["Er vinklen tydelig?","Kan teksten skimmes?","Er oplysninger og kilder troværdige?"]},
 {id:"dokumentarfilm",name:"Dokumentarfilm",category:"Information",purpose:"Undersøg og formidl virkelige mennesker, begivenheder eller problemstillinger gennem filmiske virkemidler.",audience:"Et publikum, der skal oplyses og samtidig forstå filmens valgte perspektiv.",structure:["Formulér spørgsmål og vinkel","Research og planlæg kilder","Optag interview, observationer og miljø","Skab sammenhæng gennem klipning og evt. speak","Dokumentér og perspektivér i afslutningen"],features:["Virkelighedsstof","Kilder","Interview","Observation","Filmiske virkemidler og tydelig vinkel"],checklist:["Er fakta dokumenterede?","Er kilderne repræsenteret loyalt?","Er filmens vinkel tydelig uden at foregive neutralitet?"]},
 {id:"webdok",name:"Webdok",category:"Information",purpose:"Formidl et dokumentarisk emne interaktivt gennem tekst, billede, lyd, video og brugerens navigation.",audience:"En digital bruger, der selv bevæger sig gennem materialet.",structure:["Definér hovedspørgsmål og målgruppe","Planlæg informationsarkitektur","Fordel stof på tekst, video, lyd og grafik","Skab tydelige valg og navigation","Afslut med perspektiv eller videre handling"],features:["Multimodalitet","Interaktivitet","Navigation","Dokumentation","Digital brugeroplevelse"],checklist:["Er det tydeligt, hvor brugeren skal begynde?","Har hvert medieformat en grund til at være der?","Kan kilder og fakta findes og forstås?"]},
 {id:"pressefoto",name:"Pressefoto",category:"Information",purpose:"Dokumentér eller fortolk en virkelig begivenhed visuelt med journalistisk relevans.",audience:"Mediebrugere, der skal forstå noget om en virkelig situation gennem billedet.",structure:["Vælg begivenhed og vinkel","Overvej position, øjeblik og billedudsnit","Tag flere dokumentariske billeder","Udvælg det stærkeste og mest præcise foto","Skriv en korrekt billedtekst med nødvendig kontekst"],features:["Dokumentarisk øjeblik","Komposition","Nyhedsværdi","Etik","Billedtekst"],checklist:["Er motivet autentisk og ikke vildledende?","Har billedet en journalistisk pointe?","Er billedteksten præcis?"]},
 {id:"maleri",name:"Maleri / visuel fortolkning",category:"Andre formater",purpose:"Udtryk eller fortolk et tema gennem komposition, farve, form, symboler og visuelle valg.",audience:"En beskuer, der skal opleve og fortolke værket.",structure:["Vælg tema eller idé","Lav skitser og vælg komposition","Arbejd bevidst med form, farve og symboler","Revider helhedsindtrykket","Præsentér værket med en kort kunstnerisk begrundelse"],features:["Komposition","Farve","Symbolik","Materiale","Visuelt udtryk"],checklist:["Understøtter de visuelle valg idéen?","Er fokus tydeligt?","Kan du begrunde dine vigtigste valg?"]},
 {id:"reality",name:"Reality-format",category:"Andre formater",purpose:"Udvikl eller analyser et realityformat, hvor virkelige deltagere sættes i en iscenesat ramme.",audience:"Et publikum, der følger personer, konflikter og formatets regler.",structure:["Beskriv koncept og målgruppe","Fastlæg regler, roller og ramme","Planlæg hvordan konflikter og udvikling kan opstå","Overvej kamera, klipning og fortællergreb","Vurder etik og hvad formatet får seeren til at tro"],features:["Virkelige deltagere","Iscenesættelse","Formatregler","Klipning","Etiske problemstillinger"],checklist:["Er forskellen mellem virkelighed og iscenesættelse tydelig?","Hvad gør redigeringen ved fortællingen?","Er de etiske valg forsvarlige?"]}
];
