export type TrainingQuestion={q:string;options:string[];answer:string;why:string};
const q=(text:string,options:string[],answer:string,why:string):TrainingQuestion=>({q:text,options,answer,why});
export type LevelBank=Record<string,TrainingQuestion[]>;
export const freeTrainingQuestions:Record<string,Record<string,Record<string,LevelBank>>>={
'dansk-grammatik':{
 'ordklasser':{
  'Navneord':{
   start:[q('Hvilket ord er en ting?',['løbe','bold','glad','hurtigt'],'bold','En bold er en ting og derfor et navneord.'),q('Hvad kan du sætte “en” foran?',['kat','sove','stor','meget'],'kat','Man kan sige en kat.'),q('Find navneordet: “Hunden løber.”',['Hunden','løber','begge','ingen'],'Hunden','Hunden betegner et dyr.'),q('Hvilket ord er navnet på et sted?',['skole','læser','smuk','langsomt'],'skole','Skole er et navneord.'),q('Hvilket ord er ikke en ting eller et navn?',['bord','sommer','cykel','hopper'],'hopper','Hopper fortæller en handling.')],
   basis:[q('Hvilket ord er et navneord?',['løber','cykel','hurtigt','glad'],'cykel','Cykel er navnet på en ting.'),q('Hvilket ord kan du sætte “en” foran?',['bog','læse','smuk','meget'],'bog','Man kan sige en bog.'),q('Find navneordet: “Katten sover.”',['Katten','sover','begge','ingen'],'Katten','Katten betegner et dyr.'),q('Hvilket er et egennavn?',['by','pige','Odense','skole'],'Odense','Odense er navnet på et bestemt sted.'),q('Hvilket ord er ikke et navneord?',['venskab','bord','danser','sommer'],'danser','Danser er her et udsagnsord.')],
   traening:[q('Hvilket navneord er abstrakt?',['stol','venskab','hund','blyant'],'venskab','Venskab er noget, vi kan forstå, men ikke røre ved.'),q('Hvilket ord er et egennavn?',['land','Danmark','by','hav'],'Danmark','Egennavne betegner noget bestemt og skrives med stort.'),q('Hvilken række består kun af navneord?',['bog, skole, tanke','løbe, bog, glad','hurtig, tanke, der','skrive, læse, skole'],'bog, skole, tanke','Alle tre ord er navneord.'),q('Hvad er navneordets funktion i “Eleven åbner døren”?',['Eleven og døren navngiver deltagere/ting','De viser tid','De beskriver handlingen','De binder sætninger sammen'],'Eleven og døren navngiver deltagere/ting','Navneord kan bl.a. være grundled og genstandsled.'),q('Hvilket ord kan både betegne en person og en rolle?',['lærer','hurtigt','underviser','fordi'],'lærer','Lærer er et navneord, der betegner en person/rolle.')],
   udfordring:[q('Hvilken formulering gør et abstrakt begreb konkret?',['Frygt fyldte rummet','Der var frygt','Frygt er et navneord','Man frygtede'],'Frygt fyldte rummet','Det abstrakte navneord får en konkret, billedlig handling.'),q('Hvilket navneord er mest værdiladet?',['beslutning','katastrofe','møde','forslag'],'katastrofe','Katastrofe rummer en stærk negativ vurdering.'),q('Hvorfor kan nominalisering gøre en tekst tung?',['Handlinger bliver pakket ind som navneord','Navneord kan ikke bøjes','Alle sætninger bliver korte','Der kommer automatisk komma'],'Handlinger bliver pakket ind som navneord','Fx “gennemførelse af evaluering” kan være tungere end “vi evaluerer”.'),q('Hvilken omskrivning er mest handlingspræget?',['Der skete en vurdering af sagen','Vi vurderede sagen','Sagens vurdering fandt sted','En vurdering blev foretaget'],'Vi vurderede sagen','Et aktivt udsagnsord gør handlingen tydelig.'),q('Form → funktion → effekt: “katastrofen” i en debattekst?',['Navneord → navngiver hændelsen → kan rammesætte den negativt','Biord → viser tid → skaber tempo','Stedord → henviser → skaber fællesskab','Udsagnsord → handling → skaber fart'],'Navneord → navngiver hændelsen → kan rammesætte den negativt','Ordvalget påvirker, hvordan læseren opfatter emnet.')]
  },
  'Udsagnsord':{start:[q('Hvilket ord fortæller, hvad nogen gør?',['løber','hund','rød','meget'],'løber','Løber er en handling.'),q('Hvad kan du sætte “at” foran?',['cykle','cykel','glad','stor'],'cykle','Man kan sige at cykle.'),q('Find handlingen: “Maja hopper.”',['Maja','hopper','begge','ingen'],'hopper','Hopper fortæller, hvad Maja gør.'),q('Hvilket ord er en handling?',['spiser','mad','sulten','hun'],'spiser','Spiser er et udsagnsord.'),q('Hvilket er ikke en handling?',['løbe','sove','stol','grine'],'stol','Stol er en ting.')],basis:[q('Hvilket ord er udsagnsord? “Maja løber hjem.”',['Maja','løber','hjem','ingen'],'løber','Løber fortæller, hvad Maja gør.'),q('Hvilket udsagnsord står i datid?',['spiser','spiste','spise','spis'],'spiste','Handlingen er allerede sket.'),q('Find udsagnsordet: “Børnene griner højt.”',['Børnene','griner','højt','Børnene griner'],'griner','Griner er handlingen.'),q('Hvilket står i nutid?',['løb','løber','løbe','løbet'],'løber','Løber står i nutid.'),q('Hvilket er ikke et udsagnsord?',['løbe','tænker','stol','sov'],'stol','Stol er et navneord.')]}
 },
 'saetninger':{'Grundled og udsagnsled':{basis:[q('Find udsagnsleddet: “Maja cykler.”',['Maja','cykler','Maja cykler','ingen'],'cykler','Udsagnsleddet fortæller handlingen.'),q('Find grundleddet: “Hunden gøede.”',['Hunden','gøede','begge','ingen'],'Hunden','Grundleddet udfører handlingen.'),q('Hvad er udsagnsleddet i “De har spist”?',['De','har spist','spist','har'],'har spist','Et udsagnsled kan bestå af flere udsagnsord.'),q('Grundleddet i “Børnene leger ude” er…',['Børnene','leger','ude','leger ude'],'Børnene','Det er børnene, der udfører handlingen.'),q('Hvilket spørgsmål hjælper med at finde grundleddet?',['Hvem/hvad + udsagnsled?','Hvorfor?','Hvornår?','Hvor mange?'],'Hvem/hvad + udsagnsled?','Spørg fx: Hvem cykler?')]}}
},
'matematik':{
 'tal-regning':{
  'Tal og mængder':{talstart:[q('Hvilket tal kommer efter 7?',['6','8','9','17'],'8','Når vi tæller videre fra 7, kommer 8.'),q('Hvor mange prikker er der: ● ● ● ● ?',['3','4','5','6'],'4','Der er fire prikker.'),q('Hvilket tal er størst?',['3','8','5','2'],'8','8 er større end de andre tal.'),q('Hvad mangler? 2, 3, 4, __, 6',['1','5','7','8'],'5','Tallene tæller én op ad gangen.'),q('Hvilket tal er mindst?',['10','4','7','9'],'4','4 er det mindste tal.')],grund:[q('Hvad er værdien af 5 i tallet 352?',['5','50','500','3.052'],'50','5 står på tierpladsen.'),q('Hvilket tal er størst?',['398','389','308','383'],'398','398 har flest tiere efter samme antal hundreder.'),q('Afrund 347 til nærmeste hundrede.',['300','340','350','400'],'300','347 er tættere på 300 end 400.'),q('Hvilket tal er 100 større end 625?',['525','725','635','1.625'],'725','625 + 100 = 725.'),q('Hvad er halvdelen af 80?',['20','30','40','60'],'40','80 delt i to lige store dele giver 40.')]},
  'Plus og minus':{talstart:[q('Hvad er 4 + 3?',['6','7','8','9'],'7','Fire plus tre er syv.'),q('Hvad er 9 - 2?',['5','6','7','8'],'7','Når to tages fra ni, er der syv tilbage.'),q('Du har 5 æbler og får 2 mere. Hvor mange har du?',['3','6','7','8'],'7','5 + 2 = 7.'),q('Hvad er 10 - 4?',['4','5','6','7'],'6','10 - 4 = 6.'),q('Hvilket regnestykke giver 8?',['4 + 4','3 + 4','10 - 3','2 + 5'],'4 + 4','4 + 4 = 8.')],grund:[q('Hvad er 48 + 27?',['65','75','85','95'],'75','48 + 20 + 7 = 75.'),q('Hvad er 103 - 47?',['46','56','66','76'],'56','103 - 47 = 56.'),q('Hvad mangler? 35 + __ = 80',['35','45','55','65'],'45','80 - 35 = 45.'),q('Du har 250 kr. og bruger 87 kr. Hvor meget er tilbage?',['153','163','173','337'],'163','250 - 87 = 163.'),q('Hvilket overslag passer bedst til 198 + 304?',['ca. 300','ca. 400','ca. 500','ca. 600'],'ca. 500','200 + 300 er cirka 500.')]}
 },
 'broeker-procent':{
  'Procent':{mellem:[q('Hvad er 50 % af 100?',['25','50','75','100'],'50','50 % betyder halvdelen.'),q('En vare til 200 kr. sættes 25 % ned. Hvor stor er rabatten?',['25 kr.','50 kr.','75 kr.','100 kr.'],'50 kr.','25 % af 200 kr. er 50 kr.'),q('Hvad svarer 0,5 til i procent?',['5 %','25 %','50 %','500 %'],'50 %','0,5 er halvdelen, altså 50 %.'),q('20 ud af 100 er…',['2 %','20 %','50 %','80 %'],'20 %','Procent betyder pr. hundrede.'),q('En pris stiger fra 100 til 110 kr. Stigningen er…',['5 %','10 %','11 %','110 %'],'10 %','Stigningen er 10 ud af de oprindelige 100.')]}
 },
 'anvendt':{
  'Penge og budget':{anvendt:[q('Du har 500 kr. Et køb koster 325 kr. Hvor meget har du tilbage?',['125 kr.','175 kr.','225 kr.','825 kr.'],'175 kr.','500 - 325 = 175.'),q('Tre billetter koster 75 kr. stykket. Hvad koster de?',['150 kr.','200 kr.','225 kr.','250 kr.'],'225 kr.','3 × 75 = 225.'),q('Et abonnement koster 129 kr. om måneden. Hvad koster 2 måneder?',['129 kr.','158 kr.','258 kr.','300 kr.'],'258 kr.','2 × 129 = 258.'),q('Du har 1.000 kr. og bruger 650 kr. Hvor meget er tilbage?',['250 kr.','350 kr.','450 kr.','650 kr.'],'350 kr.','1.000 - 650 = 350.'),q('Samme vare koster 240 kr. og 199 kr. Hvor meget sparer du?',['31 kr.','41 kr.','51 kr.','61 kr.'],'41 kr.','240 - 199 = 41.')]}
 }
}
};
