"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {supabase} from "../../../lib/supabase";
import {hasRole} from "../../../lib/roles";

type Klass={id:number;name:string;school_id?:number};
type Student={id:number;name:string;class_id:number|null;access_code?:string};
type User={id:string;email:string;roles:string[]};
type PLink={parent_id:string;student_id:number};

const box={background:"white",border:"1px solid #ddd9d0",borderRadius:14,padding:24};
const roleOptions=[["teacher","Lærer"],["parent","Forælder"],["board","Bestyrelsesmedlem"],["admin","Admin"]];
const roleLabels:Record<string,string>={teacher:"Lærer",parent:"Forælder",board:"Bestyrelsesmedlem",admin:"Admin"};

export default function AdminUsers(){
 const[ready,setReady]=useState(false),[schoolId,setSchoolId]=useState<number|null>(null),[classes,setClasses]=useState<Klass[]>([]),[students,setStudents]=useState<Student[]>([]),[users,setUsers]=useState<User[]>([]),[links,setLinks]=useState<PLink[]>([]),[className,setClassName]=useState(""),[studentName,setStudentName]=useState(""),[classId,setClassId]=useState<number|"">(""),[parentId,setParentId]=useState(""),[childId,setChildId]=useState<number|"">(""),[message,setMessage]=useState(""),[loadError,setLoadError]=useState("");
 const[newEmail,setNewEmail]=useState(""),[newPassword,setNewPassword]=useState(""),[newRoles,setNewRoles]=useState<string[]>(["teacher"]),[creating,setCreating]=useState(false),[editing,setEditing]=useState<string|null>(null),[editRoles,setEditRoles]=useState<string[]>([]),[resetPassword,setResetPassword]=useState("");
 const[editingClass,setEditingClass]=useState<number|null>(null),[editClassName,setEditClassName]=useState(""),[editingStudent,setEditingStudent]=useState<number|null>(null),[editStudentName,setEditStudentName]=useState(""),[editStudentClass,setEditStudentClass]=useState<number|"">("");

 async function load(activeSchoolId?:number|null){setLoadError("");let sid=activeSchoolId??schoolId;if(!sid){const{data:auth}=await supabase.auth.getSession();const uid=auth.session?.user.id;if(uid){const{data:m,error:mErr}=await supabase.from("school_memberships").select("school_id").eq("user_id",uid).eq("role","admin").eq("active",true).limit(1).maybeSingle();if(mErr){setLoadError(`Skoleadgang: ${mErr.message}`);return}sid=m?.school_id??null;if(sid)setSchoolId(sid)}}if(!sid){setLoadError("Din administratorkonto er ikke knyttet til en aktiv skole.");return}const[cRes,sRes,uRes,lRes]=await Promise.all([supabase.from("classes").select("id,name,school_id").eq("school_id",sid).order("name"),supabase.from("students").select("id,name,class_id,access_code").order("name"),supabase.rpc("admin_user_directory"),supabase.rpc("admin_parent_links")]);const ownClasses=(cRes.data||[]) as Klass[];const ownClassIds=new Set(ownClasses.map(c=>c.id));setClasses(ownClasses);setStudents(((sRes.data||[]) as Student[]).filter(s=>s.class_id!==null&&ownClassIds.has(s.class_id)));setUsers(((uRes.data||[]) as any[]).map(x=>({...x,roles:Array.isArray(x.roles)?x.roles:[]})));setLinks((lRes.data||[]) as PLink[]);const errors=[cRes.error&&`Klasser: ${cRes.error.message}`,sRes.error&&`Elever: ${sRes.error.message}`,uRes.error&&`Brugerkatalog: ${uRes.error.message}`,lRes.error&&`Forældrekoblinger: ${lRes.error.message}`].filter(Boolean);if(errors.length)setLoadError(errors.join(" | "))}
 useEffect(()=>{(async()=>{const{data}=await supabase.auth.getSession();const u=data.session?.user;if(!u||!hasRole(u,"admin")){window.location.replace("/");return}const{data:m,error}=await supabase.from("school_memberships").select("school_id").eq("user_id",u.id).eq("role","admin").eq("active",true).limit(1).maybeSingle();if(error||!m?.school_id){setLoadError(error?`Skoleadgang: ${error.message}`:"Din administratorkonto er ikke knyttet til en aktiv skole.");setReady(true);return}setSchoolId(m.school_id);await load(m.school_id);setReady(true)})()},[]);
 async function api(path:string,method:string,body:any){const{data}=await supabase.auth.getSession();const token=data.session?.access_token;if(!token)throw new Error("Din session er udløbet. Log ind igen.");const res=await fetch(path,{method,headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify(body)});const result=await res.json();if(!res.ok)throw new Error(result.error||"Handlingen mislykkedes.");return result}
 async function createUser(e:React.FormEvent){e.preventDefault();if(!newEmail.trim()||newPassword.length<8||!newRoles.length){setMessage("Udfyld mail, mindst én rolle og en adgangskode på mindst 8 tegn.");return}setCreating(true);setMessage("");try{await api("/api/admin/create-user","POST",{email:newEmail,password:newPassword,roles:newRoles});setMessage(`Brugeren ${newEmail.trim()} er oprettet.`);setNewEmail("");setNewPassword("");setNewRoles(["teacher"]);await load()}catch(err:any){setMessage(err?.message||"Brugeren kunne ikke oprettes.")}finally{setCreating(false)}}
 function toggleRole(role:string){setNewRoles(r=>r.includes(role)?r.filter(x=>x!==role):[...r,role])}
 async function saveUser(id:string){try{await api("/api/admin/manage-user","PATCH",{id,roles:editRoles});setMessage("Rollerne er gemt.");setEditing(null);await load()}catch(e:any){setMessage(e.message)}}
 async function changePassword(id:string){if(resetPassword.length<8){setMessage("Adgangskoden skal være mindst 8 tegn.");return}try{await api("/api/admin/manage-user","PATCH",{id,password:resetPassword});setMessage("Adgangskoden er nulstillet.");setResetPassword("");setEditing(null)}catch(e:any){setMessage(e.message)}}
 async function deleteUser(id:string,email:string){if(!confirm(`Vil du slette ${email}? Dette kan ikke fortrydes.`))return;try{await api("/api/admin/manage-user","DELETE",{id});setMessage(`${email} er slettet.`);await load()}catch(e:any){setMessage(e.message)}}
 async function addClass(e:React.FormEvent){e.preventDefault();if(!className.trim())return;if(!schoolId){setMessage("Skolen kunne ikke bestemmes. Log ind igen.");return}const{error}=await supabase.from("classes").insert({name:className.trim(),school_id:schoolId});setMessage(error?`Klassen kunne ikke oprettes: ${error.message}`:"Klassen er oprettet.");if(!error){setClassName("");await load()}}
 async function saveClass(id:number){if(!editClassName.trim())return;const{error}=await supabase.from("classes").update({name:editClassName.trim()}).eq("id",id);setMessage(error?`Klassen kunne ikke gemmes: ${error.message}`:"Klassen er gemt.");if(!error){setEditingClass(null);await load()}}
 async function deleteClass(c:Klass){const count=students.filter(s=>s.class_id===c.id).length;if(count>0){setMessage(`Flyt eller slet først klassens ${count} elev${count===1?"":"er"}.`);return}if(!confirm(`Vil du slette klassen ${c.name}?`))return;const{error}=await supabase.from("classes").delete().eq("id",c.id);setMessage(error?`Klassen kunne ikke slettes: ${error.message}`:`${c.name} er slettet.`);if(!error)await load()}
 async function addStudent(e:React.FormEvent){e.preventDefault();if(!studentName.trim()||!classId)return;const code=Math.random().toString(36).slice(2,8).toUpperCase();const{error}=await supabase.from("students").insert({name:studentName.trim(),class_id:Number(classId),access_code:code});setMessage(error?"Eleven kunne ikke oprettes.":`Eleven er oprettet med koden ${code}.`);if(!error){setStudentName("");await load()}}
 async function saveStudent(id:number){if(!editStudentName.trim())return;const{error}=await supabase.from("students").update({name:editStudentName.trim(),class_id:editStudentClass===""?null:Number(editStudentClass)}).eq("id",id);setMessage(error?`Eleven kunne ikke gemmes: ${error.message}`:"Eleven er gemt.");if(!error){setEditingStudent(null);await load()}}
 async function newStudentCode(id:number){const code=Math.random().toString(36).slice(2,8).toUpperCase();const{error}=await supabase.from("students").update({access_code:code}).eq("id",id);setMessage(error?`Ny kode kunne ikke oprettes: ${error.message}`:`Ny elevkode: ${code}`);if(!error)await load()}
 async function deleteStudent(s:Student){if(!confirm(`Vil du slette ${s.name}? Elevens koblinger til forældre fjernes også. Dette kan ikke fortrydes.`))return;const{error:linkError}=await supabase.from("parent_students").delete().eq("student_id",s.id);if(linkError){setMessage(`Elevens familiekoblinger kunne ikke fjernes: ${linkError.message}`);return}const{error}=await supabase.from("students").delete().eq("id",s.id);setMessage(error?`Eleven kunne ikke slettes: ${error.message}`:`${s.name} er slettet.`);if(!error){setEditingStudent(null);await load()}}
 async function linkParent(e:React.FormEvent){e.preventDefault();if(!parentId||!childId)return;const{error}=await supabase.rpc("admin_link_parent",{p_parent_id:parentId,p_student_id:Number(childId)});setMessage(error?"Forælderen kunne ikke kobles til eleven.":"Forælder og elev er nu koblet sammen.");if(!error)await load()}
 async function unlink(p:string,s:number){const{error}=await supabase.rpc("admin_unlink_parent",{p_parent_id:p,p_student_id:s});setMessage(error?"Koblingen kunne ikke fjernes.":"Koblingen er fjernet.");if(!error)await load()}
 if(!ready)return <main style={{padding:50}}>Henter brugere og klasser…</main>;

 const parents=users.filter(u=>u.roles.includes("parent"));
 const teachers=users.filter(u=>u.roles.includes("teacher")||u.roles.includes("admin"));
 const boardMembers=users.filter(u=>u.roles.includes("board"));
 const roleText=(roles:string[])=>roles.map(r=>roleLabels[r]||r).join(" · ");
 const userCard=(u:User)=><div key={u.id} style={{padding:"11px 0",borderTop:"1px solid #eee"}}><div style={{display:"flex",justifyContent:"space-between",gap:10,alignItems:"start"}}><div><strong>{u.email}</strong><small style={{display:"block",color:"#777"}}>{roleText(u.roles)}</small></div><button type="button" onClick={()=>{setEditing(editing===u.id?null:u.id);setEditRoles([...u.roles]);setResetPassword("")}} style={{fontSize:12}}>Redigér</button></div>{editing===u.id&&<div style={{marginTop:12,padding:12,background:"#f7f4ed",borderRadius:8}}><div style={{display:"flex",gap:12,flexWrap:"wrap"}}>{roleOptions.map(([r,l])=><label key={r}><input type="checkbox" checked={editRoles.includes(r)} onChange={()=>setEditRoles(x=>x.includes(r)?x.filter(y=>y!==r):[...x,r])}/> {l}</label>)}</div><div style={{display:"flex",gap:8,marginTop:10,flexWrap:"wrap"}}><button type="button" onClick={()=>saveUser(u.id)}>Gem roller</button><input type="password" value={resetPassword} onChange={e=>setResetPassword(e.target.value)} placeholder="Ny adgangskode" style={{padding:6}}/><button type="button" onClick={()=>changePassword(u.id)}>Nulstil kode</button><button type="button" onClick={()=>deleteUser(u.id,u.email)} style={{color:"#8b2f2f"}}>Slet konto</button></div></div>}</div>;

 return <main style={{minHeight:"100vh",background:"#f5f2ea",color:"#26342e"}}><header style={{background:"#486b59",color:"white",padding:"18px 6vw"}}><div style={{maxWidth:1100,margin:"0 auto",display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><strong style={{fontSize:22}}>Administration · Brugere & klasser</strong><small style={{display:"block",opacity:.8}}>Skolens grundstruktur</small></div><Link href="/admin" style={{color:"white",textDecoration:"none",border:"1px solid rgba(255,255,255,.5)",padding:"8px 12px",borderRadius:8}}>← Administration</Link></div></header><section style={{maxWidth:1100,margin:"0 auto",padding:"42px 24px"}}><p className="eyebrow">KONTROLCENTER</p><h1 style={{fontFamily:"Georgia,serif",fontSize:40,margin:"8px 0"}}>Brugere & klasser</h1><p style={{color:"#687068",fontSize:17}}>Administrér skolens klasser, elever, medarbejderkonti og familiekoblinger.</p>{loadError&&<div style={{marginTop:18,padding:14,background:"#fff0ed",border:"1px solid #c96b5c",borderRadius:9,color:"#7b2f25",fontWeight:700}}>⚠️ Supabase-fejl: {loadError}</div>}{message&&<div style={{marginTop:18,padding:14,background:"#e7eee9",borderRadius:9,fontWeight:700}}>{message}</div>}
 <form onSubmit={createUser} style={{...box,marginTop:28}}><h2 style={{fontFamily:"Georgia,serif",marginTop:0}}>Opret bruger</h2><p style={{color:"#687068"}}>Opret en konto og vælg, hvilke områder brugeren skal have adgang til.</p><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(230px,1fr))",gap:12}}><input type="email" required value={newEmail} onChange={e=>setNewEmail(e.target.value)} placeholder="E-mail" style={{padding:12}}/><input type="password" required minLength={8} value={newPassword} onChange={e=>setNewPassword(e.target.value)} placeholder="Midlertidig adgangskode (min. 8 tegn)" style={{padding:12}}/></div><div style={{display:"flex",gap:18,flexWrap:"wrap",margin:"18px 0"}}>{roleOptions.map(([value,label])=><label key={value} style={{display:"flex",alignItems:"center",gap:7,cursor:"pointer"}}><input type="checkbox" checked={newRoles.includes(value)} onChange={()=>toggleRole(value)}/><strong>{label}</strong></label>)}</div><button disabled={creating} style={{padding:"10px 16px"}}>{creating?"Opretter…":"+ Opret bruger"}</button></form>
 <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(300px,1fr))",gap:20,marginTop:20}}><form onSubmit={addClass} style={box}><h2>Opret klasse</h2><input value={className} onChange={e=>setClassName(e.target.value)} placeholder="Fx 7. klasse" style={{width:"100%",boxSizing:"border-box",padding:12,marginBottom:12}}/><button>+ Opret klasse</button></form><form onSubmit={addStudent} style={box}><h2>Opret elev</h2><input value={studentName} onChange={e=>setStudentName(e.target.value)} placeholder="Elevens navn" style={{width:"100%",boxSizing:"border-box",padding:12,marginBottom:10}}/><select value={classId} onChange={e=>setClassId(e.target.value?Number(e.target.value):"")} style={{width:"100%",padding:12,marginBottom:12}}><option value="">Vælg klasse</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><button>+ Opret elev</button></form></div>
 <form onSubmit={linkParent} style={{...box,marginTop:20}}><h2 style={{fontFamily:"Georgia,serif"}}>Kobl forælder til barn</h2><p style={{color:"#687068"}}>Vælg en forældrekonto og den elev, kontoen skal kunne se.</p><div style={{display:"flex",gap:12,flexWrap:"wrap"}}><select value={parentId} onChange={e=>setParentId(e.target.value)} style={{flex:1,minWidth:220,padding:12}}><option value="">Vælg forælder</option>{parents.map(p=><option key={p.id} value={p.id}>{p.email}</option>)}</select><select value={childId} onChange={e=>setChildId(e.target.value?Number(e.target.value):"")} style={{flex:1,minWidth:220,padding:12}}><option value="">Vælg elev</option>{students.map(s=><option key={s.id} value={s.id}>{s.name} · {classes.find(c=>c.id===s.class_id)?.name||"Ingen klasse"}</option>)}</select><button style={{padding:"10px 16px"}}>Kobl sammen</button></div></form>
 <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(310px,1fr))",gap:20,marginTop:20}}><section style={box}><h2>Klasser</h2>{classes.map(c=><div key={c.id} style={{padding:"10px 0",borderTop:"1px solid #eee"}}>{editingClass===c.id?<div style={{display:"flex",gap:8}}><input value={editClassName} onChange={e=>setEditClassName(e.target.value)} style={{flex:1,padding:7}}/><button onClick={()=>saveClass(c.id)}>Gem</button><button onClick={()=>setEditingClass(null)}>Annullér</button></div>:<div style={{display:"flex",justifyContent:"space-between",gap:8}}><strong>{c.name}</strong><span><button onClick={()=>{setEditingClass(c.id);setEditClassName(c.name)}}>Redigér</button> <button onClick={()=>deleteClass(c)} style={{color:"#8b2f2f"}}>Slet</button></span></div>}</div>)}</section><section style={box}><h2>Elever</h2>{students.map(s=><div key={s.id} style={{padding:"10px 0",borderTop:"1px solid #eee"}}>{editingStudent===s.id?<div><input value={editStudentName} onChange={e=>setEditStudentName(e.target.value)} style={{width:"100%",boxSizing:"border-box",padding:7,marginBottom:7}}/><select value={editStudentClass} onChange={e=>setEditStudentClass(e.target.value?Number(e.target.value):"")} style={{width:"100%",padding:7}}><option value="">Ingen klasse</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><div style={{marginTop:8,display:"flex",gap:6,flexWrap:"wrap"}}><button onClick={()=>saveStudent(s.id)}>Gem</button><button onClick={()=>newStudentCode(s.id)}>Ny kode</button><button onClick={()=>setEditingStudent(null)}>Annullér</button><button onClick={()=>deleteStudent(s)} style={{color:"#8b2f2f"}}>Slet elev</button></div></div>:<div style={{display:"flex",justifyContent:"space-between",gap:8}}><div><strong>{s.name}</strong><small style={{display:"block",color:"#777"}}>{classes.find(c=>c.id===s.class_id)?.name||"Ingen klasse"} · kode {s.access_code||"—"}</small></div><button onClick={()=>{setEditingStudent(s.id);setEditStudentName(s.name);setEditStudentClass(s.class_id??"")}}>Redigér</button></div>}</div>)}</section></div>
 <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(300px,1fr))",gap:20,marginTop:20}}><section style={box}><h2>Lærere</h2>{teachers.map(userCard)}</section><section style={box}><h2>Forældre</h2>{parents.map(userCard)}</section><section style={box}><h2>Bestyrelse</h2>{boardMembers.map(userCard)}</section></div>
 <section style={{...box,marginTop:20}}><h2>Familiekoblinger</h2>{links.length===0?<p style={{color:"#777"}}>Ingen koblinger endnu.</p>:links.map((l,i)=>{const p=users.find(u=>u.id===l.parent_id),s=students.find(x=>x.id===l.student_id);if(!s)return null;return <div key={`${l.parent_id}-${l.student_id}-${i}`} style={{padding:"9px 0",borderTop:"1px solid #eee",display:"flex",justifyContent:"space-between",gap:12}}><span><strong>{p?.email||"Forælder"}</strong> → {s.name}</span><button onClick={()=>unlink(l.parent_id,l.student_id)}>Fjern</button></div>})}</section>
 </section></main>
}
