"use client";

import Link from "next/link";
import {FormEvent,useEffect,useState} from "react";
import {supabase} from "../../../lib/supabase";
import {hasRole} from "../../../lib/roles";

type Meeting={id:number;title:string;meeting_date:string;start_time:string|null;location:string|null;agenda:string|null;created_at?:string};

export default function BoardMeetingsPage(){
 const[ready,setReady]=useState(false),[meetings,setMeetings]=useState<Meeting[]>([]),[canEdit,setCanEdit]=useState(false),[busy,setBusy]=useState(false);
 const[title,setTitle]=useState("Bestyrelsesmøde"),[date,setDate]=useState(""),[time,setTime]=useState("19:00"),[meetingLocation,setMeetingLocation]=useState(""),[agenda,setAgenda]=useState("");
 useEffect(()=>{(async()=>{const{data}=await supabase.auth.getSession();const user=data.session?.user;if(!user){window.location.href="/";return}if(!hasRole(user,"board")&&!hasRole(user,"admin")){window.location.href="/";return}setCanEdit(hasRole(user,"admin"));await load();setReady(true)})()},[]);
 async function load(){const{data}=await supabase.from("board_meetings").select("*").order("meeting_date",{ascending:true}).order("start_time",{ascending:true});setMeetings((data||[]) as Meeting[])}
 async function add(e:FormEvent){e.preventDefault();if(!date||!title.trim())return;setBusy(true);const{error}=await supabase.from("board_meetings").insert({title:title.trim(),meeting_date:date,start_time:time||null,location:meetingLocation.trim()||null,agenda:agenda.trim()||null});setBusy(false);if(error){alert("Mødet kunne ikke gemmes: "+error.message);return}setMeetingLocation("");setAgenda("");await load()}
 async function remove(id:number){if(!confirm("Vil du slette mødet?"))return;const{error}=await supabase.from("board_meetings").delete().eq("id",id);if(error){alert(error.message);return}await load()}
 if(!ready)return <main style={{padding:50}}>Henter møder…</main>;
 return <main style={{minHeight:"100vh",background:"#f5f3ee",color:"#26342e",paddingBottom:60}}><header style={{background:"#243d33",color:"white",padding:"20px 6vw"}}><div style={{maxWidth:1100,margin:"auto",display:"flex",justifyContent:"space-between",alignItems:"center"}}><strong style={{fontFamily:"Georgia,serif",fontSize:25}}>Bestyrelsen · Møder</strong><Link href="/board" style={{color:"white",fontWeight:700,textDecoration:"none"}}>← Bestyrelsen</Link></div></header><section style={{maxWidth:1100,margin:"auto",padding:"48px 24px"}}><p style={eyebrow}>MØDER & DAGSORDENER</p><h1 style={h1}>Bestyrelsesmøder</h1><p style={lead}>Her ligger kommende og tidligere møder samlet. Dagsordenen følger mødet, så bestyrelsen altid har ét sted at gå hen.</p>{canEdit&&<form onSubmit={add} style={panel}><p style={eyebrow}>OPRET MØDE</p><div style={grid}><label style={label}>Titel<input style={input} value={title} onChange={e=>setTitle(e.target.value)}/></label><label style={label}>Dato<input style={input} type="date" value={date} onChange={e=>setDate(e.target.value)} required/></label><label style={label}>Tid<input style={input} type="time" value={time} onChange={e=>setTime(e.target.value)}/></label><label style={label}>Sted<input style={input} value={meetingLocation} onChange={e=>setMeetingLocation(e.target.value)} placeholder="Fx lærerværelset"/></label></div><label style={{...label,marginTop:14}}>Dagsorden<textarea style={{...input,minHeight:150,resize:"vertical"}} value={agenda} onChange={e=>setAgenda(e.target.value)} placeholder={'1. Godkendelse af dagsorden\n2. Nyt fra skolelederen\n3. Økonomi\n4. Eventuelt'}/></label><button disabled={busy} style={button}>{busy?"Gemmer…":"Opret møde →"}</button></form>}<section style={{marginTop:30}}>{meetings.length===0?<div style={panel}><h2 style={{fontFamily:"Georgia,serif"}}>Ingen møder endnu</h2><p style={{color:"#687068"}}>Når det første møde oprettes, kommer det frem her.</p></div>:meetings.map(m=><article key={m.id} style={{...panel,marginBottom:16}}><div style={{display:"flex",justifyContent:"space-between",gap:18,alignItems:"flex-start",flexWrap:"wrap"}}><div><p style={eyebrow}>{new Date(m.meeting_date+"T12:00:00").toLocaleDateString("da-DK",{weekday:"long",day:"numeric",month:"long",year:"numeric"}).toUpperCase()}</p><h2 style={{fontFamily:"Georgia,serif",fontSize:28,margin:"5px 0"}}>{m.title}</h2><p style={{color:"#687068",margin:"5px 0"}}>{m.start_time?.slice(0,5)&&`Kl. ${m.start_time.slice(0,5)}`}{m.location&&` · ${m.location}`}</p></div>{canEdit&&<button onClick={()=>remove(m.id)} style={{border:0,background:"transparent",color:"#9a463c",cursor:"pointer"}}>Slet</button>}</div><div style={{borderTop:"1px solid #e4e0d8",marginTop:18,paddingTop:18}}><strong>Dagsorden</strong>{m.agenda?<div style={{whiteSpace:"pre-wrap",lineHeight:1.65,marginTop:10,color:"#4e5852"}}>{m.agenda}</div>:<p style={{color:"#8a8f89"}}>Der er ikke tilføjet en dagsorden endnu.</p>}</div></article>)}</section></section></main>
}
const eyebrow={fontSize:11,fontWeight:800,letterSpacing:1.7,color:"#718077",marginBottom:5};const h1={fontFamily:"Georgia,serif",fontSize:44,margin:"7px 0 10px"};const lead={fontSize:18,color:"#687068",lineHeight:1.55,maxWidth:760};const panel={background:"white",border:"1px solid #dedbd2",borderRadius:14,padding:24,marginTop:28};const grid={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(210px,1fr))",gap:14};const label={display:"flex",flexDirection:"column" as const,gap:7,fontWeight:700};const input={boxSizing:"border-box" as const,width:"100%",padding:"12px 13px",border:"1px solid #d6d2c9",borderRadius:8,font:"inherit",background:"#fff"};const button={marginTop:18,padding:"12px 18px",border:0,borderRadius:8,background:"#243d33",color:"white",fontWeight:800,cursor:"pointer"};