"use client";

import Link from "next/link";
import {FormEvent,useEffect,useState} from "react";
import {supabase} from "../../../lib/supabase";
import {hasRole} from "../../../lib/roles";

type Meeting={id:number;title:string;meeting_date:string;start_time:string|null;location:string|null;agenda:string|null;minutes:string|null};
type Decision={id:number;meeting_id:number;decision:string;responsible:string|null;due_date:string|null;completed:boolean};

export default function BoardMeetingsPage(){
 const[ready,setReady]=useState(false),[meetings,setMeetings]=useState<Meeting[]>([]),[decisions,setDecisions]=useState<Decision[]>([]),[canEdit,setCanEdit]=useState(false),[busy,setBusy]=useState(false);
 const[title,setTitle]=useState("Bestyrelsesmøde"),[date,setDate]=useState(""),[time,setTime]=useState("19:00"),[meetingLocation,setMeetingLocation]=useState(""),[agenda,setAgenda]=useState("");
 const[minutesDraft,setMinutesDraft]=useState<Record<number,string>>({}),[decisionDraft,setDecisionDraft]=useState<Record<number,string>>({}),[responsibleDraft,setResponsibleDraft]=useState<Record<number,string>>({}),[dueDraft,setDueDraft]=useState<Record<number,string>>({});
 useEffect(()=>{(async()=>{const{data}=await supabase.auth.getSession();const user=data.session?.user;if(!user){window.location.href="/";return}if(!hasRole(user,"board")&&!hasRole(user,"admin")){window.location.href="/";return}setCanEdit(hasRole(user,"admin"));await load();setReady(true)})()},[]);
 async function load(){const[m,d]=await Promise.all([supabase.from("board_meetings").select("id,title,meeting_date,start_time,location,agenda,minutes").order("meeting_date",{ascending:false}).order("start_time",{ascending:false}),supabase.from("board_decisions").select("id,meeting_id,decision,responsible,due_date,completed").order("created_at",{ascending:true})]);setMeetings((m.data||[]) as Meeting[]);setDecisions((d.data||[]) as Decision[]);const drafts:Record<number,string>={};((m.data||[]) as Meeting[]).forEach(x=>drafts[x.id]=x.minutes||"");setMinutesDraft(drafts)}
 async function add(e:FormEvent){e.preventDefault();if(!date||!title.trim())return;setBusy(true);const{error}=await supabase.from("board_meetings").insert({title:title.trim(),meeting_date:date,start_time:time||null,location:meetingLocation.trim()||null,agenda:agenda.trim()||null});setBusy(false);if(error){alert("Mødet kunne ikke gemmes: "+error.message);return}setMeetingLocation("");setAgenda("");await load()}
 async function saveMinutes(id:number){const{error}=await supabase.from("board_meetings").update({minutes:(minutesDraft[id]||"").trim()||null,updated_at:new Date().toISOString()}).eq("id",id);if(error)alert(error.message);else await load()}
 async function addDecision(meetingId:number){const text=(decisionDraft[meetingId]||"").trim();if(!text)return;const{error}=await supabase.from("board_decisions").insert({meeting_id:meetingId,decision:text,responsible:(responsibleDraft[meetingId]||"").trim()||null,due_date:dueDraft[meetingId]||null});if(error){alert(error.message);return}setDecisionDraft(x=>({...x,[meetingId]:""}));setResponsibleDraft(x=>({...x,[meetingId]:""}));setDueDraft(x=>({...x,[meetingId]:""}));await load()}
 async function toggleDecision(d:Decision){const{error}=await supabase.from("board_decisions").update({completed:!d.completed}).eq("id",d.id);if(error)alert(error.message);else await load()}
 async function remove(id:number){if(!confirm("Vil du slette mødet?"))return;const{error}=await supabase.from("board_meetings").delete().eq("id",id);if(error)alert(error.message);else await load()}
 const today=new Date().toISOString().slice(0,10),upcoming=meetings.filter(m=>m.meeting_date>=today).sort((a,b)=>a.meeting_date.localeCompare(b.meeting_date)),previous=meetings.filter(m=>m.meeting_date<today);
 const meetingCard=(m:Meeting)=><article key={m.id} style={{...panel,marginBottom:16}}><div style={{display:"flex",justifyContent:"space-between",gap:18,flexWrap:"wrap"}}><div><p style={eyebrow}>{new Date(m.meeting_date+"T12:00:00").toLocaleDateString("da-DK",{weekday:"long",day:"numeric",month:"long",year:"numeric"}).toUpperCase()}</p><h2 style={{fontFamily:"Georgia,serif",fontSize:28,margin:"5px 0"}}>{m.title}</h2><p style={{color:"#687068",margin:"5px 0"}}>{m.start_time?`Kl. ${m.start_time.slice(0,5)}`:""}{m.location?` · ${m.location}`:""}</p></div>{canEdit&&<button onClick={()=>remove(m.id)} style={deleteButton}>Slet</button>}</div><section style={section}><strong>Dagsorden</strong><div style={body}>{m.agenda||"Der er ikke tilføjet en dagsorden endnu."}</div></section><section style={section}><strong>Referat</strong>{canEdit?<><textarea style={{...input,minHeight:140,marginTop:10}} value={minutesDraft[m.id]||""} onChange={e=>setMinutesDraft(x=>({...x,[m.id]:e.target.value}))} placeholder="Skriv referatet fra mødet…"/><button onClick={()=>saveMinutes(m.id)} style={smallButton}>Gem referat</button></>:<div style={body}>{m.minutes||"Referatet er ikke lagt op endnu."}</div>}</section><section style={section}><strong>Beslutninger & opfølgning</strong><div style={{marginTop:10}}>{decisions.filter(d=>d.meeting_id===m.id).map(d=><div key={d.id} style={{display:"flex",gap:10,alignItems:"flex-start",padding:"10px 0",borderBottom:"1px solid #eeeae2"}}><input type="checkbox" checked={d.completed} disabled={!canEdit} onChange={()=>toggleDecision(d)}/><div><span style={{textDecoration:d.completed?"line-through":"none",fontWeight:700}}>{d.decision}</span>{(d.responsible||d.due_date)&&<small style={{display:"block",color:"#777",marginTop:3}}>{d.responsible?`Ansvarlig: ${d.responsible}`:""}{d.responsible&&d.due_date?" · ":""}{d.due_date?`Frist: ${new Date(d.due_date+"T12:00:00").toLocaleDateString("da-DK")}`:""}</small>}</div></div>)}{decisions.filter(d=>d.meeting_id===m.id).length===0&&<p style={{color:"#8a8f89"}}>Ingen beslutninger registreret endnu.</p>}</div>{canEdit&&<div style={{display:"grid",gridTemplateColumns:"2fr 1fr 1fr auto",gap:8,marginTop:14}}><input style={input} value={decisionDraft[m.id]||""} onChange={e=>setDecisionDraft(x=>({...x,[m.id]:e.target.value}))} placeholder="Beslutning eller opgave"/><input style={input} value={responsibleDraft[m.id]||""} onChange={e=>setResponsibleDraft(x=>({...x,[m.id]:e.target.value}))} placeholder="Ansvarlig"/><input style={input} type="date" value={dueDraft[m.id]||""} onChange={e=>setDueDraft(x=>({...x,[m.id]:e.target.value}))}/><button onClick={()=>addDecision(m.id)} style={{...smallButton,marginTop:0}}>Tilføj</button></div>}</section></article>;
 if(!ready)return <main style={{padding:50}}>Henter møder…</main>;
 return <main style={{minHeight:"100vh",background:"#f5f3ee",color:"#26342e",paddingBottom:60}}><header style={{background:"#243d33",color:"white",padding:"20px 6vw"}}><div style={{maxWidth:1100,margin:"auto",display:"flex",justifyContent:"space-between",alignItems:"center"}}><strong style={{fontFamily:"Georgia,serif",fontSize:25}}>Bestyrelsen · Møder</strong><Link href="/board" style={{color:"white",fontWeight:700,textDecoration:"none"}}>← Bestyrelsen</Link></div></header><section style={{maxWidth:1100,margin:"auto",padding:"48px 24px"}}><p style={eyebrow}>MØDER · REFERATER · BESLUTNINGER</p><h1 style={h1}>Bestyrelsesmøder</h1><p style={lead}>Hele mødearbejdet samlet ét sted – fra dagsorden til referat, beslutninger og opfølgning.</p>{canEdit&&<form onSubmit={add} style={panel}><p style={eyebrow}>OPRET MØDE</p><div style={grid}><label style={label}>Titel<input style={input} value={title} onChange={e=>setTitle(e.target.value)}/></label><label style={label}>Dato<input style={input} type="date" value={date} onChange={e=>setDate(e.target.value)} required/></label><label style={label}>Tid<input style={input} type="time" value={time} onChange={e=>setTime(e.target.value)}/></label><label style={label}>Sted<input style={input} value={meetingLocation} onChange={e=>setMeetingLocation(e.target.value)} placeholder="Fx lærerværelset"/></label></div><label style={{...label,marginTop:14}}>Dagsorden<textarea style={{...input,minHeight:140}} value={agenda} onChange={e=>setAgenda(e.target.value)} placeholder={'1. Godkendelse af dagsorden\n2. Nyt fra skolelederen\n3. Økonomi\n4. Eventuelt'}/></label><button disabled={busy} style={button}>{busy?"Gemmer…":"Opret møde →"}</button></form>}<h2 style={sectionTitle}>Kommende møder</h2>{upcoming.length?upcoming.map(meetingCard):<p style={{color:"#777"}}>Ingen kommende møder.</p>}<h2 style={sectionTitle}>Tidligere møder</h2>{previous.length?previous.map(meetingCard):<p style={{color:"#777"}}>Ingen tidligere møder endnu.</p>}</section></main>
}
const eyebrow={fontSize:11,fontWeight:800,letterSpacing:1.7,color:"#718077",marginBottom:5};const h1={fontFamily:"Georgia,serif",fontSize:44,margin:"7px 0 10px"};const lead={fontSize:18,color:"#687068",lineHeight:1.55,maxWidth:760};const panel={background:"white",border:"1px solid #dedbd2",borderRadius:14,padding:24,marginTop:28};const grid={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(210px,1fr))",gap:14};const label={display:"flex",flexDirection:"column" as const,gap:7,fontWeight:700};const input={boxSizing:"border-box" as const,width:"100%",padding:"11px 12px",border:"1px solid #d6d2c9",borderRadius:8,font:"inherit",background:"#fff"};const button={marginTop:18,padding:"12px 18px",border:0,borderRadius:8,background:"#243d33",color:"white",fontWeight:800,cursor:"pointer"};const smallButton={marginTop:10,padding:"10px 13px",border:0,borderRadius:8,background:"#486b59",color:"white",fontWeight:800,cursor:"pointer"};const deleteButton={border:0,background:"transparent",color:"#9a463c",cursor:"pointer",height:30};const section={borderTop:"1px solid #e4e0d8",marginTop:18,paddingTop:18};const body={whiteSpace:"pre-wrap" as const,lineHeight:1.65,marginTop:10,color:"#4e5852"};const sectionTitle={fontFamily:"Georgia,serif",fontSize:30,margin:"38px 0 4px"};