"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {supabase} from "../../../lib/supabase";
import {hasRole} from "../../../lib/roles";
type Klass={id:number;name:string};type Teacher={id:string;email:string;roles:string[]};type Entry={id:number;class_id:number;weekday:number;start_time:string;end_time:string;subject:string;teacher:string|null;room:string|null};
const days=["Mandag","Tirsdag","Onsdag","Torsdag","Fredag"];
export default function Schedule(){
 const[ready,setReady]=useState(false),[classes,setClasses]=useState<Klass[]>([]),[teachers,setTeachers]=useState<Teacher[]>([]),[entries,setEntries]=useState<Entry[]>([]),[classId,setClassId]=useState<number|"">(""),[weekday,setWeekday]=useState(1),[start,setStart]=useState("08:00"),[end,setEnd]=useState("08:45"),[subject,setSubject]=useState(""),[teacher,setTeacher]=useState(""),[room,setRoom]=useState(""),[msg,setMsg]=useState("");
 async function load(){const[cRes,eRes,uRes]=await Promise.all([supabase.from("classes").select("id,name").order("name"),supabase.from("schedule_entries").select("*").order("weekday").order("start_time"),supabase.rpc("admin_user_directory")]);const cs=(cRes.data||[]) as Klass[];setClasses(cs);setEntries((eRes.data||[]) as Entry[]);const us=((uRes.data||[]) as any[]).map(x=>({...x,roles:Array.isArray(x.roles)?x.roles:[]}));setTeachers(us.filter((u:Teacher)=>u.roles.includes("teacher")));if(classId===""&&cs[0])setClassId(cs[0].id);if(cRes.error)setMsg(`Klasser kunne ikke hentes: ${cRes.error.message}`);else if(eRes.error)setMsg(`Skemaet kunne ikke hentes: ${eRes.error.message}`);else if(uRes.error)setMsg(`Lærere kunne ikke hentes: ${uRes.error.message}`)}
 useEffect(()=>{(async()=>{const{data}=await supabase.auth.getSession();if(!data.session?.user||!hasRole(data.session.user,"admin")){location.replace("/");return}await load();setReady(true)})()},[]);
 async function add(e:React.FormEvent){e.preventDefault();if(classId===""){setMsg("Vælg en klasse.");return}if(!teacher){setMsg("Vælg en lærer.");return}if(!subject.trim()){setMsg("Skriv et fag.");return}setMsg("");const{error}=await supabase.from("schedule_entries").insert({class_id:Number(classId),weekday,start_time:start,end_time:end,subject:subject.trim(),teacher,room:room.trim()||null});setMsg(error?`Skematimen kunne ikke gemmes: ${error.message}`:"Skematimen er oprettet.");if(!error){setSubject("");setRoom("");await load()}}
 async function remove(id:number){if(!confirm("Vil du slette denne skemaltime?"))return;const{error}=await supabase.from("schedule_entries").delete().eq("id",id);setMsg(error?error.message:"Skematimen er slettet.");if(!error)await load()}
 if(!ready)return <main style={{padding:50}}>Henter skema…</main>;const shown=entries.filter(x=>x.class_id===Number(classId));
 return <main style={{minHeight:"100vh",background:"#f5f2ea",color:"#26342e"}}><header style={{background:"#486b59",color:"white",padding:"18px 6vw"}}><div style={{maxWidth:1100,margin:"auto",display:"flex",justifyContent:"space-between"}}><strong style={{fontSize:22}}>Administration · Skemaer</strong><Link href="/admin" style={{color:"white"}}>← Administration</Link></div></header><section style={{maxWidth:1100,margin:"auto",padding:"42px 24px"}}><p className="eyebrow">SKEMA</p><h1 style={{fontFamily:"Georgia,serif",fontSize:40}}>Klassernes skema</h1><p style={{color:"#687068"}}>Vælg klasse og lærer blandt dem, der allerede er oprettet i administrationen.</p>{msg&&<div style={{padding:12,background:"#e7eee9",borderRadius:9,margin:"18px 0"}}>{msg}</div>}<form onSubmit={add} style={{background:"white",padding:22,border:"1px solid #ddd9d0",borderRadius:14,display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:10}}><select value={classId} onChange={e=>setClassId(e.target.value?Number(e.target.value):"")}><option value="">Vælg klasse</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select value={teacher} onChange={e=>setTeacher(e.target.value)}><option value="">Vælg lærer</option>{teachers.map(t=><option key={t.id} value={t.email}>{t.email}</option>)}</select><select value={weekday} onChange={e=>setWeekday(Number(e.target.value))}>{days.map((d,i)=><option key={d} value={i+1}>{d}</option>)}</select><input type="time" value={start} onChange={e=>setStart(e.target.value)}/><input type="time" value={end} onChange={e=>setEnd(e.target.value)}/><input value={subject} onChange={e=>setSubject(e.target.value)} placeholder="Fag"/><input value={room} onChange={e=>setRoom(e.target.value)} placeholder="Lokale (valgfrit)"/><button type="submit" disabled={!classes.length||!teachers.length}>+ Tilføj skemaltime</button></form>{!classes.length&&<p>Der er ingen klasser endnu. Opret dem under Brugere & klasser.</p>}{!teachers.length&&<p>Der er ingen brugere med lærerrollen endnu. Tildel rollen Lærer under Brugere & klasser.</p>}<div style={{marginTop:28,display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))",gap:14}}>{days.map((d,i)=><section key={d} style={{background:"white",border:"1px solid #ddd9d0",borderRadius:12,padding:16}}><h2 style={{fontFamily:"Georgia,serif",fontSize:20}}>{d}</h2>{shown.filter(x=>x.weekday===i+1).map(x=><div key={x.id} style={{borderTop:"1px solid #eee",padding:"10px 0"}}><strong>{x.start_time.slice(0,5)}–{x.end_time.slice(0,5)} · {x.subject}</strong><small style={{display:"block",color:"#777"}}>{[x.teacher,x.room].filter(Boolean).join(" · ")}</small><button type="button" onClick={()=>remove(x.id)} style={{marginTop:6,fontSize:11}}>Slet</button></div>)}{!shown.some(x=>x.weekday===i+1)&&<small style={{color:"#888"}}>Ingen timer</small>}</section>)}</div></section></main>
}