"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {supabase} from "../../lib/supabase";

type Task={task_key:string;source:"meeting"|"board"|"personal"|"staff";action_id:number;context_id:number|null;title:string;description:string|null;due_date:string|null;completed:boolean;context_title:string|null;context_type:string|null;starts_at:string|null;can_open_context:boolean};

export default function MyTasks(){
 const[ready,setReady]=useState(false),[tasks,setTasks]=useState<Task[]>([]),[showDone,setShowDone]=useState(false),[error,setError]=useState(""),[busy,setBusy]=useState<string|null>(null);
 const[title,setTitle]=useState(""),[description,setDescription]=useState(""),[dueDate,setDueDate]=useState(""),[creating,setCreating]=useState(false),[showCreate,setShowCreate]=useState(false);
 async function load(){const{data,error:e}=await supabase.rpc("my_action_inbox",{p_include_completed:true});if(e){setError(e.message);setTasks([])}else{setError("");setTasks((data||[]) as Task[])}}
 useEffect(()=>{(async()=>{const{data}=await supabase.auth.getSession();if(!data.session){window.location.href="/?teacher=1";return}await load();setReady(true)})()},[]);
 async function toggle(t:Task){setBusy(t.task_key);setError("");const{error:e}=await supabase.rpc("set_my_action_completed",{p_source:t.source,p_action_id:t.action_id,p_completed:!t.completed});if(e)setError(e.message);else await load();setBusy(null)}
 async function createTask(){if(!title.trim()||creating)return;setCreating(true);setError("");const{error:e}=await supabase.rpc("create_personal_task",{p_title:title.trim(),p_description:description.trim()||null,p_due_date:dueDate||null});if(e)setError(e.message);else{setTitle("");setDescription("");setDueDate("");setShowCreate(false);await load()}setCreating(false)}
 async function removeTask(t:Task){if(t.source!=="personal"||busy)return;if(!confirm("Slet denne huskeopgave?"))return;setBusy(t.task_key);setError("");const{error:e}=await supabase.rpc("delete_personal_task",{p_task_id:t.action_id});if(e)setError(e.message);else await load();setBusy(null)}
 function contextLink(t:Task){return t.source==="board"?`/board/meetings#board-meeting-${t.context_id}`:`/calendar/meeting/${t.context_id}`}
 function sourceLabel(t:Task){if(t.source==="personal")return"Oprettet af dig";if(t.source==="staff")return"Tildelt af ledelsen";return t.source==="board"?"Tildelt fra bestyrelsen":"Tildelt fra et møde"}
 const shown=useMemo(()=>tasks.filter(t=>showDone||!t.completed),[tasks,showDone]);
 if(!ready)return <main style={{padding:50}}>Henter dine opgaver…</main>;
 return <main style={{minHeight:"100vh",background:"#f5f3ee",color:"#26342e"}}><header style={{background:"#243d33",color:"white",padding:"22px 30px"}}><div style={{maxWidth:900,margin:"auto",display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,flexWrap:"wrap"}}><div><small style={{opacity:.7,fontWeight:900}}>LÆRERVÆRELSET</small><h1 style={{fontFamily:"Georgia,serif",margin:"4px 0"}}>Mine opgaver</h1></div><div style={{display:"flex",gap:8}}><Link href="/calendar" style={nav}>Kalender</Link><Link href="/teacher-room" style={nav}>Lærerværelset</Link></div></div></header><section style={{maxWidth:900,margin:"auto",padding:"38px 24px 70px"}}>
  <div style={{display:"flex",justifyContent:"space-between",alignItems:"end",gap:15,flexWrap:"wrap"}}><div><p style={eyebrow}>OPGAVER & OPFØLGNING</p><h2 style={{fontFamily:"Georgia,serif",fontSize:32,margin:"5px 0"}}>Det, du skal følge op på</h2><p style={{color:"#707670",maxWidth:650,lineHeight:1.5,margin:"6px 0 0"}}>Her samles dine egne huskeopgaver, opgaver fra møder og bestyrelse samt opgaver, ledelsen har tildelt dig.</p></div><button onClick={()=>setShowCreate(v=>!v)} style={primary}>{showCreate?"Luk":"+ Ny huskeopgave"}</button></div>
  {showCreate&&<section style={{...card,marginTop:18,background:"#eef2ed"}}><div style={{display:"grid",gap:10}}><label style={label}>Hvad skal du huske?<input autoFocus value={title} onChange={e=>setTitle(e.target.value)} placeholder="Fx Ring til forælder, bestil bøger eller send referat" style={field}/></label><label style={label}>Note <span style={{fontWeight:500}}>(valgfri)</span><textarea value={description} onChange={e=>setDescription(e.target.value)} rows={3} placeholder="Skriv evt. lidt mere…" style={field}/></label><label style={{...label,maxWidth:260}}>Deadline <span style={{fontWeight:500}}>(valgfri)</span><input type="date" value={dueDate} onChange={e=>setDueDate(e.target.value)} style={field}/></label><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><button disabled={!title.trim()||creating} onClick={createTask} style={{...primary,opacity:!title.trim()||creating?.55:1}}>{creating?"Gemmer…":"Gem huskeopgave"}</button><button onClick={()=>{setShowCreate(false);setTitle("");setDescription("");setDueDate("")}} style={secondary}>Annullér</button></div></div></section>}
  <div style={{display:"flex",justifyContent:"flex-end",marginTop:18}}><label style={{fontWeight:800,color:"#657169"}}><input type="checkbox" checked={showDone} onChange={e=>setShowDone(e.target.checked)} style={{marginRight:7}}/>Vis udførte</label></div>
  {error&&<div style={{...card,marginTop:14,background:"#fff3cd",color:"#765b29"}}>Dine opgaver kunne ikke hentes eller gemmes: {error}</div>}
  {shown.length===0&&!error?<div style={{...card,marginTop:14}}><strong>Du har ingen åbne opgaver.</strong><p style={{color:"#707670",marginBottom:0}}>Når der kommer noget, der kræver din handling, lander det her.</p></div>:<div style={{display:"grid",gap:11,marginTop:14}}>{shown.map(t=>{const overdue=!!t.due_date&&!t.completed&&t.due_date<today();return <div key={t.task_key} style={{...card,opacity:t.completed?0.65:1}}><div style={{display:"flex",gap:12,alignItems:"start"}}><button onClick={()=>toggle(t)} disabled={busy===t.task_key} aria-label={t.completed?"Markér som ikke udført":"Markér som udført"} style={check}>{busy===t.task_key?"…":t.completed?"✓":""}</button><div style={{flex:1,minWidth:0}}><strong style={{fontSize:17,textDecoration:t.completed?"line-through":"none"}}>{t.title}</strong>{t.description&&<p style={{color:"#707670",margin:"6px 0"}}>{t.description}</p>}<div style={{display:"flex",gap:10,flexWrap:"wrap",marginTop:8,fontSize:13}}>{t.due_date&&<span style={{fontWeight:800,color:overdue?"#a44438":"#657169"}}>{overdue?"Overskredet · ":"Deadline · "}{new Date(t.due_date+"T12:00").toLocaleDateString("da-DK")}</span>}{t.can_open_context&&t.context_title?<Link href={contextLink(t)} style={{color:"#486b59",fontWeight:800,textDecoration:"none"}}>{t.context_type||"Møde"} · {t.context_title} →</Link>:<span style={{color:t.source==="staff"?"#365044":"#7b817c",fontWeight:t.source==="staff"?850:500}}>{sourceLabel(t)}</span>}</div></div>{t.source==="personal"&&<button onClick={()=>removeTask(t)} disabled={busy===t.task_key} style={deleteButton}>Slet</button>}</div></div>})}</div>}
 </section></main>
}
const today=()=>{const d=new Date();return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`};
const nav:React.CSSProperties={color:"white",textDecoration:"none",fontWeight:800,border:"1px solid rgba(255,255,255,.25)",padding:"9px 11px",borderRadius:8};
const card:React.CSSProperties={background:"white",border:"1px solid #ddd9d0",borderRadius:13,padding:"17px 18px"};
const eyebrow:React.CSSProperties={fontSize:11,fontWeight:900,letterSpacing:1.3,color:"#718077",margin:0};
const check:React.CSSProperties={width:28,height:28,borderRadius:7,border:"2px solid #486b59",background:"white",color:"#486b59",fontWeight:900,cursor:"pointer",flex:"0 0 auto"};
const primary:React.CSSProperties={border:0,borderRadius:9,padding:"10px 14px",background:"#365044",color:"white",fontWeight:900,cursor:"pointer"};
const secondary:React.CSSProperties={border:"1px solid #cbc7be",borderRadius:9,padding:"9px 12px",background:"white",color:"#365044",fontWeight:850,cursor:"pointer"};
const deleteButton:React.CSSProperties={...secondary,color:"#8a3e36",fontSize:11,padding:"6px 8px"};
const label:React.CSSProperties={fontWeight:850,fontSize:13};
const field:React.CSSProperties={display:"block",width:"100%",boxSizing:"border-box",marginTop:6,padding:"10px 11px",border:"1px solid #cbc7be",borderRadius:8,font:"inherit",background:"white"};
