"use client";

import { useEffect, useState } from "react";
import { supabase } from "../../lib/supabase";
import {hasRole} from "../../lib/roles";

type Student={id:number;name:string;access_code:string|null;class_id:number};
type ClassRow={id:number;name:string};
type TeacherClass={teacher_id:string;class_id:number};
const makeCode=()=>{const chars="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";return Array.from({length:6},()=>chars[Math.floor(Math.random()*chars.length)]).join("")};

export default function StudentsPage(){
 const[ready,setReady]=useState(false),[classes,setClasses]=useState<ClassRow[]>([]),[classId,setClassId]=useState<number|"">(""),[students,setStudents]=useState<Student[]>([]),[name,setName]=useState("");
 async function load(){const{data:s}=await supabase.auth.getSession();const user=s.session?.user;if(!user){window.location.href="/?teacher=1";return}const[{data:c},{data:st},{data:tc}]=await Promise.all([supabase.from("classes").select("id,name").order("id"),supabase.from("students").select("id,name,access_code,class_id").order("id"),supabase.from("teacher_classes").select("teacher_id,class_id").eq("teacher_id",user.id)]);const allClasses=(c||[]) as ClassRow[];const assigned=new Set(((tc||[]) as TeacherClass[]).map(x=>x.class_id));const cs=hasRole(user,"admin")?allClasses:allClasses.filter(x=>assigned.has(x.id));setClasses(cs);setStudents((st||[]).filter(x=>hasRole(user,"admin")||assigned.has(x.class_id)));const requested=Number(new URLSearchParams(window.location.search).get("class"));setClassId(cs.some(x=>x.id===requested)?requested:(cs[0]?.id||""));setReady(true)}
 useEffect(()=>{load()},[]);
 const shown=students.filter(s=>s.class_id===classId);
 async function add(){if(!name.trim()||!classId)return;let code=makeCode();let r=await supabase.from("students").insert({name:name.trim(),class_id:classId,access_code:code}).select("id,name,access_code,class_id").single();if(r.error?.code==="23505"){code=makeCode();r=await supabase.from("students").insert({name:name.trim(),class_id:classId,access_code:code}).select("id,name,access_code,class_id").single()}if(r.error)return alert(r.error.message);setStudents(v=>[...v,r.data]);setName("")}
 async function newCode(s:Student){let code=makeCode();const{data,error}=await supabase.from("students").update({access_code:code}).eq("id",s.id).select("access_code").single();if(error)return alert(error.message);setStudents(v=>v.map(x=>x.id===s.id?{...x,access_code:data.access_code}:x))}
 async function remove(s:Student){if(!confirm(`Slet ${s.name}?\n\nElevens gemte arbejde og feedback slettes permanent.`))return;await supabase.from("feedback").delete().eq("student_id",s.id);const d=await supabase.from("drafts").delete().eq("student_id",s.id);if(d.error)return alert(d.error.message);const r=await supabase.from("students").delete().eq("id",s.id);if(r.error)return alert(r.error.message);setStudents(v=>v.filter(x=>x.id!==s.id))}
 async function copy(code:string){try{await navigator.clipboard.writeText(code)}catch{prompt("Kopiér elevkoden:",code)}}
 if(!ready)return <main style={{padding:50}}>Henter elever…</main>;
 return <main style={{minHeight:"100vh",background:"#f5f3ee",padding:"42px 24px 80px"}}><section style={{maxWidth:1000,margin:"0 auto"}}><a href="/teacher-dashboard" style={{color:"#526b60",fontWeight:800,textDecoration:"none"}}>← Til lærerforsiden</a><p className="eyebrow" style={{marginTop:38}}>ELEVER</p><h1 style={{marginBottom:8}}>{classes.find(c=>c.id===classId)?.name||"Mine klasser"}</h1><p style={{color:"#777",marginTop:0}}>Elever i de klasser, du er tilknyttet.</p>{classes.length===0?<div className="card" style={{padding:26,marginTop:28}}><strong>Du er endnu ikke tilknyttet en klasse.</strong><p style={{color:"#777"}}>En administrator kan tilknytte dig under Lærere & klasser.</p></div>:<div className="card" style={{padding:26,marginTop:28}}><label style={{fontWeight:800}}>Klasse<select value={classId} onChange={e=>setClassId(Number(e.target.value))} style={{display:"block",marginTop:8,padding:11,border:"1px solid #d8d5cd",borderRadius:8,minWidth:240}}>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><div style={{marginTop:26}}>{shown.map(s=><div key={s.id} style={{display:"flex",alignItems:"center",gap:12,padding:"16px 0",borderBottom:"1px solid #ebe7de",flexWrap:"wrap"}}><div style={{width:38,height:38,borderRadius:99,background:"#eee8da",display:"grid",placeItems:"center",fontFamily:"Georgia,serif"}}>{s.name[0]}</div><strong style={{minWidth:130}}>{s.name}</strong><code style={{background:"#f2efe8",padding:"7px 10px",borderRadius:7,fontWeight:800,letterSpacing:1}}>{s.access_code||"Ingen kode"}</code>{s.access_code&&<button onClick={()=>copy(s.access_code!)}>Kopiér</button>}<button onClick={()=>newCode(s)}>Ny kode</button><button onClick={()=>remove(s)} style={{marginLeft:"auto",color:"#9b3b32"}}>Slet</button></div>)}</div><div style={{display:"flex",gap:10,marginTop:24}}><input value={name} onChange={e=>setName(e.target.value)} placeholder="Elevens navn" style={{flex:1,padding:12,border:"1px solid #d8d5cd",borderRadius:8}}/><button className="primary" onClick={add} style={{width:"auto",margin:0}}>Tilføj elev</button></div></div>}</section></main>
}