create table public.lesson_instances (
  id bigint generated by default as identity primary key,
  school_id bigint not null references public.schools(id) on delete cascade,
  schedule_entry_id bigint not null references public.schedule_entries(id) on delete cascade,
  lesson_date date not null,
  learning_goals text null,
  plan text null,
  materials jsonb not null default '[]'::jsonb,
  status text not null default 'planned' check (status in ('planned','active','completed','cancelled')),
  started_at timestamptz null,
  ended_at timestamptz null,
  carry_forward_to date null,
  carry_forward_note text null,
  created_by uuid not null references auth.users(id),
  updated_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint lesson_instances_schedule_date_key unique (schedule_entry_id, lesson_date),
  constraint lesson_instances_materials_array check (jsonb_typeof(materials) = 'array'),
  constraint lesson_instances_time_order check (ended_at is null or started_at is null or ended_at >= started_at)
);

create index idx_lesson_instances_school_date on public.lesson_instances(school_id, lesson_date);
create index idx_lesson_instances_schedule_entry on public.lesson_instances(schedule_entry_id);
create index idx_lesson_instances_created_by on public.lesson_instances(created_by);
create index idx_lesson_instances_updated_by on public.lesson_instances(updated_by);

create or replace function private.sync_lesson_instance_context()
returns trigger
language plpgsql
security definer
set search_path = 'public','private'
as $$
declare
  v_school_id bigint;
  v_weekday integer;
  v_uid uuid;
begin
  select c.school_id, se.weekday
    into v_school_id, v_weekday
  from public.schedule_entries se
  join public.classes c on c.id = se.class_id
  where se.id = new.schedule_entry_id;

  if v_school_id is null then
    raise exception 'Lesson schedule entry is not linked to a school';
  end if;

  if extract(isodow from new.lesson_date)::integer <> v_weekday then
    raise exception 'Lesson date does not match the schedule weekday';
  end if;

  v_uid := auth.uid();
  if v_uid is null then
    raise exception 'Authenticated user required';
  end if;

  new.school_id := v_school_id;
  new.updated_by := v_uid;
  new.updated_at := now();

  if tg_op = 'INSERT' then
    new.created_by := v_uid;
    new.created_at := coalesce(new.created_at, now());
  end if;

  return new;
end;
$$;

revoke all on function private.sync_lesson_instance_context() from public, anon, authenticated;

drop trigger if exists lesson_instances_sync_context on public.lesson_instances;
create trigger lesson_instances_sync_context
before insert or update on public.lesson_instances
for each row execute function private.sync_lesson_instance_context();

alter table public.lesson_instances enable row level security;
revoke all on table public.lesson_instances from anon, authenticated;
grant select, insert, update, delete on table public.lesson_instances to authenticated;
grant usage, select on sequence public.lesson_instances_id_seq to authenticated;

create policy "assigned staff read lesson instances"
on public.lesson_instances
for select
to authenticated
using (
  public.has_school_role(school_id, 'admin')
  or exists (
    select 1 from public.schedule_teachers st
    where st.schedule_entry_id = lesson_instances.schedule_entry_id
      and st.teacher_id = (select auth.uid())
  )
  or exists (
    select 1 from public.substitute_assignments sa
    where sa.schedule_entry_id = lesson_instances.schedule_entry_id
      and sa.assignment_date = lesson_instances.lesson_date
      and sa.substitute_teacher_id = (select auth.uid())
  )
);

create policy "assigned teachers create lesson instances"
on public.lesson_instances
for insert
to authenticated
with check (
  public.has_school_role(school_id, 'admin')
  or exists (
    select 1 from public.schedule_teachers st
    where st.schedule_entry_id = lesson_instances.schedule_entry_id
      and st.teacher_id = (select auth.uid())
  )
);

create policy "assigned teachers update lesson instances"
on public.lesson_instances
for update
to authenticated
using (
  public.has_school_role(school_id, 'admin')
  or exists (
    select 1 from public.schedule_teachers st
    where st.schedule_entry_id = lesson_instances.schedule_entry_id
      and st.teacher_id = (select auth.uid())
  )
)
with check (
  public.has_school_role(school_id, 'admin')
  or exists (
    select 1 from public.schedule_teachers st
    where st.schedule_entry_id = lesson_instances.schedule_entry_id
      and st.teacher_id = (select auth.uid())
  )
);

create policy "assigned teachers delete lesson instances"
on public.lesson_instances
for delete
to authenticated
using (
  public.has_school_role(school_id, 'admin')
  or exists (
    select 1 from public.schedule_teachers st
    where st.schedule_entry_id = lesson_instances.schedule_entry_id
      and st.teacher_id = (select auth.uid())
  )
);
