create table if not exists public.staff_tasks (
  id bigint generated by default as identity primary key,
  school_id bigint not null references public.schools(id) on delete cascade,
  title text not null check (length(trim(title)) between 1 and 240),
  description text null,
  due_date date null,
  created_by uuid not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.staff_task_assignees (
  task_id bigint not null references public.staff_tasks(id) on delete cascade,
  user_id uuid not null,
  completed boolean not null default false,
  completed_at timestamptz null,
  created_at timestamptz not null default now(),
  primary key (task_id,user_id)
);

create index if not exists staff_tasks_school_due_idx on public.staff_tasks(school_id,due_date,id);
create index if not exists staff_task_assignees_user_idx on public.staff_task_assignees(user_id,completed,task_id);

alter table public.staff_tasks enable row level security;
alter table public.staff_task_assignees enable row level security;

create or replace function private.is_staff_task_assignee(p_task_id bigint,p_user_id uuid)
returns boolean
language sql
stable
security definer
set search_path=public,private
as $$
  select exists(
    select 1 from public.staff_task_assignees a
    where a.task_id=p_task_id and a.user_id=p_user_id
  );
$$;

create or replace function private.staff_task_school_id(p_task_id bigint)
returns bigint
language sql
stable
security definer
set search_path=public,private
as $$
  select t.school_id from public.staff_tasks t where t.id=p_task_id;
$$;

revoke all on function private.is_staff_task_assignee(bigint,uuid) from public,anon;
revoke all on function private.staff_task_school_id(bigint) from public,anon;
grant execute on function private.is_staff_task_assignee(bigint,uuid) to authenticated;
grant execute on function private.staff_task_school_id(bigint) to authenticated;

create policy staff_tasks_read on public.staff_tasks
for select to authenticated
using (
  public.has_school_role(school_id,'admin')
  or public.has_school_role(school_id,'leader')
  or private.is_staff_task_assignee(id,auth.uid())
);

create policy staff_task_assignees_read on public.staff_task_assignees
for select to authenticated
using (
  user_id=auth.uid()
  or public.has_school_role(private.staff_task_school_id(task_id),'admin')
  or public.has_school_role(private.staff_task_school_id(task_id),'leader')
);

revoke all on public.staff_tasks from anon;
revoke all on public.staff_task_assignees from anon;
grant select on public.staff_tasks to authenticated;
grant select on public.staff_task_assignees to authenticated;

create or replace function private.create_staff_task_internal(
  p_title text,
  p_description text,
  p_due_date date,
  p_user_ids uuid[]
)
returns bigint
language plpgsql
security definer
set search_path=public,private
as $$
declare
  v_school_id bigint;
  v_task_id bigint;
  v_user_ids uuid[];
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  if length(trim(coalesce(p_title,'')))=0 then raise exception 'Title required'; end if;

  select sm.school_id into v_school_id
  from public.school_memberships sm
  where sm.user_id=auth.uid() and sm.active=true and sm.role in ('admin','leader')
  order by sm.school_id
  limit 1;
  if v_school_id is null then raise exception 'Admin role required'; end if;

  select array_agg(distinct x) into v_user_ids
  from unnest(coalesce(p_user_ids,'{}'::uuid[])) x
  where x is not null;
  if coalesce(cardinality(v_user_ids),0)=0 then raise exception 'Choose at least one staff member'; end if;

  if exists(
    select 1 from unnest(v_user_ids) u
    where not exists(
      select 1 from public.school_memberships sm
      where sm.school_id=v_school_id and sm.user_id=u and sm.active=true
        and sm.role in ('teacher','admin','leader')
    )
  ) then raise exception 'All assignees must be active staff at the same school'; end if;

  insert into public.staff_tasks(school_id,title,description,due_date,created_by)
  values(v_school_id,trim(p_title),nullif(trim(coalesce(p_description,'')),''),p_due_date,auth.uid())
  returning id into v_task_id;

  insert into public.staff_task_assignees(task_id,user_id)
  select v_task_id,u from unnest(v_user_ids) u;

  return v_task_id;
end;
$$;

create or replace function public.admin_create_staff_task(
  p_title text,
  p_description text default null,
  p_due_date date default null,
  p_user_ids uuid[] default '{}'
)
returns bigint
language sql
security invoker
set search_path=public,private
as $$
  select private.create_staff_task_internal(p_title,p_description,p_due_date,p_user_ids);
$$;

create or replace function private.delete_staff_task_internal(p_task_id bigint)
returns void
language plpgsql
security definer
set search_path=public,private
as $$
declare v_rows integer;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  delete from public.staff_tasks t
  where t.id=p_task_id
    and (public.has_school_role(t.school_id,'admin') or public.has_school_role(t.school_id,'leader'));
  get diagnostics v_rows=row_count;
  if v_rows<>1 then raise exception 'Task not found or access denied'; end if;
end;
$$;

create or replace function public.admin_delete_staff_task(p_task_id bigint)
returns void
language sql
security invoker
set search_path=public,private
as $$
  select private.delete_staff_task_internal(p_task_id);
$$;

revoke all on function private.create_staff_task_internal(text,text,date,uuid[]) from public,anon;
revoke all on function private.delete_staff_task_internal(bigint) from public,anon;
grant execute on function private.create_staff_task_internal(text,text,date,uuid[]) to authenticated;
grant execute on function private.delete_staff_task_internal(bigint) to authenticated;
revoke all on function public.admin_create_staff_task(text,text,date,uuid[]) from public,anon;
revoke all on function public.admin_delete_staff_task(bigint) from public,anon;
grant execute on function public.admin_create_staff_task(text,text,date,uuid[]) to authenticated;
grant execute on function public.admin_delete_staff_task(bigint) to authenticated;

create or replace function public.my_action_inbox(p_include_completed boolean default false)
returns table(task_key text,source text,action_id bigint,context_id bigint,title text,description text,due_date date,completed boolean,context_title text,context_type text,starts_at timestamptz,can_open_context boolean)
language sql
stable
security definer
set search_path=public,private
as $$
  select task_key,source,action_id,context_id,title,description,due_date,completed,
         context_title,context_type,starts_at,can_open_context
  from (
    select
      'meeting:'||ma.id::text as task_key,
      'meeting'::text as source,
      ma.id as action_id,
      ma.meeting_id as context_id,
      ma.title,
      ma.description,
      ma.due_date,
      ma.completed,
      case when private.can_access_meeting(cm.id) then cm.title else null end as context_title,
      case when private.can_access_meeting(cm.id) then cm.meeting_type else null end as context_type,
      case when private.can_access_meeting(cm.id) then cm.starts_at else null end as starts_at,
      private.can_access_meeting(cm.id) as can_open_context,
      ma.created_at
    from public.meeting_actions ma
    join public.calendar_meetings cm on cm.id=ma.meeting_id
    where ma.responsible_user_id=auth.uid()
      and public.is_school_member(cm.school_id)

    union all

    select
      'board:'||bd.id::text,
      'board'::text,
      bd.id,
      bd.meeting_id,
      bd.decision,
      null::text,
      bd.due_date,
      bd.completed,
      bm.title,
      'Bestyrelsesmøde'::text,
      ((bm.meeting_date+coalesce(bm.start_time,time '00:00')) at time zone 'Europe/Copenhagen'),
      true,
      bd.created_at
    from public.board_decisions bd
    join public.board_meetings bm on bm.id=bd.meeting_id
    where bd.responsible_user_id=auth.uid()
      and exists(
        select 1 from public.school_memberships sm
        where sm.school_id=bm.school_id and sm.user_id=auth.uid()
          and sm.role='board' and sm.active=true
      )

    union all

    select
      'personal:'||pt.id::text,
      'personal'::text,
      pt.id,
      null::bigint,
      pt.title,
      pt.description,
      pt.due_date,
      pt.completed,
      null::text,
      'Egen opgave'::text,
      null::timestamptz,
      false,
      pt.created_at
    from public.personal_tasks pt
    where pt.user_id=auth.uid()
      and public.is_school_member(pt.school_id)

    union all

    select
      'staff:'||st.id::text,
      'staff'::text,
      st.id,
      null::bigint,
      st.title,
      st.description,
      st.due_date,
      a.completed,
      null::text,
      'Tildelt af ledelsen'::text,
      null::timestamptz,
      false,
      st.created_at
    from public.staff_task_assignees a
    join public.staff_tasks st on st.id=a.task_id
    where a.user_id=auth.uid()
      and public.is_school_member(st.school_id)
  ) actions
  where coalesce(p_include_completed,false) or actions.completed=false
  order by due_date asc nulls last,created_at asc;
$$;

create or replace function public.set_my_action_completed(p_source text,p_action_id bigint,p_completed boolean)
returns void
language plpgsql
security definer
set search_path=public,private
as $$
declare v_rows integer;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;

  if p_source='meeting' then
    update public.meeting_actions ma
    set completed=coalesce(p_completed,false),
        completed_at=case when coalesce(p_completed,false) then now() else null end,
        updated_at=now()
    where ma.id=p_action_id and ma.responsible_user_id=auth.uid()
      and exists(select 1 from public.calendar_meetings cm where cm.id=ma.meeting_id and public.is_school_member(cm.school_id));
  elsif p_source='board' then
    update public.board_decisions bd
    set completed=coalesce(p_completed,false)
    where bd.id=p_action_id and bd.responsible_user_id=auth.uid()
      and exists(
        select 1 from public.board_meetings bm
        join public.school_memberships sm on sm.school_id=bm.school_id and sm.user_id=auth.uid() and sm.role='board' and sm.active=true
        where bm.id=bd.meeting_id
      );
  elsif p_source='personal' then
    update public.personal_tasks
    set completed=coalesce(p_completed,false),
        completed_at=case when coalesce(p_completed,false) then now() else null end,
        updated_at=now()
    where id=p_action_id and user_id=auth.uid();
  elsif p_source='staff' then
    update public.staff_task_assignees
    set completed=coalesce(p_completed,false),
        completed_at=case when coalesce(p_completed,false) then now() else null end
    where task_id=p_action_id and user_id=auth.uid();
  else
    raise exception 'Unknown action source';
  end if;

  get diagnostics v_rows=row_count;
  if v_rows<>1 then raise exception 'Handlingen tilhører ikke dig'; end if;
end;
$$;