create table public.lesson_resource_links (
  id bigint generated by default as identity primary key,
  lesson_instance_id bigint not null references public.lesson_instances(id) on delete cascade,
  subject_room_item_id bigint references public.subject_room_items(id) on delete cascade,
  assignment_id bigint references public.assignments(id) on delete cascade,
  position integer not null default 0,
  created_by uuid not null,
  created_at timestamptz not null default now(),
  constraint lesson_resource_links_one_source check (
    ((subject_room_item_id is not null)::integer + (assignment_id is not null)::integer) = 1
  )
);

create index lesson_resource_links_lesson_idx on public.lesson_resource_links(lesson_instance_id);
create index lesson_resource_links_item_idx on public.lesson_resource_links(subject_room_item_id) where subject_room_item_id is not null;
create index lesson_resource_links_assignment_idx on public.lesson_resource_links(assignment_id) where assignment_id is not null;
create unique index lesson_resource_links_unique_item on public.lesson_resource_links(lesson_instance_id,subject_room_item_id) where subject_room_item_id is not null;
create unique index lesson_resource_links_unique_assignment on public.lesson_resource_links(lesson_instance_id,assignment_id) where assignment_id is not null;

create or replace function private.validate_lesson_resource_link()
returns trigger
language plpgsql
security definer
set search_path='public','private'
as $$
declare
  v_lesson_class_id bigint;
  v_resource_class_id bigint;
  v_uid uuid;
begin
  v_uid := auth.uid();
  if v_uid is null then raise exception 'Authenticated user required'; end if;

  select se.class_id into v_lesson_class_id
  from public.lesson_instances li
  join public.schedule_entries se on se.id=li.schedule_entry_id
  where li.id=new.lesson_instance_id;
  if v_lesson_class_id is null then raise exception 'Lesson instance not found'; end if;

  if new.subject_room_item_id is not null then
    select cs.class_id into v_resource_class_id
    from public.subject_room_items sri
    join public.class_subjects cs on cs.id=sri.class_subject_id
    where sri.id=new.subject_room_item_id;
  elsif new.assignment_id is not null then
    select a.class_id into v_resource_class_id
    from public.assignments a where a.id=new.assignment_id;
  else
    raise exception 'A lesson resource source is required';
  end if;

  if v_resource_class_id is null then raise exception 'Lesson resource not found'; end if;
  if v_resource_class_id <> v_lesson_class_id then raise exception 'Lesson resource must belong to the same class as the lesson'; end if;

  if tg_op='INSERT' then
    new.created_by := v_uid;
    new.created_at := coalesce(new.created_at,now());
  end if;
  return new;
end;
$$;

revoke all on function private.validate_lesson_resource_link() from public;

create trigger validate_lesson_resource_link_before_write
before insert or update on public.lesson_resource_links
for each row execute function private.validate_lesson_resource_link();

alter table public.lesson_resource_links enable row level security;

create policy "assigned staff read lesson resource links"
on public.lesson_resource_links for select to authenticated
using (
  exists (
    select 1 from public.lesson_instances li
    where li.id=lesson_resource_links.lesson_instance_id
      and (
        public.has_school_role(li.school_id,'admin')
        or exists (select 1 from public.schedule_teachers st where st.schedule_entry_id=li.schedule_entry_id and st.teacher_id=(select auth.uid()))
        or exists (select 1 from public.substitute_assignments sa where sa.schedule_entry_id=li.schedule_entry_id and sa.assignment_date=li.lesson_date and sa.substitute_teacher_id=(select auth.uid()))
      )
  )
);

create policy "assigned teachers create lesson resource links"
on public.lesson_resource_links for insert to authenticated
with check (
  exists (
    select 1 from public.lesson_instances li
    where li.id=lesson_resource_links.lesson_instance_id
      and (
        public.has_school_role(li.school_id,'admin')
        or exists (select 1 from public.schedule_teachers st where st.schedule_entry_id=li.schedule_entry_id and st.teacher_id=(select auth.uid()))
      )
  )
);

create policy "assigned teachers update lesson resource links"
on public.lesson_resource_links for update to authenticated
using (
  exists (
    select 1 from public.lesson_instances li
    where li.id=lesson_resource_links.lesson_instance_id
      and (
        public.has_school_role(li.school_id,'admin')
        or exists (select 1 from public.schedule_teachers st where st.schedule_entry_id=li.schedule_entry_id and st.teacher_id=(select auth.uid()))
      )
  )
)
with check (
  exists (
    select 1 from public.lesson_instances li
    where li.id=lesson_resource_links.lesson_instance_id
      and (
        public.has_school_role(li.school_id,'admin')
        or exists (select 1 from public.schedule_teachers st where st.schedule_entry_id=li.schedule_entry_id and st.teacher_id=(select auth.uid()))
      )
  )
);

create policy "assigned teachers delete lesson resource links"
on public.lesson_resource_links for delete to authenticated
using (
  exists (
    select 1 from public.lesson_instances li
    where li.id=lesson_resource_links.lesson_instance_id
      and (
        public.has_school_role(li.school_id,'admin')
        or exists (select 1 from public.schedule_teachers st where st.schedule_entry_id=li.schedule_entry_id and st.teacher_id=(select auth.uid()))
      )
  )
);

revoke all on table public.lesson_resource_links from anon;
grant select,insert,update,delete on table public.lesson_resource_links to authenticated;
grant usage,select on sequence public.lesson_resource_links_id_seq to authenticated;
