create table public.subject_units (
  id bigint generated by default as identity primary key,
  school_id bigint not null references public.schools(id) on delete cascade,
  class_subject_id bigint not null references public.class_subjects(id) on delete cascade,
  title text not null,
  driving_question text null,
  summary text null,
  learning_goals text[] not null default '{}'::text[],
  start_date date null,
  end_date date null,
  status text not null default 'planned' check (status in ('planned','active','completed','archived')),
  visible_to_students boolean not null default false,
  visible_to_guardians boolean not null default false,
  position integer not null default 0,
  created_by uuid not null references auth.users(id),
  updated_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint subject_units_title_not_blank check (nullif(trim(title),'') is not null),
  constraint subject_units_date_order check (end_date is null or start_date is null or end_date >= start_date)
);

create table public.subject_unit_assignments (
  subject_unit_id bigint not null references public.subject_units(id) on delete cascade,
  assignment_id bigint not null references public.assignments(id) on delete cascade,
  position integer not null default 0,
  created_at timestamptz not null default now(),
  primary key (subject_unit_id, assignment_id)
);

create index subject_units_school_idx on public.subject_units(school_id);
create index subject_units_class_subject_dates_idx on public.subject_units(class_subject_id,start_date,end_date,position);
create index subject_units_created_by_idx on public.subject_units(created_by);
create index subject_units_updated_by_idx on public.subject_units(updated_by);
create index subject_unit_assignments_assignment_idx on public.subject_unit_assignments(assignment_id);

create or replace function private.sync_subject_unit_context()
returns trigger language plpgsql security definer set search_path='public','private' as $$
declare v_school_id bigint; v_uid uuid;
begin
  select cs.school_id into v_school_id from public.class_subjects cs where cs.id=new.class_subject_id and cs.active=true;
  if v_school_id is null then raise exception 'Subject room does not exist or is inactive'; end if;
  v_uid:=auth.uid(); if v_uid is null then raise exception 'Authenticated user required'; end if;
  new.school_id:=v_school_id; new.updated_by:=v_uid; new.updated_at:=now();
  if tg_op='INSERT' then new.created_by:=v_uid; new.created_at:=coalesce(new.created_at,now()); end if;
  return new;
end;$$;
revoke all on function private.sync_subject_unit_context() from public,anon,authenticated;
create trigger subject_units_sync_context before insert or update on public.subject_units for each row execute function private.sync_subject_unit_context();

create or replace function private.validate_subject_unit_assignment()
returns trigger language plpgsql security definer set search_path='public','private' as $$
declare v_unit_room bigint; v_assignment_room bigint;
begin
  select u.class_subject_id into v_unit_room from public.subject_units u where u.id=new.subject_unit_id;
  select a.class_subject_id into v_assignment_room from public.assignments a where a.id=new.assignment_id;
  if v_unit_room is null or v_assignment_room is null or v_unit_room<>v_assignment_room then raise exception 'Assignment and unit must belong to the same subject room'; end if;
  return new;
end;$$;
revoke all on function private.validate_subject_unit_assignment() from public,anon,authenticated;
create trigger subject_unit_assignments_validate before insert or update on public.subject_unit_assignments for each row execute function private.validate_subject_unit_assignment();

alter table public.subject_units enable row level security;
alter table public.subject_unit_assignments enable row level security;
revoke all on public.subject_units,public.subject_unit_assignments from anon,authenticated;
grant select,insert,update,delete on public.subject_units,public.subject_unit_assignments to authenticated;
grant usage,select on sequence public.subject_units_id_seq to authenticated;

create policy "school staff read subject units" on public.subject_units for select to authenticated using (public.is_school_staff(school_id));
create policy "subject teachers create units" on public.subject_units for insert to authenticated with check (
  exists(select 1 from public.class_subjects cs where cs.id=class_subject_id and (public.has_school_role(cs.school_id,'admin') or exists(select 1 from public.class_subject_teachers cst join public.school_memberships sm on sm.user_id=cst.user_id and sm.school_id=cs.school_id and sm.role='teacher' and sm.active=true where cst.class_subject_id=cs.id and cst.user_id=(select auth.uid()))))
);
create policy "subject teachers update units" on public.subject_units for update to authenticated using (
  exists(select 1 from public.class_subjects cs where cs.id=class_subject_id and (public.has_school_role(cs.school_id,'admin') or exists(select 1 from public.class_subject_teachers cst join public.school_memberships sm on sm.user_id=cst.user_id and sm.school_id=cs.school_id and sm.role='teacher' and sm.active=true where cst.class_subject_id=cs.id and cst.user_id=(select auth.uid()))))
) with check (
  exists(select 1 from public.class_subjects cs where cs.id=class_subject_id and (public.has_school_role(cs.school_id,'admin') or exists(select 1 from public.class_subject_teachers cst join public.school_memberships sm on sm.user_id=cst.user_id and sm.school_id=cs.school_id and sm.role='teacher' and sm.active=true where cst.class_subject_id=cs.id and cst.user_id=(select auth.uid()))))
);
create policy "subject teachers delete units" on public.subject_units for delete to authenticated using (
  exists(select 1 from public.class_subjects cs where cs.id=class_subject_id and (public.has_school_role(cs.school_id,'admin') or exists(select 1 from public.class_subject_teachers cst join public.school_memberships sm on sm.user_id=cst.user_id and sm.school_id=cs.school_id and sm.role='teacher' and sm.active=true where cst.class_subject_id=cs.id and cst.user_id=(select auth.uid()))))
);

create policy "school staff read unit assignments" on public.subject_unit_assignments for select to authenticated using (exists(select 1 from public.subject_units u where u.id=subject_unit_id and public.is_school_staff(u.school_id)));
create policy "subject teachers link unit assignments" on public.subject_unit_assignments for insert to authenticated with check (
  exists(select 1 from public.subject_units u join public.assignments a on a.id=assignment_id and a.class_subject_id=u.class_subject_id join public.class_subjects cs on cs.id=u.class_subject_id where u.id=subject_unit_id and (public.has_school_role(cs.school_id,'admin') or exists(select 1 from public.class_subject_teachers cst join public.school_memberships sm on sm.user_id=cst.user_id and sm.school_id=cs.school_id and sm.role='teacher' and sm.active=true where cst.class_subject_id=cs.id and cst.user_id=(select auth.uid()))))
);
create policy "subject teachers update unit assignments" on public.subject_unit_assignments for update to authenticated using (
  exists(select 1 from public.subject_units u join public.class_subjects cs on cs.id=u.class_subject_id where u.id=subject_unit_id and (public.has_school_role(cs.school_id,'admin') or exists(select 1 from public.class_subject_teachers cst join public.school_memberships sm on sm.user_id=cst.user_id and sm.school_id=cs.school_id and sm.role='teacher' and sm.active=true where cst.class_subject_id=cs.id and cst.user_id=(select auth.uid()))))
) with check (
  exists(select 1 from public.subject_units u join public.assignments a on a.id=assignment_id and a.class_subject_id=u.class_subject_id join public.class_subjects cs on cs.id=u.class_subject_id where u.id=subject_unit_id and (public.has_school_role(cs.school_id,'admin') or exists(select 1 from public.class_subject_teachers cst join public.school_memberships sm on sm.user_id=cst.user_id and sm.school_id=cs.school_id and sm.role='teacher' and sm.active=true where cst.class_subject_id=cs.id and cst.user_id=(select auth.uid()))))
);
create policy "subject teachers unlink unit assignments" on public.subject_unit_assignments for delete to authenticated using (
  exists(select 1 from public.subject_units u join public.class_subjects cs on cs.id=u.class_subject_id where u.id=subject_unit_id and (public.has_school_role(cs.school_id,'admin') or exists(select 1 from public.class_subject_teachers cst join public.school_memberships sm on sm.user_id=cst.user_id and sm.school_id=cs.school_id and sm.role='teacher' and sm.active=true where cst.class_subject_id=cs.id and cst.user_id=(select auth.uid()))))
);
