create table public.subjects (
  id bigint generated by default as identity primary key,
  school_id bigint not null references public.schools(id) on delete cascade,
  name text not null,
  slug text not null,
  active boolean not null default true,
  created_by uuid null references auth.users(id),
  created_at timestamptz not null default now(),
  unique (school_id, slug)
);

create table public.class_subjects (
  id bigint generated by default as identity primary key,
  school_id bigint not null references public.schools(id) on delete cascade,
  class_id bigint not null references public.classes(id) on delete cascade,
  subject_id bigint not null references public.subjects(id) on delete restrict,
  title text null,
  intro text null,
  active boolean not null default true,
  created_by uuid null references auth.users(id),
  updated_by uuid null references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (class_id, subject_id)
);

create table public.class_subject_teachers (
  class_subject_id bigint not null references public.class_subjects(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (class_subject_id, user_id)
);

create table public.subject_room_items (
  id bigint generated by default as identity primary key,
  class_subject_id bigint not null references public.class_subjects(id) on delete cascade,
  item_type text not null check (item_type in ('post','section','link','material','note')),
  title text null,
  body text null,
  url text null,
  position integer not null default 0,
  visible_to_students boolean not null default true,
  created_by uuid not null references auth.users(id),
  updated_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint subject_room_items_content check (title is not null or body is not null or url is not null)
);

create index idx_subjects_school on public.subjects(school_id);
create index idx_class_subjects_school on public.class_subjects(school_id);
create index idx_class_subjects_class on public.class_subjects(class_id);
create index idx_class_subjects_subject on public.class_subjects(subject_id);
create index idx_class_subject_teachers_user on public.class_subject_teachers(user_id);
create index idx_subject_room_items_room_position on public.subject_room_items(class_subject_id, position, created_at);
create index idx_subject_room_items_created_by on public.subject_room_items(created_by);
create index idx_subject_room_items_updated_by on public.subject_room_items(updated_by);

create or replace function public.can_edit_class_subject(p_class_subject_id bigint)
returns boolean
language sql
stable
security definer
set search_path='public'
as $$
  select exists (
    select 1
    from public.class_subjects cs
    where cs.id=p_class_subject_id
      and (
        public.has_school_role(cs.school_id,'admin')
        or exists (
          select 1
          from public.class_subject_teachers cst
          join public.school_memberships sm
            on sm.user_id=cst.user_id
           and sm.school_id=cs.school_id
           and sm.role='teacher'
           and sm.active=true
          where cst.class_subject_id=cs.id
            and cst.user_id=auth.uid()
        )
      )
  );
$$;

create or replace function private.sync_class_subject_context()
returns trigger
language plpgsql
security definer
set search_path='public','private'
as $$
declare
  v_school bigint;
  v_subject_school bigint;
  v_uid uuid;
begin
  select school_id into v_school from public.classes where id=new.class_id;
  select school_id into v_subject_school from public.subjects where id=new.subject_id;
  if v_school is null or v_subject_school is null or v_school<>v_subject_school then
    raise exception 'Class and subject must belong to the same school';
  end if;
  new.school_id:=v_school;
  v_uid:=auth.uid();
  if v_uid is not null then
    new.updated_by:=v_uid;
    new.updated_at:=now();
    if tg_op='INSERT' then new.created_by:=coalesce(new.created_by,v_uid); end if;
  end if;
  return new;
end;
$$;
revoke all on function private.sync_class_subject_context() from public,anon,authenticated;
create trigger class_subjects_sync_context before insert or update on public.class_subjects for each row execute function private.sync_class_subject_context();

create or replace function private.sync_subject_room_item_context()
returns trigger
language plpgsql
security definer
set search_path='public','private'
as $$
declare v_uid uuid;
begin
  v_uid:=auth.uid();
  if v_uid is null then raise exception 'Authenticated user required'; end if;
  new.updated_by:=v_uid;
  new.updated_at:=now();
  if tg_op='INSERT' then new.created_by:=v_uid; end if;
  return new;
end;
$$;
revoke all on function private.sync_subject_room_item_context() from public,anon,authenticated;
create trigger subject_room_items_sync_context before insert or update on public.subject_room_items for each row execute function private.sync_subject_room_item_context();

create or replace function private.add_class_subject_creator()
returns trigger
language plpgsql
security definer
set search_path='public','private'
as $$
begin
  if auth.uid() is not null and exists (
    select 1 from public.school_memberships sm
    where sm.user_id=auth.uid() and sm.school_id=new.school_id and sm.role='teacher' and sm.active=true
  ) then
    insert into public.class_subject_teachers(class_subject_id,user_id)
    values(new.id,auth.uid()) on conflict do nothing;
  end if;
  return new;
end;
$$;
revoke all on function private.add_class_subject_creator() from public,anon,authenticated;
create trigger class_subjects_add_creator after insert on public.class_subjects for each row execute function private.add_class_subject_creator();

alter table public.subjects enable row level security;
alter table public.class_subjects enable row level security;
alter table public.class_subject_teachers enable row level security;
alter table public.subject_room_items enable row level security;

revoke all on public.subjects, public.class_subjects, public.class_subject_teachers, public.subject_room_items from anon,authenticated;
grant select,insert,update,delete on public.subjects, public.class_subjects, public.class_subject_teachers, public.subject_room_items to authenticated;
grant usage,select on sequence public.subjects_id_seq, public.class_subjects_id_seq, public.subject_room_items_id_seq to authenticated;

create policy "school staff read subjects" on public.subjects for select to authenticated using (public.is_school_staff(school_id));
create policy "school staff create subjects" on public.subjects for insert to authenticated with check (public.is_school_staff(school_id) and created_by=(select auth.uid()));
create policy "school admins update subjects" on public.subjects for update to authenticated using (public.has_school_role(school_id,'admin')) with check (public.has_school_role(school_id,'admin'));
create policy "school admins delete subjects" on public.subjects for delete to authenticated using (public.has_school_role(school_id,'admin'));

create policy "school staff read class subjects" on public.class_subjects for select to authenticated using (public.is_school_staff(school_id));
create policy "class teachers create class subjects" on public.class_subjects for insert to authenticated with check (
  public.has_school_role(school_id,'admin')
  or exists (
    select 1 from public.teacher_classes tc
    join public.school_memberships sm on sm.user_id=tc.teacher_id and sm.school_id=class_subjects.school_id and sm.role='teacher' and sm.active=true
    where tc.class_id=class_subjects.class_id and tc.teacher_id=(select auth.uid())
  )
);
create policy "subject teachers update class subjects" on public.class_subjects for update to authenticated using (public.can_edit_class_subject(id)) with check (public.can_edit_class_subject(id));
create policy "subject teachers delete class subjects" on public.class_subjects for delete to authenticated using (public.can_edit_class_subject(id));

create policy "school staff read subject teachers" on public.class_subject_teachers for select to authenticated using (
  exists(select 1 from public.class_subjects cs where cs.id=class_subject_id and public.is_school_staff(cs.school_id))
);
create policy "class teachers manage subject teachers" on public.class_subject_teachers for all to authenticated using (
  exists(
    select 1 from public.class_subjects cs
    where cs.id=class_subject_id and (
      public.has_school_role(cs.school_id,'admin')
      or exists(select 1 from public.teacher_classes tc where tc.class_id=cs.class_id and tc.teacher_id=(select auth.uid()))
    )
  )
) with check (
  exists(
    select 1 from public.class_subjects cs
    join public.school_memberships target on target.user_id=class_subject_teachers.user_id and target.school_id=cs.school_id and target.role='teacher' and target.active=true
    where cs.id=class_subject_id and (
      public.has_school_role(cs.school_id,'admin')
      or exists(select 1 from public.teacher_classes tc where tc.class_id=cs.class_id and tc.teacher_id=(select auth.uid()))
    )
  )
);

create policy "school staff read subject room items" on public.subject_room_items for select to authenticated using (
  exists(select 1 from public.class_subjects cs where cs.id=class_subject_id and public.is_school_staff(cs.school_id))
);
create policy "subject teachers create room items" on public.subject_room_items for insert to authenticated with check (public.can_edit_class_subject(class_subject_id));
create policy "subject teachers update room items" on public.subject_room_items for update to authenticated using (public.can_edit_class_subject(class_subject_id)) with check (public.can_edit_class_subject(class_subject_id));
create policy "subject teachers delete room items" on public.subject_room_items for delete to authenticated using (public.can_edit_class_subject(class_subject_id));

insert into public.subjects(school_id,name,slug,created_by)
select distinct c.school_id, trim(se.subject), regexp_replace(lower(trim(se.subject)),'[^a-z0-9æøå]+','-','g'), null::uuid
from public.schedule_entries se
join public.classes c on c.id=se.class_id
where c.school_id is not null
  and trim(se.subject)<>''
  and lower(trim(se.subject)) not in ('pause','samling')
on conflict (school_id,slug) do nothing;

insert into public.class_subjects(school_id,class_id,subject_id,title,created_by,updated_by)
select distinct c.school_id,se.class_id,s.id,s.name,null::uuid,null::uuid
from public.schedule_entries se
join public.classes c on c.id=se.class_id
join public.subjects s on s.school_id=c.school_id and s.slug=regexp_replace(lower(trim(se.subject)),'[^a-z0-9æøå]+','-','g')
where lower(trim(se.subject)) not in ('pause','samling')
on conflict (class_id,subject_id) do nothing;

insert into public.class_subject_teachers(class_subject_id,user_id)
select distinct cs.id,st.teacher_id
from public.schedule_entries se
join public.schedule_teachers st on st.schedule_entry_id=se.id
join public.classes c on c.id=se.class_id
join public.subjects s on s.school_id=c.school_id and s.slug=regexp_replace(lower(trim(se.subject)),'[^a-z0-9æøå]+','-','g')
join public.class_subjects cs on cs.class_id=se.class_id and cs.subject_id=s.id
join public.school_memberships sm on sm.user_id=st.teacher_id and sm.school_id=c.school_id and sm.role='teacher' and sm.active=true
where lower(trim(se.subject)) not in ('pause','samling')
on conflict do nothing;
