create table if not exists public.school_years (
  id bigint generated by default as identity primary key,
  school_id bigint not null references public.schools(id) on delete cascade,
  label text not null,
  period_start date not null,
  period_end date not null,
  teaching_start date,
  teaching_end date,
  status text not null default 'draft' check (status in ('draft','active','archived')),
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  updated_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint school_years_school_label_key unique (school_id,label),
  constraint school_years_period_check check (period_end >= period_start),
  constraint school_years_teaching_range_check check (
    (teaching_start is null and teaching_end is null)
    or (
      teaching_start is not null and teaching_end is not null
      and teaching_end >= teaching_start
      and teaching_start >= period_start
      and teaching_end <= period_end
    )
  )
);
create unique index if not exists school_years_one_active_per_school_idx
  on public.school_years(school_id) where status='active';
create index if not exists school_years_school_period_idx on public.school_years(school_id,period_start,period_end);
create index if not exists school_years_created_by_idx on public.school_years(created_by);
create index if not exists school_years_updated_by_idx on public.school_years(updated_by);

alter table public.school_years enable row level security;
revoke all on public.school_years from anon;
grant select,insert,update,delete on public.school_years to authenticated;
grant usage,select on sequence public.school_years_id_seq to authenticated;

create policy school_years_read_members on public.school_years for select to authenticated
using (public.is_school_member(school_id));
create policy school_years_create_leadership on public.school_years for insert to authenticated
with check (public.has_school_role(school_id,'admin') or public.has_school_role(school_id,'leader'));
create policy school_years_update_leadership on public.school_years for update to authenticated
using (public.has_school_role(school_id,'admin') or public.has_school_role(school_id,'leader'))
with check (public.has_school_role(school_id,'admin') or public.has_school_role(school_id,'leader'));
create policy school_years_delete_leadership on public.school_years for delete to authenticated
using (public.has_school_role(school_id,'admin') or public.has_school_role(school_id,'leader'));

create table if not exists public.school_year_calendar_events (
  id bigint generated by default as identity primary key,
  school_year_id bigint not null references public.school_years(id) on delete cascade,
  starts_on date not null,
  ends_on date not null,
  title text not null,
  event_kind text not null default 'other' check (event_kind in ('closure','pedagogical','special_week','project','trip','event','other')),
  closes_school boolean not null default false,
  visibility text not null default 'staff' check (visibility in ('all','staff','leadership')),
  source text not null default 'planning' check (source in ('planning','school_calendar')),
  notes text,
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  updated_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint school_year_calendar_events_dates_check check (ends_on >= starts_on),
  constraint school_year_calendar_events_title_check check (length(trim(title)) between 1 and 200),
  constraint school_year_calendar_events_notes_check check (notes is null or length(notes) <= 4000)
);
create index if not exists school_year_calendar_events_year_dates_idx on public.school_year_calendar_events(school_year_id,starts_on,ends_on);
create index if not exists school_year_calendar_events_created_by_idx on public.school_year_calendar_events(created_by);

alter table public.school_year_calendar_events enable row level security;
revoke all on public.school_year_calendar_events from anon;
grant select,insert,update,delete on public.school_year_calendar_events to authenticated;
grant usage,select on sequence public.school_year_calendar_events_id_seq to authenticated;

create policy school_year_calendar_events_read on public.school_year_calendar_events for select to authenticated
using (exists (
  select 1 from public.school_years sy
  where sy.id=school_year_id and (
    (visibility='all' and public.is_school_member(sy.school_id))
    or (visibility='staff' and public.is_school_staff(sy.school_id))
    or (visibility='leadership' and (public.has_school_role(sy.school_id,'admin') or public.has_school_role(sy.school_id,'leader')))
  )
));
create policy school_year_calendar_events_create on public.school_year_calendar_events for insert to authenticated
with check (exists (
  select 1 from public.school_years sy where sy.id=school_year_id
  and (public.has_school_role(sy.school_id,'admin') or public.has_school_role(sy.school_id,'leader'))
));
create policy school_year_calendar_events_update on public.school_year_calendar_events for update to authenticated
using (exists (
  select 1 from public.school_years sy where sy.id=school_year_id
  and (public.has_school_role(sy.school_id,'admin') or public.has_school_role(sy.school_id,'leader'))
))
with check (exists (
  select 1 from public.school_years sy where sy.id=school_year_id
  and (public.has_school_role(sy.school_id,'admin') or public.has_school_role(sy.school_id,'leader'))
));
create policy school_year_calendar_events_delete on public.school_year_calendar_events for delete to authenticated
using (exists (
  select 1 from public.school_years sy where sy.id=school_year_id
  and (public.has_school_role(sy.school_id,'admin') or public.has_school_role(sy.school_id,'leader'))
));

create table if not exists public.school_schedule_versions (
  id bigint generated by default as identity primary key,
  school_year_id bigint not null references public.school_years(id) on delete cascade,
  name text not null,
  status text not null default 'draft' check (status in ('draft','published','archived')),
  effective_from date,
  effective_to date,
  based_on_version_id bigint references public.school_schedule_versions(id) on delete set null,
  published_at timestamptz,
  published_by uuid references auth.users(id) on delete set null,
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  updated_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint school_schedule_versions_name_check check (length(trim(name)) between 1 and 120),
  constraint school_schedule_versions_effective_check check (effective_to is null or effective_from is null or effective_to >= effective_from)
);
create unique index if not exists school_schedule_versions_one_published_idx
  on public.school_schedule_versions(school_year_id) where status='published';
create index if not exists school_schedule_versions_year_status_idx on public.school_schedule_versions(school_year_id,status);
create index if not exists school_schedule_versions_based_on_idx on public.school_schedule_versions(based_on_version_id);

alter table public.school_schedule_versions enable row level security;
revoke all on public.school_schedule_versions from anon;
grant select,insert,update,delete on public.school_schedule_versions to authenticated;
grant usage,select on sequence public.school_schedule_versions_id_seq to authenticated;

create policy school_schedule_versions_read on public.school_schedule_versions for select to authenticated
using (exists (
  select 1 from public.school_years sy where sy.id=school_year_id and (
    public.has_school_role(sy.school_id,'admin')
    or public.has_school_role(sy.school_id,'leader')
    or (status='published' and public.is_school_staff(sy.school_id))
  )
));
create policy school_schedule_versions_create on public.school_schedule_versions for insert to authenticated
with check (exists (
  select 1 from public.school_years sy where sy.id=school_year_id
  and (public.has_school_role(sy.school_id,'admin') or public.has_school_role(sy.school_id,'leader'))
));
create policy school_schedule_versions_update on public.school_schedule_versions for update to authenticated
using (exists (
  select 1 from public.school_years sy where sy.id=school_year_id
  and (public.has_school_role(sy.school_id,'admin') or public.has_school_role(sy.school_id,'leader'))
))
with check (exists (
  select 1 from public.school_years sy where sy.id=school_year_id
  and (public.has_school_role(sy.school_id,'admin') or public.has_school_role(sy.school_id,'leader'))
));
create policy school_schedule_versions_delete on public.school_schedule_versions for delete to authenticated
using (exists (
  select 1 from public.school_years sy where sy.id=school_year_id
  and (public.has_school_role(sy.school_id,'admin') or public.has_school_role(sy.school_id,'leader'))
));

create table if not exists public.staff_year_allocations (
  id bigint generated by default as identity primary key,
  school_year_id bigint not null references public.school_years(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  category text not null check (category in ('preparation','meeting','duty','leadership','amr','tr','reading_specialist','project','administration','other')),
  title text not null,
  planned_minutes integer not null check (planned_minutes >= 0 and planned_minutes <= 200000),
  starts_on date,
  ends_on date,
  notes text,
  active boolean not null default true,
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  updated_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint staff_year_allocations_title_check check (length(trim(title)) between 1 and 200),
  constraint staff_year_allocations_dates_check check (ends_on is null or starts_on is null or ends_on >= starts_on),
  constraint staff_year_allocations_notes_check check (notes is null or length(notes) <= 4000)
);
create index if not exists staff_year_allocations_year_user_idx on public.staff_year_allocations(school_year_id,user_id) where active;
create index if not exists staff_year_allocations_created_by_idx on public.staff_year_allocations(created_by);

alter table public.staff_year_allocations enable row level security;
revoke all on public.staff_year_allocations from anon;
grant select,insert,update,delete on public.staff_year_allocations to authenticated;
grant usage,select on sequence public.staff_year_allocations_id_seq to authenticated;

create policy staff_year_allocations_read on public.staff_year_allocations for select to authenticated
using (exists (
  select 1 from public.school_years sy where sy.id=school_year_id and (
    ((select auth.uid())=user_id and public.is_school_member(sy.school_id))
    or public.has_school_role(sy.school_id,'admin')
    or public.has_school_role(sy.school_id,'leader')
  )
));
create policy staff_year_allocations_create on public.staff_year_allocations for insert to authenticated
with check (exists (
  select 1 from public.school_years sy where sy.id=school_year_id
  and (public.has_school_role(sy.school_id,'admin') or public.has_school_role(sy.school_id,'leader'))
));
create policy staff_year_allocations_update on public.staff_year_allocations for update to authenticated
using (exists (
  select 1 from public.school_years sy where sy.id=school_year_id
  and (public.has_school_role(sy.school_id,'admin') or public.has_school_role(sy.school_id,'leader'))
))
with check (exists (
  select 1 from public.school_years sy where sy.id=school_year_id
  and (public.has_school_role(sy.school_id,'admin') or public.has_school_role(sy.school_id,'leader'))
));
create policy staff_year_allocations_delete on public.staff_year_allocations for delete to authenticated
using (exists (
  select 1 from public.school_years sy where sy.id=school_year_id
  and (public.has_school_role(sy.school_id,'admin') or public.has_school_role(sy.school_id,'leader'))
));

create table if not exists public.teaching_requirements (
  id bigint generated by default as identity primary key,
  school_year_id bigint not null references public.school_years(id) on delete cascade,
  class_subject_id bigint not null references public.class_subjects(id) on delete cascade,
  weekly_minutes integer not null check (weekly_minutes > 0 and weekly_minutes <= 10080),
  notes text,
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  updated_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint teaching_requirements_year_subject_key unique (school_year_id,class_subject_id),
  constraint teaching_requirements_notes_check check (notes is null or length(notes) <= 4000)
);
create index if not exists teaching_requirements_subject_idx on public.teaching_requirements(class_subject_id);
create index if not exists teaching_requirements_created_by_idx on public.teaching_requirements(created_by);

alter table public.teaching_requirements enable row level security;
revoke all on public.teaching_requirements from anon;
grant select,insert,update,delete on public.teaching_requirements to authenticated;
grant usage,select on sequence public.teaching_requirements_id_seq to authenticated;

create policy teaching_requirements_read on public.teaching_requirements for select to authenticated
using (exists (
  select 1 from public.school_years sy where sy.id=school_year_id and public.is_school_staff(sy.school_id)
));
create policy teaching_requirements_create on public.teaching_requirements for insert to authenticated
with check (exists (
  select 1 from public.school_years sy
  join public.class_subjects cs on cs.id=class_subject_id
  join public.classes c on c.id=cs.class_id
  where sy.id=school_year_id and c.school_id=sy.school_id
    and (public.has_school_role(sy.school_id,'admin') or public.has_school_role(sy.school_id,'leader'))
));
create policy teaching_requirements_update on public.teaching_requirements for update to authenticated
using (exists (
  select 1 from public.school_years sy where sy.id=school_year_id
  and (public.has_school_role(sy.school_id,'admin') or public.has_school_role(sy.school_id,'leader'))
))
with check (exists (
  select 1 from public.school_years sy
  join public.class_subjects cs on cs.id=class_subject_id
  join public.classes c on c.id=cs.class_id
  where sy.id=school_year_id and c.school_id=sy.school_id
    and (public.has_school_role(sy.school_id,'admin') or public.has_school_role(sy.school_id,'leader'))
));
create policy teaching_requirements_delete on public.teaching_requirements for delete to authenticated
using (exists (
  select 1 from public.school_years sy where sy.id=school_year_id
  and (public.has_school_role(sy.school_id,'admin') or public.has_school_role(sy.school_id,'leader'))
));

alter table public.schedule_entries add column if not exists schedule_version_id bigint references public.school_schedule_versions(id) on delete restrict;
create index if not exists schedule_entries_version_idx on public.schedule_entries(schedule_version_id);

alter table public.staff_work_profiles add column if not exists school_year_id bigint references public.school_years(id) on delete restrict;
create index if not exists staff_work_profiles_school_year_idx on public.staff_work_profiles(school_year_id,user_id);

with work_year as (
  select school_id,school_year,min(period_start) as period_start,max(period_end) as period_end,
         row_number() over(partition by school_id order by max(period_end) desc) as rn
  from public.staff_work_profiles
  group by school_id,school_year
), source as (
  select s.id as school_id,
         coalesce(w.school_year,
           case when ss.school_year_start is not null then extract(year from ss.school_year_start)::int::text||'/'||(extract(year from ss.school_year_start)::int+1)::text end,
           extract(year from current_date)::int::text||'/'||(extract(year from current_date)::int+1)::text) as label,
         coalesce(w.period_start,ss.school_year_start,make_date(extract(year from current_date)::int,8,1)) as period_start,
         coalesce(w.period_end,ss.school_year_end,make_date(extract(year from current_date)::int+1,7,31)) as period_end,
         ss.school_year_start as teaching_start,
         ss.school_year_end as teaching_end
  from public.schools s
  left join work_year w on w.school_id=s.id and w.rn=1
  left join public.school_settings ss on ss.school_id=s.id
)
insert into public.school_years(school_id,label,period_start,period_end,teaching_start,teaching_end,status)
select school_id,label,period_start,period_end,
       case when teaching_start between period_start and period_end then teaching_start end,
       case when teaching_end between period_start and period_end then teaching_end end,
       'active'
from source
where period_end>=period_start
on conflict (school_id,label) do update
set period_start=excluded.period_start,
    period_end=excluded.period_end,
    teaching_start=excluded.teaching_start,
    teaching_end=excluded.teaching_end,
    status='active',
    updated_at=now();

update public.staff_work_profiles swp
set school_year_id=sy.id
from public.school_years sy
where swp.school_year_id is null
  and sy.school_id=swp.school_id
  and sy.label=swp.school_year;

insert into public.school_schedule_versions(school_year_id,name,status,effective_from)
select sy.id,'Grundskema · kladde','draft',coalesce(sy.teaching_start,sy.period_start)
from public.school_years sy
where sy.status='active'
  and not exists(select 1 from public.school_schedule_versions sv where sv.school_year_id=sy.id);

update public.schedule_entries se
set schedule_version_id=sv.id
from public.classes c
join public.school_years sy on sy.school_id=c.school_id and sy.status='active'
join public.school_schedule_versions sv on sv.school_year_id=sy.id and sv.status='draft'
where se.class_id=c.id and se.schedule_version_id is null;

insert into public.school_year_calendar_events(school_year_id,starts_on,ends_on,title,event_kind,closes_school,visibility,source)
select sy.id,(d.value->>'date')::date,(d.value->>'date')::date,
       coalesce(nullif(trim(d.value->>'label'),''),'Lukkedag'),'closure',true,'all','school_calendar'
from public.school_settings ss
join public.school_years sy on sy.school_id=ss.school_id and sy.status='active'
cross join lateral jsonb_array_elements(coalesce(ss.closed_days,'[]'::jsonb)) d(value)
where d.value ? 'date';

insert into public.school_year_calendar_events(school_year_id,starts_on,ends_on,title,event_kind,closes_school,visibility,source)
select sy.id,(e.value->>'date')::date,(e.value->>'date')::date,
       coalesce(nullif(trim(e.value->>'label'),''),'Begivenhed'),
       case when e.value->>'kind' in ('pedagogical','special_week','project','trip','event','other') then e.value->>'kind' else 'other' end,
       false,'staff','school_calendar'
from public.school_settings ss
join public.school_years sy on sy.school_id=ss.school_id and sy.status='active'
cross join lateral jsonb_array_elements(coalesce(ss.calendar_events,'[]'::jsonb)) e(value)
where e.value ? 'date';

drop policy if exists "school admins insert school settings" on public.school_settings;
drop policy if exists "school admins update school settings" on public.school_settings;
drop policy if exists "school admins delete school settings" on public.school_settings;
create policy "school leadership insert school settings" on public.school_settings for insert to authenticated
with check (public.has_school_role(school_id,'admin') or public.has_school_role(school_id,'leader'));
create policy "school leadership update school settings" on public.school_settings for update to authenticated
using (public.has_school_role(school_id,'admin') or public.has_school_role(school_id,'leader'))
with check (public.has_school_role(school_id,'admin') or public.has_school_role(school_id,'leader'));
create policy "school leadership delete school settings" on public.school_settings for delete to authenticated
using (public.has_school_role(school_id,'admin') or public.has_school_role(school_id,'leader'));

create or replace function public.save_school_year_calendar(
  p_school_id bigint,
  p_teaching_start date,
  p_teaching_end date,
  p_closed_days jsonb,
  p_calendar_events jsonb
) returns void
language plpgsql
security invoker
set search_path=''
as $$
declare
  v_year_id bigint;
  v_item jsonb;
  v_date date;
  v_kind text;
begin
  if not (public.has_school_role(p_school_id,'admin') or public.has_school_role(p_school_id,'leader')) then
    raise exception 'Leadership access required';
  end if;
  if p_teaching_start is null or p_teaching_end is null or p_teaching_end < p_teaching_start then
    raise exception 'Invalid teaching period';
  end if;
  if jsonb_typeof(coalesce(p_closed_days,'[]'::jsonb)) <> 'array'
     or jsonb_typeof(coalesce(p_calendar_events,'[]'::jsonb)) <> 'array' then
    raise exception 'Calendar payload must be arrays';
  end if;

  select id into v_year_id
  from public.school_years
  where school_id=p_school_id and status='active'
  limit 1;
  if v_year_id is null then raise exception 'Active school year not found'; end if;

  update public.school_years
  set teaching_start=p_teaching_start, teaching_end=p_teaching_end,
      updated_by=(select auth.uid()), updated_at=now()
  where id=v_year_id
    and p_teaching_start>=period_start and p_teaching_end<=period_end;
  if not found then raise exception 'Teaching period must be inside the school-year resource period'; end if;

  insert into public.school_settings(school_id,school_year_start,school_year_end,closed_days,calendar_events,updated_by,updated_at)
  values(p_school_id,p_teaching_start,p_teaching_end,coalesce(p_closed_days,'[]'::jsonb),coalesce(p_calendar_events,'[]'::jsonb),(select auth.uid()),now())
  on conflict (school_id) do update
  set school_year_start=excluded.school_year_start,
      school_year_end=excluded.school_year_end,
      closed_days=excluded.closed_days,
      calendar_events=excluded.calendar_events,
      updated_by=excluded.updated_by,
      updated_at=excluded.updated_at;

  delete from public.school_year_calendar_events
  where school_year_id=v_year_id and source='school_calendar';

  for v_item in select value from jsonb_array_elements(coalesce(p_closed_days,'[]'::jsonb)) loop
    v_date=(v_item->>'date')::date;
    insert into public.school_year_calendar_events(school_year_id,starts_on,ends_on,title,event_kind,closes_school,visibility,source,created_by,updated_by)
    values(v_year_id,v_date,v_date,coalesce(nullif(trim(v_item->>'label'),''),'Lukkedag'),'closure',true,'all','school_calendar',(select auth.uid()),(select auth.uid()));
  end loop;

  for v_item in select value from jsonb_array_elements(coalesce(p_calendar_events,'[]'::jsonb)) loop
    v_date=(v_item->>'date')::date;
    v_kind=case when v_item->>'kind' in ('pedagogical','special_week','project','trip','event','other') then v_item->>'kind' else 'other' end;
    insert into public.school_year_calendar_events(school_year_id,starts_on,ends_on,title,event_kind,closes_school,visibility,source,created_by,updated_by)
    values(v_year_id,v_date,v_date,coalesce(nullif(trim(v_item->>'label'),''),'Begivenhed'),v_kind,false,'staff','school_calendar',(select auth.uid()),(select auth.uid()));
  end loop;
end;
$$;
revoke all on function public.save_school_year_calendar(bigint,date,date,jsonb,jsonb) from public,anon;
grant execute on function public.save_school_year_calendar(bigint,date,date,jsonb,jsonb) to authenticated;

create or replace function public.publish_schedule_version(p_version_id bigint,p_effective_from date default null)
returns void
language plpgsql
security invoker
set search_path=''
as $$
declare
  v_year_id bigint;
  v_school_id bigint;
  v_start date;
begin
  select sv.school_year_id,sy.school_id,coalesce(p_effective_from,sy.teaching_start,sy.period_start)
  into v_year_id,v_school_id,v_start
  from public.school_schedule_versions sv
  join public.school_years sy on sy.id=sv.school_year_id
  where sv.id=p_version_id;
  if v_year_id is null then raise exception 'Schedule version not found'; end if;
  if not (public.has_school_role(v_school_id,'admin') or public.has_school_role(v_school_id,'leader')) then
    raise exception 'Leadership access required';
  end if;

  update public.school_schedule_versions
  set status='archived', effective_to=v_start-1, updated_by=(select auth.uid()), updated_at=now()
  where school_year_id=v_year_id and status='published' and id<>p_version_id;

  update public.school_schedule_versions
  set status='published', effective_from=v_start, effective_to=null,
      published_at=now(), published_by=(select auth.uid()), updated_by=(select auth.uid()), updated_at=now()
  where id=p_version_id;
end;
$$;
revoke all on function public.publish_schedule_version(bigint,date) from public,anon;
grant execute on function public.publish_schedule_version(bigint,date) to authenticated;