create table public.school_policy_versions (
  id bigint generated by default as identity primary key,
  school_id bigint not null references public.schools(id) on delete cascade,
  policy_key text not null check (policy_key in ('usage_terms','privacy_notice','security_logging_notice')),
  version_label text not null,
  title text not null,
  summary text,
  acknowledgement_text text not null,
  body_markdown text not null,
  status text not null default 'draft' check (status in ('draft','published','retired')),
  effective_from timestamptz,
  published_at timestamptz,
  published_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id),
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id),
  unique(school_id,policy_key,version_label)
);

create unique index school_policy_versions_one_published_key_idx
on public.school_policy_versions(school_id,policy_key)
where status='published';

create index school_policy_versions_school_status_idx
on public.school_policy_versions(school_id,status,effective_from);

create table public.user_policy_acknowledgements (
  id bigint generated by default as identity primary key,
  school_id bigint not null references public.schools(id) on delete cascade,
  policy_version_id bigint not null references public.school_policy_versions(id) on delete restrict,
  user_id uuid not null references auth.users(id) on delete cascade,
  acknowledged_at timestamptz not null default now(),
  unique(policy_version_id,user_id)
);

create index user_policy_ack_user_idx on public.user_policy_acknowledgements(user_id,acknowledged_at desc);
create index user_policy_ack_school_idx on public.user_policy_acknowledgements(school_id,policy_version_id);

alter table public.school_policy_versions enable row level security;
alter table public.user_policy_acknowledgements enable row level security;

create policy school_policy_versions_read_published
on public.school_policy_versions for select to authenticated
using (
  status='published'
  and effective_from is not null
  and effective_from<=now()
  and public.is_school_member(school_id)
);

create policy school_policy_versions_admin_read_all
on public.school_policy_versions for select to authenticated
using (public.has_school_role(school_id,'admin'));

create policy policy_ack_read_own
on public.user_policy_acknowledgements for select to authenticated
using (user_id=(select auth.uid()));

create policy policy_ack_admin_read_school
on public.user_policy_acknowledgements for select to authenticated
using (public.has_school_role(school_id,'admin'));

revoke all on public.school_policy_versions from anon, authenticated;
grant select on public.school_policy_versions to authenticated;
revoke all on public.user_policy_acknowledgements from anon, authenticated;
grant select on public.user_policy_acknowledgements to authenticated;

create or replace function public.my_required_policy_acknowledgements()
returns table(
  school_id bigint,
  policy_version_id bigint,
  policy_key text,
  version_label text,
  title text,
  summary text,
  acknowledgement_text text,
  body_markdown text,
  effective_from timestamptz
)
language sql
security definer
set search_path=''
as $function$
  select pv.school_id,pv.id,pv.policy_key,pv.version_label,pv.title,pv.summary,
         pv.acknowledgement_text,pv.body_markdown,pv.effective_from
  from public.school_policy_versions pv
  where auth.uid() is not null
    and pv.status='published'
    and pv.effective_from is not null
    and pv.effective_from<=now()
    and exists(
      select 1 from public.school_memberships sm
      where sm.school_id=pv.school_id and sm.user_id=auth.uid() and sm.active=true
    )
    and not exists(
      select 1 from public.user_policy_acknowledgements a
      where a.policy_version_id=pv.id and a.user_id=auth.uid()
    )
  order by pv.school_id,pv.policy_key;
$function$;

revoke all on function public.my_required_policy_acknowledgements() from public, anon;
grant execute on function public.my_required_policy_acknowledgements() to authenticated;

create or replace function public.acknowledge_policy(p_policy_version_id bigint)
returns void
language plpgsql
security definer
set search_path=''
as $function$
declare
  v_school_id bigint;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;

  select pv.school_id into v_school_id
  from public.school_policy_versions pv
  where pv.id=p_policy_version_id
    and pv.status='published'
    and pv.effective_from is not null
    and pv.effective_from<=now();

  if v_school_id is null then raise exception 'Published policy not found'; end if;
  if not exists(
    select 1 from public.school_memberships sm
    where sm.school_id=v_school_id and sm.user_id=auth.uid() and sm.active=true
  ) then
    raise exception 'Active school membership required';
  end if;

  insert into public.user_policy_acknowledgements(school_id,policy_version_id,user_id)
  values(v_school_id,p_policy_version_id,auth.uid())
  on conflict(policy_version_id,user_id) do nothing;
end;
$function$;

revoke all on function public.acknowledge_policy(bigint) from public, anon;
grant execute on function public.acknowledge_policy(bigint) to authenticated;
