create table if not exists public.training_assignments (
  id bigint generated by default as identity primary key,
  class_id bigint not null references public.classes(id) on delete cascade,
  subject_id text not null check (length(trim(subject_id)) > 0),
  area_id text not null check (length(trim(area_id)) > 0),
  skill_id text not null check (length(trim(skill_id)) > 0),
  level_id text not null check (length(trim(level_id)) > 0),
  target_grade smallint null check (target_grade between 0 and 10),
  title text not null,
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  constraint training_assignments_supported_subject check (subject_id = any(array['matematik'::text,'dansk-grammatik'::text]))
);

create table if not exists public.training_assignment_students (
  training_assignment_id bigint not null references public.training_assignments(id) on delete cascade,
  student_id bigint not null references public.students(id) on delete cascade,
  primary key (training_assignment_id,student_id)
);

create table if not exists public.training_assignment_progress (
  training_assignment_id bigint not null references public.training_assignments(id) on delete cascade,
  student_id bigint not null references public.students(id) on delete cascade,
  attempts integer not null default 0 check (attempts >= 0),
  best_score integer not null default 0 check (best_score >= 0),
  last_score integer not null default 0 check (last_score >= 0),
  max_score integer not null default 0 check (max_score >= 0),
  first_attempt_at timestamptz null,
  last_attempt_at timestamptz null,
  updated_at timestamptz not null default now(),
  primary key (training_assignment_id,student_id)
);

create index if not exists training_assignments_class_subject_idx on public.training_assignments(class_id,subject_id,created_at desc);
create index if not exists training_assignment_students_student_idx on public.training_assignment_students(student_id,training_assignment_id);
create index if not exists training_assignment_progress_student_idx on public.training_assignment_progress(student_id,training_assignment_id);
create index if not exists training_assignments_created_by_idx on public.training_assignments(created_by);

alter table public.training_assignments enable row level security;
alter table public.training_assignment_students enable row level security;
alter table public.training_assignment_progress enable row level security;
revoke all on table public.training_assignments from public, anon, authenticated;
revoke all on table public.training_assignment_students from public, anon, authenticated;
revoke all on table public.training_assignment_progress from public, anon, authenticated;

create or replace function public.create_training_assignment(
  p_class_id bigint,
  p_subject_id text,
  p_area_id text,
  p_skill_id text,
  p_level_id text,
  p_target_grade integer default null,
  p_student_ids bigint[] default null,
  p_title text default null
) returns jsonb
language plpgsql
security definer
set search_path='public','private'
as $function$
declare
  v_school_id bigint;
  v_allowed boolean;
  v_assignment public.training_assignments;
  v_invalid_students integer;
  v_recipient_count integer;
begin
  if auth.uid() is null then return jsonb_build_object('ok',false,'error','not_authenticated'); end if;
  if p_subject_id is null or trim(p_subject_id) not in ('matematik','dansk-grammatik') then return jsonb_build_object('ok',false,'error','invalid_subject'); end if;
  if p_area_id is null or trim(p_area_id)='' or p_skill_id is null or trim(p_skill_id)='' or p_level_id is null or trim(p_level_id)='' then return jsonb_build_object('ok',false,'error','invalid_training_key'); end if;
  if p_target_grade is not null and p_target_grade not between 0 and 10 then return jsonb_build_object('ok',false,'error','invalid_target_grade'); end if;

  select c.school_id into v_school_id from public.classes c where c.id=p_class_id;
  if v_school_id is null then return jsonb_build_object('ok',false,'error','class_not_found'); end if;
  select (public.has_school_role(v_school_id,'admin') or (public.has_school_role(v_school_id,'teacher') and exists(select 1 from public.teacher_classes tc where tc.class_id=p_class_id and tc.teacher_id=auth.uid()))) into v_allowed;
  if not coalesce(v_allowed,false) then return jsonb_build_object('ok',false,'error','forbidden'); end if;

  if p_student_ids is not null and cardinality(p_student_ids)>0 then
    select count(*) into v_invalid_students from unnest(p_student_ids) x(student_id)
    where not exists(select 1 from public.students s where s.id=x.student_id and s.class_id=p_class_id);
    if v_invalid_students>0 then return jsonb_build_object('ok',false,'error','invalid_recipients'); end if;
  end if;

  insert into public.training_assignments(class_id,subject_id,area_id,skill_id,level_id,target_grade,title,created_by)
  values(p_class_id,trim(p_subject_id),trim(p_area_id),trim(p_skill_id),trim(p_level_id),p_target_grade,coalesce(nullif(trim(p_title),''),concat('Træn ',p_skill_id)),auth.uid())
  returning * into v_assignment;

  if p_student_ids is not null and cardinality(p_student_ids)>0 then
    insert into public.training_assignment_students(training_assignment_id,student_id)
    select v_assignment.id,student_id from (select distinct unnest(p_student_ids) student_id) q;
    select count(*) into v_recipient_count from public.training_assignment_students where training_assignment_id=v_assignment.id;
  else
    select count(*) into v_recipient_count from public.students where class_id=p_class_id;
  end if;

  return jsonb_build_object('ok',true,'assignment_id',v_assignment.id,'recipient_count',v_recipient_count);
end;
$function$;

create or replace function public.student_session_training_assignments(p_session_token text)
returns jsonb
language plpgsql
security definer
set search_path='public','private'
as $function$
declare s public.students;
begin
  select * into s from public.students where id=private.student_id_for_session(p_session_token);
  if s.id is null then return jsonb_build_object('ok',false,'error','invalid_session'); end if;
  return jsonb_build_object('ok',true,'assignments',coalesce((
    select jsonb_agg(jsonb_build_object(
      'id',a.id,'title',a.title,'subject_id',a.subject_id,'area_id',a.area_id,'skill_id',a.skill_id,'level_id',a.level_id,'target_grade',a.target_grade,'created_at',a.created_at,
      'started',coalesce(p.attempts,0)>0,'attempts',coalesce(p.attempts,0),'best_score',case when p.attempts>0 then p.best_score else null end,
      'last_score',case when p.attempts>0 then p.last_score else null end,'max_score',case when p.attempts>0 then p.max_score else null end,
      'mastered',coalesce(p.attempts,0)>0 and p.max_score>0 and p.best_score>=p.max_score,'last_attempt_at',p.last_attempt_at
    ) order by a.created_at desc)
    from public.training_assignments a
    left join public.training_assignment_progress p on p.training_assignment_id=a.id and p.student_id=s.id
    where a.class_id=s.class_id and (
      not exists(select 1 from public.training_assignment_students x where x.training_assignment_id=a.id)
      or exists(select 1 from public.training_assignment_students x where x.training_assignment_id=a.id and x.student_id=s.id)
    )
  ),'[]'::jsonb));
end;
$function$;

create or replace function public.teacher_training_assignments(p_class_id bigint,p_subject_id text default null)
returns jsonb
language plpgsql
security definer
set search_path='public','private'
as $function$
declare v_school_id bigint; v_allowed boolean;
begin
  if auth.uid() is null then return jsonb_build_object('ok',false,'error','not_authenticated'); end if;
  select c.school_id into v_school_id from public.classes c where c.id=p_class_id;
  if v_school_id is null then return jsonb_build_object('ok',false,'error','class_not_found'); end if;
  select (public.has_school_role(v_school_id,'admin') or (public.has_school_role(v_school_id,'teacher') and exists(select 1 from public.teacher_classes tc where tc.class_id=p_class_id and tc.teacher_id=auth.uid()))) into v_allowed;
  if not coalesce(v_allowed,false) then return jsonb_build_object('ok',false,'error','forbidden'); end if;

  return jsonb_build_object('ok',true,'assignments',coalesce((
    select jsonb_agg(jsonb_build_object(
      'id',a.id,'title',a.title,'subject_id',a.subject_id,'area_id',a.area_id,'skill_id',a.skill_id,'level_id',a.level_id,'target_grade',a.target_grade,'created_at',a.created_at,
      'recipient_count',case when exists(select 1 from public.training_assignment_students x0 where x0.training_assignment_id=a.id)
        then (select count(*) from public.training_assignment_students x where x.training_assignment_id=a.id)
        else (select count(*) from public.students s where s.class_id=a.class_id) end,
      'started_count',(select count(*) from public.students s join public.training_assignment_progress p on p.student_id=s.id and p.training_assignment_id=a.id
        where s.class_id=a.class_id and (not exists(select 1 from public.training_assignment_students z where z.training_assignment_id=a.id)
          or exists(select 1 from public.training_assignment_students z where z.training_assignment_id=a.id and z.student_id=s.id)) and p.attempts>0),
      'mastered_count',(select count(*) from public.students s join public.training_assignment_progress p on p.student_id=s.id and p.training_assignment_id=a.id
        where s.class_id=a.class_id and (not exists(select 1 from public.training_assignment_students z where z.training_assignment_id=a.id)
          or exists(select 1 from public.training_assignment_students z where z.training_assignment_id=a.id and z.student_id=s.id)) and p.attempts>0 and p.max_score>0 and p.best_score>=p.max_score)
    ) order by a.created_at desc)
    from public.training_assignments a where a.class_id=p_class_id and (p_subject_id is null or a.subject_id=p_subject_id)
  ),'[]'::jsonb));
end;
$function$;

create or replace function public.save_student_training_assignment_attempt_session(
  p_session_token text,
  p_training_assignment_id bigint,
  p_answers jsonb,
  p_score integer,
  p_max_score integer
) returns jsonb
language plpgsql
security definer
set search_path='public','private'
as $function$
declare
  v_student_id bigint;
  a public.training_assignments;
  global_saved public.student_training_progress;
  assigned_saved public.training_assignment_progress;
begin
  v_student_id:=private.student_id_for_session(p_session_token);
  if v_student_id is null then return jsonb_build_object('ok',false,'error','invalid_session'); end if;
  select * into a from public.training_assignments where id=p_training_assignment_id;
  if a.id is null then return jsonb_build_object('ok',false,'error','assignment_not_found'); end if;
  if not exists(select 1 from public.students s where s.id=v_student_id and s.class_id=a.class_id) then return jsonb_build_object('ok',false,'error','forbidden'); end if;
  if exists(select 1 from public.training_assignment_students x where x.training_assignment_id=a.id)
     and not exists(select 1 from public.training_assignment_students x where x.training_assignment_id=a.id and x.student_id=v_student_id) then
    return jsonb_build_object('ok',false,'error','not_recipient');
  end if;
  if p_max_score<=0 or p_score<0 or p_score>p_max_score then return jsonb_build_object('ok',false,'error','invalid_score'); end if;

  insert into public.student_training_progress(student_id,subject_id,area_id,skill_id,level_id,attempts,best_score,last_score,max_score,last_answers,first_attempt_at,last_attempt_at,updated_at)
  values(v_student_id,a.subject_id,a.area_id,a.skill_id,a.level_id,1,p_score,p_score,p_max_score,coalesce(p_answers,'{}'::jsonb),now(),now(),now())
  on conflict(student_id,subject_id,area_id,skill_id,level_id)
  do update set attempts=public.student_training_progress.attempts+1,best_score=greatest(public.student_training_progress.best_score,excluded.last_score),last_score=excluded.last_score,max_score=excluded.max_score,last_answers=excluded.last_answers,last_attempt_at=now(),updated_at=now()
  returning * into global_saved;

  insert into public.training_assignment_progress(training_assignment_id,student_id,attempts,best_score,last_score,max_score,first_attempt_at,last_attempt_at,updated_at)
  values(a.id,v_student_id,1,p_score,p_score,p_max_score,now(),now(),now())
  on conflict(training_assignment_id,student_id)
  do update set attempts=public.training_assignment_progress.attempts+1,best_score=greatest(public.training_assignment_progress.best_score,excluded.last_score),last_score=excluded.last_score,max_score=excluded.max_score,last_attempt_at=now(),updated_at=now()
  returning * into assigned_saved;

  return jsonb_build_object('ok',true,'assignment_id',a.id,'attempts',assigned_saved.attempts,'best_score',assigned_saved.best_score,'last_score',assigned_saved.last_score,'max_score',assigned_saved.max_score,'mastered',assigned_saved.best_score>=assigned_saved.max_score,
    'global_attempts',global_saved.attempts,'global_best_score',global_saved.best_score);
end;
$function$;

create or replace function public.delete_training_assignment(p_assignment_id bigint)
returns jsonb
language plpgsql
security definer
set search_path='public','private'
as $function$
declare a public.training_assignments; v_school_id bigint; v_allowed boolean;
begin
  if auth.uid() is null then return jsonb_build_object('ok',false,'error','not_authenticated'); end if;
  select * into a from public.training_assignments where id=p_assignment_id;
  if a.id is null then return jsonb_build_object('ok',false,'error','not_found'); end if;
  select school_id into v_school_id from public.classes where id=a.class_id;
  select (public.has_school_role(v_school_id,'admin') or (public.has_school_role(v_school_id,'teacher') and exists(select 1 from public.teacher_classes tc where tc.class_id=a.class_id and tc.teacher_id=auth.uid()))) into v_allowed;
  if not coalesce(v_allowed,false) then return jsonb_build_object('ok',false,'error','forbidden'); end if;
  if exists(select 1 from public.training_assignment_progress p where p.training_assignment_id=a.id and p.attempts>0) then return jsonb_build_object('ok',false,'error','assignment_started'); end if;
  delete from public.training_assignments where id=a.id;
  return jsonb_build_object('ok',true);
end;
$function$;

revoke all on function public.create_training_assignment(bigint,text,text,text,text,integer,bigint[],text) from public,anon;
revoke all on function public.teacher_training_assignments(bigint,text) from public,anon;
revoke all on function public.delete_training_assignment(bigint) from public,anon;
revoke all on function public.student_session_training_assignments(text) from public,authenticated;
revoke all on function public.save_student_training_assignment_attempt_session(text,bigint,jsonb,integer,integer) from public,authenticated;
grant execute on function public.create_training_assignment(bigint,text,text,text,text,integer,bigint[],text) to authenticated,service_role;
grant execute on function public.teacher_training_assignments(bigint,text) to authenticated,service_role;
grant execute on function public.delete_training_assignment(bigint) to authenticated,service_role;
grant execute on function public.student_session_training_assignments(text) to anon,service_role;
grant execute on function public.save_student_training_assignment_attempt_session(text,bigint,jsonb,integer,integer) to anon,service_role;
