-- Bevar hvert grammatisk forsøg som historik i stedet for kun at overskrive seneste svar.

create table public.grammar_attempt_history (
  id bigint generated by default as identity primary key,
  grammar_assignment_id bigint not null references public.grammar_assignments(id) on delete cascade,
  student_id bigint not null references public.students(id) on delete cascade,
  attempt_number integer not null check (attempt_number > 0),
  answers jsonb not null default '{}'::jsonb,
  score integer not null check (score >= 0),
  max_score integer not null check (max_score > 0 and score <= max_score),
  completed_at timestamptz not null default now(),
  unique (grammar_assignment_id, student_id, attempt_number)
);

create index grammar_attempt_history_assignment_idx
  on public.grammar_attempt_history(grammar_assignment_id, student_id, attempt_number desc);
create index grammar_attempt_history_student_idx
  on public.grammar_attempt_history(student_id, completed_at desc);

alter table public.grammar_attempt_history enable row level security;
revoke all on table public.grammar_attempt_history from public, anon;
grant select on table public.grammar_attempt_history to authenticated;

create policy grammar_attempt_history_students_read_own
on public.grammar_attempt_history
for select
to authenticated
using (
  exists (
    select 1 from public.students s
    where s.id=grammar_attempt_history.student_id
      and s.user_id=(select auth.uid())
  )
);

create policy grammar_attempt_history_parents_read_own_children
on public.grammar_attempt_history
for select
to authenticated
using (
  exists (
    select 1 from public.parent_students ps
    where ps.student_id=grammar_attempt_history.student_id
      and ps.parent_id=(select auth.uid())
  )
);

create policy grammar_attempt_history_teachers_read_own_classes
on public.grammar_attempt_history
for select
to authenticated
using (
  exists (
    select 1
    from public.students s
    join public.teacher_classes tc on tc.class_id=s.class_id
    join public.classes c on c.id=s.class_id
    join public.school_memberships sm
      on sm.user_id=(select auth.uid())
     and sm.school_id=c.school_id
     and sm.role='teacher'
     and sm.active=true
    where s.id=grammar_attempt_history.student_id
      and tc.teacher_id=(select auth.uid())
  )
);

create policy grammar_attempt_history_leaders_admins_read_school
on public.grammar_attempt_history
for select
to authenticated
using (
  exists (
    select 1
    from public.students s
    join public.classes c on c.id=s.class_id
    join public.school_memberships sm
      on sm.school_id=c.school_id
     and sm.user_id=(select auth.uid())
     and sm.role in ('admin','leader')
     and sm.active=true
    where s.id=grammar_attempt_history.student_id
  )
);

create or replace function public.save_student_grammar_attempt_session(
  p_session_token text,
  p_assignment_id bigint,
  p_answers jsonb,
  p_score integer,
  p_max_score integer
)
returns jsonb
language plpgsql
security definer
set search_path='public','private'
as $$
declare
  s public.students;
  saved public.grammar_attempts;
  v_seen_question_keys text[] := '{}'::text[];
begin
  select * into s
  from public.students
  where id=private.student_id_for_session(p_session_token);

  if s.id is null then
    return jsonb_build_object('ok',false,'error','invalid_session');
  end if;

  if p_max_score<=0 or p_score<0 or p_score>p_max_score then
    return jsonb_build_object('ok',false,'error','invalid_score');
  end if;

  if not exists(
    select 1
    from public.grammar_assignments ga
    where ga.id=p_assignment_id
      and ga.class_id=s.class_id
      and (
        not exists(
          select 1
          from public.grammar_assignment_students gas0
          where gas0.grammar_assignment_id=ga.id
        )
        or exists(
          select 1
          from public.grammar_assignment_students gas
          where gas.grammar_assignment_id=ga.id
            and gas.student_id=s.id
        )
      )
  ) then
    return jsonb_build_object('ok',false,'error','assignment_not_available');
  end if;

  select coalesce(array_agg(distinct q.question_key), '{}'::text[])
  into v_seen_question_keys
  from (
    select (entry.value->>'question') || '::' || (entry.value->>'correctAnswer') as question_key
    from jsonb_each(coalesce(p_answers,'{}'::jsonb)) entry
    where coalesce(entry.value->>'question','')<>''
      and coalesce(entry.value->>'correctAnswer','')<>''
  ) q;

  insert into public.grammar_attempts(
    grammar_assignment_id,
    student_id,
    answers,
    score,
    max_score,
    completed_at,
    updated_at,
    attempt_count,
    best_score,
    best_max_score,
    seen_question_keys
  )
  values(
    p_assignment_id,
    s.id,
    coalesce(p_answers,'{}'::jsonb),
    p_score,
    p_max_score,
    now(),
    now(),
    1,
    p_score,
    p_max_score,
    v_seen_question_keys
  )
  on conflict(grammar_assignment_id,student_id)
  do update set
    answers=excluded.answers,
    score=excluded.score,
    max_score=excluded.max_score,
    completed_at=excluded.completed_at,
    updated_at=excluded.updated_at,
    attempt_count=public.grammar_attempts.attempt_count+1,
    best_score=case
      when public.grammar_attempts.best_max_score=0
        or excluded.score::numeric/excluded.max_score>public.grammar_attempts.best_score::numeric/public.grammar_attempts.best_max_score
      then excluded.score
      else public.grammar_attempts.best_score
    end,
    best_max_score=case
      when public.grammar_attempts.best_max_score=0
        or excluded.score::numeric/excluded.max_score>public.grammar_attempts.best_score::numeric/public.grammar_attempts.best_max_score
      then excluded.max_score
      else public.grammar_attempts.best_max_score
    end,
    seen_question_keys=(
      select coalesce(array_agg(distinct x.question_key), '{}'::text[])
      from unnest(public.grammar_attempts.seen_question_keys || excluded.seen_question_keys) as x(question_key)
    )
  returning * into saved;

  insert into public.grammar_attempt_history(
    grammar_assignment_id,
    student_id,
    attempt_number,
    answers,
    score,
    max_score,
    completed_at
  ) values (
    p_assignment_id,
    s.id,
    saved.attempt_count,
    coalesce(p_answers,'{}'::jsonb),
    p_score,
    p_max_score,
    saved.completed_at
  );

  return jsonb_build_object(
    'ok',true,
    'score',saved.score,
    'max_score',saved.max_score,
    'attempts',saved.attempt_count,
    'best_score',saved.best_score,
    'best_max_score',saved.best_max_score,
    'completed',saved.best_max_score>0 and saved.best_score=saved.best_max_score,
    'seen_question_keys',saved.seen_question_keys
  );
end;
$$;

create or replace function public.teacher_grammar_results(p_assignment_id bigint)
returns jsonb
language plpgsql
security definer
set search_path='public','private'
as $$
declare
  v_result jsonb;
  v_allowed boolean;
begin
  if auth.uid() is null then
    return jsonb_build_object('ok',false,'error','not_authenticated');
  end if;

  select exists(
    select 1
    from public.grammar_assignments a
    join public.classes c on c.id=a.class_id
    where a.id=p_assignment_id
      and (
        exists(
          select 1
          from public.teacher_classes tc
          join public.school_memberships sm
            on sm.user_id=tc.teacher_id
           and sm.school_id=c.school_id
           and sm.role='teacher'
           and sm.active=true
          where tc.class_id=a.class_id and tc.teacher_id=auth.uid()
        )
        or exists(
          select 1 from public.school_memberships sm
          where sm.user_id=auth.uid()
            and sm.school_id=c.school_id
            and sm.role in ('admin','leader')
            and sm.active=true
        )
      )
  ) into v_allowed;

  if not coalesce(v_allowed,false) then
    return jsonb_build_object('ok',false,'error','forbidden');
  end if;

  select jsonb_build_object(
    'ok',true,
    'history_started_at',(select min(h.completed_at) from public.grammar_attempt_history h where h.grammar_assignment_id=p_assignment_id),
    'results',coalesce(jsonb_agg(jsonb_build_object(
      'student_id',s.id,
      'student_name',s.name,
      'completed',(ga.student_id is not null),
      'score',ga.score,
      'max_score',ga.max_score,
      'completed_at',ga.completed_at,
      'answers',ga.answers,
      'attempts',coalesce(ga.attempt_count,0),
      'best_score',ga.best_score,
      'best_max_score',ga.best_max_score,
      'mastered',coalesce(ga.best_max_score>0 and ga.best_score=ga.best_max_score,false),
      'attempt_history',coalesce((
        select jsonb_agg(jsonb_build_object(
          'attempt_number',h.attempt_number,
          'score',h.score,
          'max_score',h.max_score,
          'completed_at',h.completed_at,
          'answers',h.answers
        ) order by h.attempt_number)
        from public.grammar_attempt_history h
        where h.grammar_assignment_id=a.id
          and h.student_id=s.id
      ),'[]'::jsonb)
    ) order by s.name),'[]'::jsonb)
  ) into v_result
  from public.grammar_assignments a
  join public.students s on s.class_id=a.class_id
  left join public.grammar_assignment_students gas
    on gas.grammar_assignment_id=a.id and gas.student_id=s.id
  left join public.grammar_attempts ga
    on ga.grammar_assignment_id=a.id and ga.student_id=s.id
  where a.id=p_assignment_id
    and (
      not exists(select 1 from public.grammar_assignment_students z where z.grammar_assignment_id=a.id)
      or gas.student_id=s.id
    );

  return coalesce(v_result,jsonb_build_object('ok',true,'results','[]'::jsonb));
end;
$$;

revoke all on function public.save_student_grammar_attempt_session(text,bigint,jsonb,integer,integer) from public,authenticated;
grant execute on function public.save_student_grammar_attempt_session(text,bigint,jsonb,integer,integer) to anon,service_role;
revoke all on function public.teacher_grammar_results(bigint) from public,anon;
grant execute on function public.teacher_grammar_results(bigint) to authenticated,service_role;
