create table if not exists public.reading_exam_assignments (
  id bigint generated by default as identity primary key,
  class_id bigint not null references public.classes(id) on delete cascade,
  title text not null default 'Træn læseprøven',
  time_limit_minutes integer null,
  question_count integer not null default 50,
  created_at timestamptz not null default now(),
  constraint reading_exam_time_limit_check check (time_limit_minutes is null or time_limit_minutes between 5 and 180),
  constraint reading_exam_question_count_check check (question_count between 20 and 80)
);

create table if not exists public.reading_exam_assignment_students (
  id bigint generated by default as identity primary key,
  reading_exam_assignment_id bigint not null references public.reading_exam_assignments(id) on delete cascade,
  student_id bigint not null references public.students(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique(reading_exam_assignment_id, student_id)
);

create table if not exists public.reading_exam_sessions (
  id bigint generated by default as identity primary key,
  reading_exam_assignment_id bigint not null references public.reading_exam_assignments(id) on delete cascade,
  student_id bigint not null references public.students(id) on delete cascade,
  question_seed integer not null,
  started_at timestamptz not null default now(),
  submitted_at timestamptz null,
  unique(reading_exam_assignment_id, student_id)
);

create table if not exists public.reading_exam_attempts (
  id bigint generated by default as identity primary key,
  reading_exam_assignment_id bigint not null references public.reading_exam_assignments(id) on delete cascade,
  student_id bigint not null references public.students(id) on delete cascade,
  answers jsonb not null default '{}'::jsonb,
  score integer not null,
  max_score integer not null,
  completed_at timestamptz not null default now(),
  unique(reading_exam_assignment_id, student_id),
  constraint reading_exam_attempt_score_check check (max_score > 0 and score >= 0 and score <= max_score)
);

create index if not exists reading_exam_assignments_class_idx on public.reading_exam_assignments(class_id);
create index if not exists reading_exam_assignment_students_student_idx on public.reading_exam_assignment_students(student_id);
create index if not exists reading_exam_sessions_student_idx on public.reading_exam_sessions(student_id);
create index if not exists reading_exam_attempts_student_idx on public.reading_exam_attempts(student_id);

alter table public.reading_exam_assignments enable row level security;
alter table public.reading_exam_assignment_students enable row level security;
alter table public.reading_exam_sessions enable row level security;
alter table public.reading_exam_attempts enable row level security;

revoke all on public.reading_exam_assignments from anon, authenticated;
revoke all on public.reading_exam_assignment_students from anon, authenticated;
revoke all on public.reading_exam_sessions from anon, authenticated;
revoke all on public.reading_exam_attempts from anon, authenticated;
grant all on public.reading_exam_assignments to service_role;
grant all on public.reading_exam_assignment_students to service_role;
grant all on public.reading_exam_sessions to service_role;
grant all on public.reading_exam_attempts to service_role;

create or replace function public.create_reading_exam_assignment(p_class_id bigint,p_title text default 'Træn læseprøven',p_time_limit_minutes integer default null,p_student_ids bigint[] default null)
returns jsonb language plpgsql security definer set search_path=public,private as $$
declare v_school_id bigint; v_allowed boolean; v_assignment public.reading_exam_assignments; v_invalid_students integer;
begin
  if auth.uid() is null then return jsonb_build_object('ok',false,'error','not_authenticated'); end if;
  select c.school_id into v_school_id from public.classes c where c.id=p_class_id;
  if v_school_id is null then return jsonb_build_object('ok',false,'error','class_not_found'); end if;
  select (public.has_school_role(v_school_id,'admin') or (public.has_school_role(v_school_id,'teacher') and exists(select 1 from public.teacher_classes tc where tc.class_id=p_class_id and tc.teacher_id=auth.uid()))) into v_allowed;
  if not coalesce(v_allowed,false) then return jsonb_build_object('ok',false,'error','forbidden'); end if;
  if p_time_limit_minutes is not null and (p_time_limit_minutes<5 or p_time_limit_minutes>180) then return jsonb_build_object('ok',false,'error','invalid_time_limit'); end if;
  if p_student_ids is not null and cardinality(p_student_ids)>0 then
    select count(*) into v_invalid_students from unnest(p_student_ids) x(student_id) where not exists(select 1 from public.students s where s.id=x.student_id and s.class_id=p_class_id);
    if v_invalid_students>0 then return jsonb_build_object('ok',false,'error','invalid_recipients'); end if;
  end if;
  insert into public.reading_exam_assignments(class_id,title,time_limit_minutes,question_count) values(p_class_id,coalesce(nullif(trim(p_title),''),'Træn læseprøven'),p_time_limit_minutes,50) returning * into v_assignment;
  if p_student_ids is not null and cardinality(p_student_ids)>0 then insert into public.reading_exam_assignment_students(reading_exam_assignment_id,student_id) select v_assignment.id,student_id from (select distinct unnest(p_student_ids) student_id) q; end if;
  return jsonb_build_object('ok',true,'assignment_id',v_assignment.id);
end; $$;

create or replace function public.delete_reading_exam_assignment(p_assignment_id bigint)
returns jsonb language plpgsql security definer set search_path=public,private as $$
declare v_school_id bigint; v_class_id bigint; v_allowed boolean;
begin
  if auth.uid() is null then return jsonb_build_object('ok',false,'error','not_authenticated'); end if;
  select a.class_id,c.school_id into v_class_id,v_school_id from public.reading_exam_assignments a join public.classes c on c.id=a.class_id where a.id=p_assignment_id;
  if v_school_id is null then return jsonb_build_object('ok',false,'error','not_found'); end if;
  select (public.has_school_role(v_school_id,'admin') or (public.has_school_role(v_school_id,'teacher') and exists(select 1 from public.teacher_classes tc where tc.class_id=v_class_id and tc.teacher_id=auth.uid()))) into v_allowed;
  if not coalesce(v_allowed,false) then return jsonb_build_object('ok',false,'error','forbidden'); end if;
  if exists(select 1 from public.reading_exam_sessions s where s.reading_exam_assignment_id=p_assignment_id) then return jsonb_build_object('ok',false,'error','started_and_locked'); end if;
  delete from public.reading_exam_assignments where id=p_assignment_id;
  return jsonb_build_object('ok',true);
end; $$;

create or replace function public.student_session_reading_exam_assignments(p_session_token text)
returns jsonb language plpgsql security definer set search_path=public,private as $$
declare s public.students;
begin
  select * into s from public.students where id=private.student_id_for_session(p_session_token);
  if s.id is null then return jsonb_build_object('ok',false,'error','invalid_session'); end if;
  return jsonb_build_object('ok',true,'assignments',coalesce((select jsonb_agg(jsonb_build_object('id',a.id,'title',a.title,'time_limit_minutes',a.time_limit_minutes,'question_count',a.question_count,'created_at',a.created_at,'started',sess.id is not null,'started_at',sess.started_at,'submitted',att.id is not null,'submitted_at',sess.submitted_at,'score',att.score,'max_score',att.max_score) order by a.created_at desc) from public.reading_exam_assignments a left join public.reading_exam_sessions sess on sess.reading_exam_assignment_id=a.id and sess.student_id=s.id left join public.reading_exam_attempts att on att.reading_exam_assignment_id=a.id and att.student_id=s.id where a.class_id=s.class_id and (not exists(select 1 from public.reading_exam_assignment_students x where x.reading_exam_assignment_id=a.id) or exists(select 1 from public.reading_exam_assignment_students x where x.reading_exam_assignment_id=a.id and x.student_id=s.id))),'[]'::jsonb));
end; $$;

create or replace function public.start_student_reading_exam_session(p_session_token text,p_assignment_id bigint)
returns jsonb language plpgsql security definer set search_path=public,private as $$
declare s public.students; a public.reading_exam_assignments; sess public.reading_exam_sessions; v_remaining integer;
begin
  select * into s from public.students where id=private.student_id_for_session(p_session_token); if s.id is null then return jsonb_build_object('ok',false,'error','invalid_session'); end if;
  select * into a from public.reading_exam_assignments x where x.id=p_assignment_id and x.class_id=s.class_id and (not exists(select 1 from public.reading_exam_assignment_students z where z.reading_exam_assignment_id=x.id) or exists(select 1 from public.reading_exam_assignment_students z where z.reading_exam_assignment_id=x.id and z.student_id=s.id));
  if a.id is null then return jsonb_build_object('ok',false,'error','assignment_not_available'); end if;
  insert into public.reading_exam_sessions(reading_exam_assignment_id,student_id,question_seed) values(a.id,s.id,floor(random()*2147483000)::integer+1) on conflict(reading_exam_assignment_id,student_id) do nothing;
  select * into sess from public.reading_exam_sessions where reading_exam_assignment_id=a.id and student_id=s.id;
  if a.time_limit_minutes is not null then v_remaining:=greatest(0,(extract(epoch from (sess.started_at+make_interval(mins=>a.time_limit_minutes)-now())))::integer); else v_remaining:=null; end if;
  return jsonb_build_object('ok',true,'question_seed',sess.question_seed,'started_at',sess.started_at,'submitted_at',sess.submitted_at,'time_limit_minutes',a.time_limit_minutes,'remaining_seconds',v_remaining,'question_count',a.question_count,'already_submitted',sess.submitted_at is not null);
end; $$;

create or replace function public.save_student_reading_exam_attempt(p_session_token text,p_assignment_id bigint,p_answers jsonb,p_score integer,p_max_score integer)
returns jsonb language plpgsql security definer set search_path=public,private as $$
declare s public.students; a public.reading_exam_assignments; sess public.reading_exam_sessions; att public.reading_exam_attempts; v_elapsed integer; v_timed_out boolean:=false;
begin
  select * into s from public.students where id=private.student_id_for_session(p_session_token); if s.id is null then return jsonb_build_object('ok',false,'error','invalid_session'); end if;
  if p_max_score<=0 or p_score<0 or p_score>p_max_score then return jsonb_build_object('ok',false,'error','invalid_score'); end if;
  select * into a from public.reading_exam_assignments x where x.id=p_assignment_id and x.class_id=s.class_id and (not exists(select 1 from public.reading_exam_assignment_students z where z.reading_exam_assignment_id=x.id) or exists(select 1 from public.reading_exam_assignment_students z where z.reading_exam_assignment_id=x.id and z.student_id=s.id)); if a.id is null then return jsonb_build_object('ok',false,'error','assignment_not_available'); end if;
  select * into sess from public.reading_exam_sessions where reading_exam_assignment_id=a.id and student_id=s.id for update; if sess.id is null then return jsonb_build_object('ok',false,'error','not_started'); end if;
  if sess.submitted_at is not null then select * into att from public.reading_exam_attempts where reading_exam_assignment_id=a.id and student_id=s.id; return jsonb_build_object('ok',true,'already_submitted',true,'score',att.score,'max_score',att.max_score,'submitted_at',sess.submitted_at); end if;
  v_elapsed:=greatest(0,extract(epoch from (now()-sess.started_at))::integer); v_timed_out:=a.time_limit_minutes is not null and v_elapsed>a.time_limit_minutes*60;
  insert into public.reading_exam_attempts(reading_exam_assignment_id,student_id,answers,score,max_score,completed_at) values(a.id,s.id,coalesce(p_answers,'{}'::jsonb),p_score,p_max_score,now()) on conflict(reading_exam_assignment_id,student_id) do update set answers=excluded.answers,score=excluded.score,max_score=excluded.max_score,completed_at=excluded.completed_at returning * into att;
  update public.reading_exam_sessions set submitted_at=now() where id=sess.id returning * into sess;
  return jsonb_build_object('ok',true,'score',att.score,'max_score',att.max_score,'submitted_at',sess.submitted_at,'elapsed_seconds',v_elapsed,'timed_out',v_timed_out);
end; $$;

create or replace function public.teacher_reading_exam_results(p_assignment_id bigint)
returns jsonb language plpgsql security definer set search_path=public,private as $$
declare v_school_id bigint; v_class_id bigint; v_allowed boolean; v_time_limit integer; v_result jsonb;
begin
  if auth.uid() is null then return jsonb_build_object('ok',false,'error','not_authenticated'); end if;
  select a.class_id,c.school_id,a.time_limit_minutes into v_class_id,v_school_id,v_time_limit from public.reading_exam_assignments a join public.classes c on c.id=a.class_id where a.id=p_assignment_id; if v_school_id is null then return jsonb_build_object('ok',false,'error','not_found'); end if;
  select (public.has_school_role(v_school_id,'admin') or (public.has_school_role(v_school_id,'teacher') and exists(select 1 from public.teacher_classes tc where tc.class_id=v_class_id and tc.teacher_id=auth.uid()))) into v_allowed; if not coalesce(v_allowed,false) then return jsonb_build_object('ok',false,'error','forbidden'); end if;
  select jsonb_build_object('ok',true,'time_limit_minutes',v_time_limit,'results',coalesce(jsonb_agg(jsonb_build_object('student_id',s.id,'student_name',s.name,'started',sess.id is not null,'started_at',sess.started_at,'submitted',att.id is not null,'submitted_at',sess.submitted_at,'score',att.score,'max_score',att.max_score,'elapsed_seconds',case when sess.id is null then null else extract(epoch from (coalesce(sess.submitted_at,now())-sess.started_at))::integer end,'timed_out',case when v_time_limit is null or sess.id is null then false else extract(epoch from (coalesce(sess.submitted_at,now())-sess.started_at))>v_time_limit*60 end,'answers',att.answers) order by s.name),'[]'::jsonb)) into v_result from public.students s left join public.reading_exam_assignment_students link on link.reading_exam_assignment_id=p_assignment_id and link.student_id=s.id left join public.reading_exam_sessions sess on sess.reading_exam_assignment_id=p_assignment_id and sess.student_id=s.id left join public.reading_exam_attempts att on att.reading_exam_assignment_id=p_assignment_id and att.student_id=s.id where s.class_id=v_class_id and (not exists(select 1 from public.reading_exam_assignment_students z where z.reading_exam_assignment_id=p_assignment_id) or link.student_id=s.id);
  return coalesce(v_result,jsonb_build_object('ok',true,'time_limit_minutes',v_time_limit,'results','[]'::jsonb));
end; $$;

create or replace function public.teacher_reading_exam_assignments(p_class_id bigint)
returns jsonb language plpgsql security definer set search_path=public,private as $$
declare v_school_id bigint; v_allowed boolean;
begin
  if auth.uid() is null then return jsonb_build_object('ok',false,'error','not_authenticated'); end if;
  select c.school_id into v_school_id from public.classes c where c.id=p_class_id;
  if v_school_id is null then return jsonb_build_object('ok',false,'error','class_not_found'); end if;
  select (public.has_school_role(v_school_id,'admin') or (public.has_school_role(v_school_id,'teacher') and exists(select 1 from public.teacher_classes tc where tc.class_id=p_class_id and tc.teacher_id=auth.uid()))) into v_allowed;
  if not coalesce(v_allowed,false) then return jsonb_build_object('ok',false,'error','forbidden'); end if;
  return jsonb_build_object('ok',true,'assignments',coalesce((select jsonb_agg(jsonb_build_object('id',a.id,'title',a.title,'time_limit_minutes',a.time_limit_minutes,'question_count',a.question_count,'created_at',a.created_at,'recipient_count',case when exists(select 1 from public.reading_exam_assignment_students l0 where l0.reading_exam_assignment_id=a.id) then (select count(*) from public.reading_exam_assignment_students l where l.reading_exam_assignment_id=a.id) else (select count(*) from public.students s where s.class_id=a.class_id) end,'started_count',(select count(*) from public.reading_exam_sessions s where s.reading_exam_assignment_id=a.id),'submitted_count',(select count(*) from public.reading_exam_attempts x where x.reading_exam_assignment_id=a.id),'locked',exists(select 1 from public.reading_exam_sessions s where s.reading_exam_assignment_id=a.id)) order by a.created_at desc) from public.reading_exam_assignments a where a.class_id=p_class_id),'[]'::jsonb));
end; $$;

revoke execute on function public.create_reading_exam_assignment(bigint,text,integer,bigint[]) from public,anon,authenticated;
grant execute on function public.create_reading_exam_assignment(bigint,text,integer,bigint[]) to authenticated,service_role;
revoke execute on function public.delete_reading_exam_assignment(bigint) from public,anon,authenticated;
grant execute on function public.delete_reading_exam_assignment(bigint) to authenticated,service_role;
revoke execute on function public.teacher_reading_exam_results(bigint) from public,anon,authenticated;
grant execute on function public.teacher_reading_exam_results(bigint) to authenticated,service_role;
revoke execute on function public.teacher_reading_exam_assignments(bigint) from public,anon,authenticated;
grant execute on function public.teacher_reading_exam_assignments(bigint) to authenticated,service_role;
revoke execute on function public.student_session_reading_exam_assignments(text) from public,authenticated,anon;
grant execute on function public.student_session_reading_exam_assignments(text) to anon,service_role;
revoke execute on function public.start_student_reading_exam_session(text,bigint) from public,authenticated,anon;
grant execute on function public.start_student_reading_exam_session(text,bigint) to anon,service_role;
revoke execute on function public.save_student_reading_exam_attempt(text,bigint,jsonb,integer,integer) from public,authenticated,anon;
grant execute on function public.save_student_reading_exam_attempt(text,bigint,jsonb,integer,integer) to anon,service_role;
