-- Student authentication phase 1: short code is used only to start a limited session.
-- Session tokens are random, stored only as hashes, and expire after 12 hours.

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;
grant usage on schema private to postgres, service_role;

create table if not exists private.student_sessions (
  id bigint generated by default as identity primary key,
  student_id bigint not null references public.students(id) on delete cascade,
  token_hash text not null unique,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  last_seen_at timestamptz not null default now(),
  revoked_at timestamptz null
);
create index if not exists idx_private_student_sessions_student_id on private.student_sessions(student_id);
create index if not exists idx_private_student_sessions_expires_at on private.student_sessions(expires_at);
revoke all on private.student_sessions from public, anon, authenticated;

create or replace function private.student_id_for_session(p_session_token text)
returns bigint language plpgsql security definer set search_path='private','public','extensions' as $$
declare v_hash text; v_student_id bigint;
begin
  if p_session_token is null or length(trim(p_session_token))<40 then return null; end if;
  v_hash:=encode(extensions.digest(trim(p_session_token),'sha256'),'hex');
  select ss.student_id into v_student_id from private.student_sessions ss
  where ss.token_hash=v_hash and ss.revoked_at is null and ss.expires_at>now() limit 1;
  if v_student_id is not null then
    update private.student_sessions set last_seen_at=now()
    where token_hash=v_hash and last_seen_at<now()-interval '10 minutes';
  end if;
  return v_student_id;
end; $$;
revoke execute on function private.student_id_for_session(text) from public,anon,authenticated;

create or replace function public.student_start_session(p_access_code text)
returns jsonb language plpgsql security definer set search_path='public','private','extensions' as $$
declare s public.students; v_token text; v_hash text; v_expires timestamptz;
begin
  select * into s from public.students where upper(access_code)=upper(trim(p_access_code)) limit 1;
  if s.id is null then return jsonb_build_object('ok',false,'error','invalid_code'); end if;
  delete from private.student_sessions where student_id=s.id and (expires_at<=now() or revoked_at is not null);
  v_token:=encode(extensions.gen_random_bytes(32),'hex');
  v_hash:=encode(extensions.digest(v_token,'sha256'),'hex');
  v_expires:=now()+interval '12 hours';
  insert into private.student_sessions(student_id,token_hash,expires_at) values(s.id,v_hash,v_expires);
  return jsonb_build_object('ok',true,'session_token',v_token,'expires_at',v_expires,'student_id',s.id,'student_name',s.name,'class_id',s.class_id);
end; $$;

create or replace function public.student_end_session(p_session_token text)
returns jsonb language plpgsql security definer set search_path='public','private','extensions' as $$
declare v_hash text; v_count integer;
begin
  if p_session_token is null or length(trim(p_session_token))<40 then return jsonb_build_object('ok',true); end if;
  v_hash:=encode(extensions.digest(trim(p_session_token),'sha256'),'hex');
  update private.student_sessions set revoked_at=now() where token_hash=v_hash and revoked_at is null;
  get diagnostics v_count=row_count;
  return jsonb_build_object('ok',true,'revoked',v_count>0);
end; $$;

create or replace function public.student_session_data(p_session_token text)
returns jsonb language plpgsql security definer set search_path='public','private' as $$
declare v_student_id bigint; s public.students; c public.classes; v_result jsonb;
begin
  v_student_id:=private.student_id_for_session(p_session_token);
  if v_student_id is null then return jsonb_build_object('ok',false,'error','invalid_session'); end if;
  select * into s from public.students where id=v_student_id;
  select * into c from public.classes where id=s.class_id;
  if s.id is null or c.id is null then return jsonb_build_object('ok',false,'error','student_not_found'); end if;
  select jsonb_build_object(
    'ok',true,
    'student',jsonb_build_object('id',s.id,'name',s.name,'class_id',s.class_id),
    'class',jsonb_build_object('id',c.id,'name',c.name),
    'assignments',coalesce((select jsonb_agg(jsonb_build_object('id',a.id,'title',a.title,'type',a.type,'instructions',a.instructions) order by a.id)
      from public.assignments a where a.class_id=s.class_id and (not exists(select 1 from public.assignment_students ast0 where ast0.assignment_id=a.id) or exists(select 1 from public.assignment_students ast where ast.assignment_id=a.id and ast.student_id=s.id))),'[]'::jsonb),
    'drafts',coalesce((select jsonb_agg(jsonb_build_object('assignment_id',d.assignment_id,'content',d.content)) from public.drafts d where d.student_id=s.id),'[]'::jsonb)
  ) into v_result;
  return v_result;
end; $$;

create or replace function public.student_session_feedback(p_session_token text)
returns jsonb language plpgsql security definer set search_path='public','private' as $$
declare v_student_id bigint; v_result jsonb;
begin
  v_student_id:=private.student_id_for_session(p_session_token);
  if v_student_id is null then return jsonb_build_object('ok',false,'error','invalid_session','feedback','[]'::jsonb); end if;
  select jsonb_build_object('ok',true,'feedback',coalesce(jsonb_agg(jsonb_build_object('assignment_id',f.assignment_id,'text',f.text) order by f.assignment_id) filter(where f.id is not null),'[]'::jsonb)) into v_result
  from public.feedback f where f.student_id=v_student_id;
  return v_result;
end; $$;

create or replace function public.student_session_grammar_assignments(p_session_token text)
returns jsonb language plpgsql security definer set search_path='public','private' as $$
declare s public.students;
begin
  select * into s from public.students where id=private.student_id_for_session(p_session_token);
  if s.id is null then return jsonb_build_object('ok',false,'error','invalid_session'); end if;
  return jsonb_build_object('ok',true,'assignments',coalesce((
    select jsonb_agg(jsonb_build_object('id',ga.id,'area',ga.area,'topic',ga.topic,'level',ga.level,'title',ga.title,'completed',a.completed_at is not null,'score',a.score,'max_score',a.max_score) order by ga.created_at desc)
    from public.grammar_assignments ga left join public.grammar_attempts a on a.grammar_assignment_id=ga.id and a.student_id=s.id
    where ga.class_id=s.class_id and (not exists(select 1 from public.grammar_assignment_students gas0 where gas0.grammar_assignment_id=ga.id) or exists(select 1 from public.grammar_assignment_students gas where gas.grammar_assignment_id=ga.id and gas.student_id=s.id))
  ),'[]'::jsonb));
end; $$;

create or replace function public.save_student_draft_session(p_session_token text,p_assignment_id bigint,p_content jsonb)
returns jsonb language plpgsql security definer set search_path='public','private' as $$
declare v_student_id bigint; v_class_id bigint;
begin
  v_student_id:=private.student_id_for_session(p_session_token);
  if v_student_id is null then return jsonb_build_object('ok',false,'error','invalid_session'); end if;
  select class_id into v_class_id from public.students where id=v_student_id;
  if not exists(select 1 from public.assignments a where a.id=p_assignment_id and a.class_id=v_class_id and (not exists(select 1 from public.assignment_students ast0 where ast0.assignment_id=a.id) or exists(select 1 from public.assignment_students ast where ast.assignment_id=a.id and ast.student_id=v_student_id))) then
    return jsonb_build_object('ok',false,'error','assignment_not_available');
  end if;
  insert into public.drafts(student_id,assignment_id,content,updated_at) values(v_student_id,p_assignment_id,coalesce(p_content,'[]'::jsonb),now())
  on conflict(student_id,assignment_id) do update set content=excluded.content,updated_at=now();
  return jsonb_build_object('ok',true);
end; $$;

create or replace function public.save_student_grammar_attempt_session(p_session_token text,p_assignment_id bigint,p_answers jsonb,p_score integer,p_max_score integer)
returns jsonb language plpgsql security definer set search_path='public','private' as $$
declare s public.students;
begin
  select * into s from public.students where id=private.student_id_for_session(p_session_token);
  if s.id is null then return jsonb_build_object('ok',false,'error','invalid_session'); end if;
  if p_max_score<=0 or p_score<0 or p_score>p_max_score then return jsonb_build_object('ok',false,'error','invalid_score'); end if;
  if not exists(select 1 from public.grammar_assignments ga where ga.id=p_assignment_id and ga.class_id=s.class_id and (not exists(select 1 from public.grammar_assignment_students gas0 where gas0.grammar_assignment_id=ga.id) or exists(select 1 from public.grammar_assignment_students gas where gas.grammar_assignment_id=ga.id and gas.student_id=s.id))) then
    return jsonb_build_object('ok',false,'error','assignment_not_available');
  end if;
  insert into public.grammar_attempts(grammar_assignment_id,student_id,answers,score,max_score,completed_at,updated_at)
  values(p_assignment_id,s.id,coalesce(p_answers,'{}'::jsonb),p_score,p_max_score,now(),now())
  on conflict(grammar_assignment_id,student_id) do update set answers=excluded.answers,score=excluded.score,max_score=excluded.max_score,completed_at=excluded.completed_at,updated_at=excluded.updated_at;
  return jsonb_build_object('ok',true,'score',p_score,'max_score',p_max_score);
end; $$;

create or replace function public.get_student_training_progress_session(p_session_token text)
returns table(subject_id text,area_id text,skill_id text,level_id text,attempts integer,best_score integer,last_score integer,max_score integer,last_attempt_at timestamptz)
language plpgsql security definer set search_path='public','private' as $$
declare v_student_id bigint;
begin
  v_student_id:=private.student_id_for_session(p_session_token);
  if v_student_id is null then return; end if;
  return query select p.subject_id,p.area_id,p.skill_id,p.level_id,p.attempts,p.best_score,p.last_score,p.max_score,p.last_attempt_at
  from public.student_training_progress p where p.student_id=v_student_id order by p.last_attempt_at desc;
end; $$;

create or replace function public.save_student_training_attempt_session(p_session_token text,p_subject_id text,p_area_id text,p_skill_id text,p_level_id text,p_answers jsonb,p_score integer,p_max_score integer)
returns jsonb language plpgsql security definer set search_path='public','private' as $$
declare v_student_id bigint; saved public.student_training_progress;
begin
  v_student_id:=private.student_id_for_session(p_session_token);
  if v_student_id is null then return jsonb_build_object('ok',false,'error','invalid_session'); end if;
  if p_subject_id is null or trim(p_subject_id)='' or p_area_id is null or trim(p_area_id)='' or p_skill_id is null or trim(p_skill_id)='' or p_level_id is null or trim(p_level_id)='' then return jsonb_build_object('ok',false,'error','invalid_training_key'); end if;
  if p_max_score<=0 or p_score<0 or p_score>p_max_score then return jsonb_build_object('ok',false,'error','invalid_score'); end if;
  insert into public.student_training_progress(student_id,subject_id,area_id,skill_id,level_id,attempts,best_score,last_score,max_score,last_answers,first_attempt_at,last_attempt_at,updated_at)
  values(v_student_id,trim(p_subject_id),trim(p_area_id),trim(p_skill_id),trim(p_level_id),1,p_score,p_score,p_max_score,coalesce(p_answers,'{}'::jsonb),now(),now(),now())
  on conflict(student_id,subject_id,area_id,skill_id,level_id) do update set attempts=public.student_training_progress.attempts+1,best_score=greatest(public.student_training_progress.best_score,excluded.last_score),last_score=excluded.last_score,max_score=excluded.max_score,last_answers=excluded.last_answers,last_attempt_at=now(),updated_at=now()
  returning * into saved;
  return jsonb_build_object('ok',true,'student_id',saved.student_id,'subject_id',saved.subject_id,'area_id',saved.area_id,'skill_id',saved.skill_id,'level_id',saved.level_id,'attempts',saved.attempts,'best_score',saved.best_score,'last_score',saved.last_score,'max_score',saved.max_score);
end; $$;

-- Compatibility fix for the currently deployed student writing UI.
create or replace function public.save_student_draft(p_access_code text,p_assignment_id bigint,p_content jsonb)
returns void language plpgsql security definer set search_path='public' as $$
declare v_student_id bigint; v_class_id bigint;
begin
  select s.id,s.class_id into v_student_id,v_class_id from public.students s where upper(s.access_code)=upper(trim(p_access_code)) limit 1;
  if v_student_id is null then raise exception 'Invalid student access code'; end if;
  if not exists(select 1 from public.assignments a where a.id=p_assignment_id and a.class_id=v_class_id and (not exists(select 1 from public.assignment_students ast0 where ast0.assignment_id=a.id) or exists(select 1 from public.assignment_students ast where ast.assignment_id=a.id and ast.student_id=v_student_id))) then raise exception 'Assignment is not available to this student'; end if;
  insert into public.drafts(student_id,assignment_id,content,updated_at) values(v_student_id,p_assignment_id,coalesce(p_content,'[]'::jsonb),now())
  on conflict(student_id,assignment_id) do update set content=excluded.content,updated_at=now();
end; $$;

revoke execute on function public.student_start_session(text) from public;
revoke execute on function public.student_end_session(text) from public;
revoke execute on function public.student_session_data(text) from public;
revoke execute on function public.student_session_feedback(text) from public;
revoke execute on function public.student_session_grammar_assignments(text) from public;
revoke execute on function public.save_student_draft_session(text,bigint,jsonb) from public;
revoke execute on function public.save_student_grammar_attempt_session(text,bigint,jsonb,integer,integer) from public;
revoke execute on function public.get_student_training_progress_session(text) from public;
revoke execute on function public.save_student_training_attempt_session(text,text,text,text,text,jsonb,integer,integer) from public;
revoke execute on function public.save_student_draft(text,bigint,jsonb) from public;

grant execute on function public.student_start_session(text) to anon,authenticated;
grant execute on function public.student_end_session(text) to anon,authenticated;
grant execute on function public.student_session_data(text) to anon,authenticated;
grant execute on function public.student_session_feedback(text) to anon,authenticated;
grant execute on function public.student_session_grammar_assignments(text) to anon,authenticated;
grant execute on function public.save_student_draft_session(text,bigint,jsonb) to anon,authenticated;
grant execute on function public.save_student_grammar_attempt_session(text,bigint,jsonb,integer,integer) to anon,authenticated;
grant execute on function public.get_student_training_progress_session(text) to anon,authenticated;
grant execute on function public.save_student_training_attempt_session(text,text,text,text,text,jsonb,integer,integer) to anon,authenticated;
grant execute on function public.save_student_draft(text,bigint,jsonb) to anon,authenticated;
