create table if not exists public.reading_strategy_assignments (
  id bigint generated by default as identity primary key,
  class_id bigint not null references public.classes(id) on delete cascade,
  title text not null default 'Læsestrategitræning',
  strategy text not null,
  target_grade integer not null check (target_grade between 6 and 9),
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  constraint reading_strategy_assignments_strategy_valid check (strategy = any (array[
    'Skimning og overblik'::text,
    'Scanning og informationssøgning'::text,
    'Hovedindhold'::text,
    'Inferens'::text,
    'Ord i kontekst'::text,
    'Tekststruktur'::text,
    'Afsender og formål'::text,
    'Sammenhæng og cloze'::text
  ]))
);

create table if not exists public.reading_strategy_assignment_students (
  reading_strategy_assignment_id bigint not null references public.reading_strategy_assignments(id) on delete cascade,
  student_id bigint not null references public.students(id) on delete cascade,
  primary key (reading_strategy_assignment_id, student_id)
);

create index if not exists reading_strategy_assignments_class_idx on public.reading_strategy_assignments(class_id, created_at desc);
create index if not exists reading_strategy_assignment_students_student_idx on public.reading_strategy_assignment_students(student_id, reading_strategy_assignment_id);

alter table public.reading_strategy_assignments enable row level security;
alter table public.reading_strategy_assignment_students enable row level security;
revoke all on table public.reading_strategy_assignments from public, anon, authenticated;
revoke all on table public.reading_strategy_assignment_students from public, anon, authenticated;

create or replace function public.create_reading_strategy_assignment(
  p_class_id bigint,
  p_strategy text,
  p_target_grade integer default 9,
  p_student_ids bigint[] default null,
  p_title text default null
) returns jsonb
language plpgsql
security definer
set search_path = 'public', 'private'
as $function$
declare
  v_school_id bigint;
  v_allowed boolean;
  v_assignment public.reading_strategy_assignments;
  v_invalid_students integer;
  v_recipient_count integer;
begin
  if auth.uid() is null then return jsonb_build_object('ok',false,'error','not_authenticated'); end if;
  if p_target_grade not between 6 and 9 then return jsonb_build_object('ok',false,'error','invalid_target_grade'); end if;
  if p_strategy is null or p_strategy <> all(array[
    'Skimning og overblik'::text,
    'Scanning og informationssøgning'::text,
    'Hovedindhold'::text,
    'Inferens'::text,
    'Ord i kontekst'::text,
    'Tekststruktur'::text,
    'Afsender og formål'::text,
    'Sammenhæng og cloze'::text
  ]) then return jsonb_build_object('ok',false,'error','invalid_strategy'); end if;

  select c.school_id into v_school_id from public.classes c where c.id=p_class_id;
  if v_school_id is null then return jsonb_build_object('ok',false,'error','class_not_found'); end if;
  select (public.has_school_role(v_school_id,'admin') or (public.has_school_role(v_school_id,'teacher') and exists(select 1 from public.teacher_classes tc where tc.class_id=p_class_id and tc.teacher_id=auth.uid()))) into v_allowed;
  if not coalesce(v_allowed,false) then return jsonb_build_object('ok',false,'error','forbidden'); end if;

  if p_student_ids is not null and cardinality(p_student_ids)>0 then
    select count(*) into v_invalid_students
    from unnest(p_student_ids) x(student_id)
    where not exists(select 1 from public.students s where s.id=x.student_id and s.class_id=p_class_id);
    if v_invalid_students>0 then return jsonb_build_object('ok',false,'error','invalid_recipients'); end if;
  end if;

  insert into public.reading_strategy_assignments(class_id,title,strategy,target_grade,created_by)
  values(p_class_id,coalesce(nullif(trim(p_title),''),concat('Træn ',p_strategy)),p_strategy,p_target_grade,auth.uid())
  returning * into v_assignment;

  if p_student_ids is not null and cardinality(p_student_ids)>0 then
    insert into public.reading_strategy_assignment_students(reading_strategy_assignment_id,student_id)
    select v_assignment.id,student_id from (select distinct unnest(p_student_ids) student_id) q;
    select count(*) into v_recipient_count from public.reading_strategy_assignment_students where reading_strategy_assignment_id=v_assignment.id;
  else
    select count(*) into v_recipient_count from public.students where class_id=p_class_id;
  end if;

  return jsonb_build_object('ok',true,'assignment_id',v_assignment.id,'recipient_count',v_recipient_count,'strategy',v_assignment.strategy,'target_grade',v_assignment.target_grade);
end;
$function$;

create or replace function public.student_session_reading_strategy_assignments(p_session_token text)
returns jsonb
language plpgsql
security definer
set search_path = 'public', 'private'
as $function$
declare
  s public.students;
begin
  select * into s from public.students where id=private.student_id_for_session(p_session_token);
  if s.id is null then return jsonb_build_object('ok',false,'error','invalid_session'); end if;

  return jsonb_build_object('ok',true,'assignments',coalesce((
    select jsonb_agg(jsonb_build_object(
      'id',a.id,'title',a.title,'strategy',a.strategy,'target_grade',a.target_grade,'created_at',a.created_at,
      'completed',p.last_attempt_at is not null and p.last_attempt_at>=a.created_at,
      'attempts',case when p.last_attempt_at>=a.created_at then p.attempts else 0 end,
      'best_score',case when p.last_attempt_at>=a.created_at then p.best_score else null end,
      'max_score',case when p.last_attempt_at>=a.created_at then p.max_score else null end,
      'last_score',case when p.last_attempt_at>=a.created_at then p.last_score else null end,
      'last_attempt_at',case when p.last_attempt_at>=a.created_at then p.last_attempt_at else null end
    ) order by a.created_at desc)
    from public.reading_strategy_assignments a
    left join public.student_training_progress p
      on p.student_id=s.id and p.subject_id='dansk-laesning' and p.area_id='laesestrategier' and p.skill_id=a.strategy and p.level_id=concat('grade-',a.target_grade)
    where a.class_id=s.class_id
      and (not exists(select 1 from public.reading_strategy_assignment_students x where x.reading_strategy_assignment_id=a.id)
           or exists(select 1 from public.reading_strategy_assignment_students x where x.reading_strategy_assignment_id=a.id and x.student_id=s.id))
  ),'[]'::jsonb));
end;
$function$;

create or replace function public.teacher_reading_strategy_assignments(p_class_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = 'public', 'private'
as $function$
declare v_school_id bigint; v_allowed boolean;
begin
  if auth.uid() is null then return jsonb_build_object('ok',false,'error','not_authenticated'); end if;
  select c.school_id into v_school_id from public.classes c where c.id=p_class_id;
  if v_school_id is null then return jsonb_build_object('ok',false,'error','class_not_found'); end if;
  select (public.has_school_role(v_school_id,'admin') or (public.has_school_role(v_school_id,'teacher') and exists(select 1 from public.teacher_classes tc where tc.class_id=p_class_id and tc.teacher_id=auth.uid()))) into v_allowed;
  if not coalesce(v_allowed,false) then return jsonb_build_object('ok',false,'error','forbidden'); end if;

  return jsonb_build_object('ok',true,'assignments',coalesce((
    select jsonb_agg(jsonb_build_object(
      'id',a.id,'title',a.title,'strategy',a.strategy,'target_grade',a.target_grade,'created_at',a.created_at,
      'recipient_count',case when exists(select 1 from public.reading_strategy_assignment_students x0 where x0.reading_strategy_assignment_id=a.id)
        then (select count(*) from public.reading_strategy_assignment_students x where x.reading_strategy_assignment_id=a.id)
        else (select count(*) from public.students s where s.class_id=a.class_id) end,
      'completed_count',(select count(*) from public.students s left join public.student_training_progress p
        on p.student_id=s.id and p.subject_id='dansk-laesning' and p.area_id='laesestrategier' and p.skill_id=a.strategy and p.level_id=concat('grade-',a.target_grade)
        where s.class_id=a.class_id and (not exists(select 1 from public.reading_strategy_assignment_students z where z.reading_strategy_assignment_id=a.id)
          or exists(select 1 from public.reading_strategy_assignment_students z where z.reading_strategy_assignment_id=a.id and z.student_id=s.id)) and p.last_attempt_at>=a.created_at),
      'locked',exists(select 1 from public.students s join public.student_training_progress p
        on p.student_id=s.id and p.subject_id='dansk-laesning' and p.area_id='laesestrategier' and p.skill_id=a.strategy and p.level_id=concat('grade-',a.target_grade)
        where s.class_id=a.class_id and (not exists(select 1 from public.reading_strategy_assignment_students z where z.reading_strategy_assignment_id=a.id)
          or exists(select 1 from public.reading_strategy_assignment_students z where z.reading_strategy_assignment_id=a.id and z.student_id=s.id)) and p.last_attempt_at>=a.created_at)
    ) order by a.created_at desc) from public.reading_strategy_assignments a where a.class_id=p_class_id
  ),'[]'::jsonb));
end;
$function$;

create or replace function public.delete_reading_strategy_assignment(p_assignment_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = 'public', 'private'
as $function$
declare a public.reading_strategy_assignments; v_school_id bigint; v_allowed boolean; v_started boolean;
begin
  if auth.uid() is null then return jsonb_build_object('ok',false,'error','not_authenticated'); end if;
  select * into a from public.reading_strategy_assignments where id=p_assignment_id;
  if a.id is null then return jsonb_build_object('ok',false,'error','not_found'); end if;
  select school_id into v_school_id from public.classes where id=a.class_id;
  select (public.has_school_role(v_school_id,'admin') or (public.has_school_role(v_school_id,'teacher') and exists(select 1 from public.teacher_classes tc where tc.class_id=a.class_id and tc.teacher_id=auth.uid()))) into v_allowed;
  if not coalesce(v_allowed,false) then return jsonb_build_object('ok',false,'error','forbidden'); end if;
  select exists(select 1 from public.students s join public.student_training_progress p
    on p.student_id=s.id and p.subject_id='dansk-laesning' and p.area_id='laesestrategier' and p.skill_id=a.strategy and p.level_id=concat('grade-',a.target_grade)
    where s.class_id=a.class_id and (not exists(select 1 from public.reading_strategy_assignment_students z where z.reading_strategy_assignment_id=a.id)
      or exists(select 1 from public.reading_strategy_assignment_students z where z.reading_strategy_assignment_id=a.id and z.student_id=s.id)) and p.last_attempt_at>=a.created_at) into v_started;
  if v_started then return jsonb_build_object('ok',false,'error','assignment_started'); end if;
  delete from public.reading_strategy_assignments where id=a.id;
  return jsonb_build_object('ok',true);
end;
$function$;

revoke all on function public.create_reading_strategy_assignment(bigint,text,integer,bigint[],text) from public, anon;
revoke all on function public.teacher_reading_strategy_assignments(bigint) from public, anon;
revoke all on function public.delete_reading_strategy_assignment(bigint) from public, anon;
revoke all on function public.student_session_reading_strategy_assignments(text) from public, authenticated;
grant execute on function public.create_reading_strategy_assignment(bigint,text,integer,bigint[],text) to authenticated, service_role;
grant execute on function public.teacher_reading_strategy_assignments(bigint) to authenticated, service_role;
grant execute on function public.delete_reading_strategy_assignment(bigint) to authenticated, service_role;
grant execute on function public.student_session_reading_strategy_assignments(text) to anon, service_role;
