create table if not exists public.subject_unit_items (
  id bigint generated by default as identity primary key,
  subject_unit_id bigint not null references public.subject_units(id) on delete cascade,
  subject_room_item_id bigint not null references public.subject_room_items(id) on delete cascade,
  position integer not null default 0,
  created_at timestamptz not null default now(),
  unique(subject_unit_id, subject_room_item_id)
);

create index if not exists subject_unit_items_unit_idx
  on public.subject_unit_items(subject_unit_id, position, id);
create index if not exists subject_unit_items_item_idx
  on public.subject_unit_items(subject_room_item_id);

alter table public.subject_unit_items enable row level security;

create or replace function private.validate_subject_unit_item()
returns trigger
language plpgsql
security definer
set search_path='public','private'
as $$
declare
  v_unit_room bigint;
  v_item_room bigint;
  v_item_type text;
begin
  select u.class_subject_id into v_unit_room
  from public.subject_units u
  where u.id=new.subject_unit_id;

  select i.class_subject_id,i.item_type into v_item_room,v_item_type
  from public.subject_room_items i
  where i.id=new.subject_room_item_id;

  if v_unit_room is null or v_item_room is null then
    raise exception 'Unit or room item does not exist';
  end if;
  if v_unit_room<>v_item_room then
    raise exception 'Unit material must belong to the same subject room';
  end if;
  if v_item_type='note' then
    raise exception 'Teacher notes cannot be linked as unit materials';
  end if;
  return new;
end;
$$;

revoke all on function private.validate_subject_unit_item() from public,anon,authenticated;

drop trigger if exists subject_unit_items_validate_room on public.subject_unit_items;
create trigger subject_unit_items_validate_room
before insert or update of subject_unit_id,subject_room_item_id on public.subject_unit_items
for each row execute function private.validate_subject_unit_item();

drop policy if exists "school staff read unit items" on public.subject_unit_items;
create policy "school staff read unit items" on public.subject_unit_items
for select to authenticated
using (
  exists (
    select 1 from public.subject_units u
    where u.id=subject_unit_items.subject_unit_id
      and public.is_school_staff(u.school_id)
  )
);

drop policy if exists "subject teachers link unit items" on public.subject_unit_items;
create policy "subject teachers link unit items" on public.subject_unit_items
for insert to authenticated
with check (
  exists (
    select 1
    from public.subject_units u
    join public.subject_room_items i
      on i.id=subject_unit_items.subject_room_item_id
     and i.class_subject_id=u.class_subject_id
    where u.id=subject_unit_items.subject_unit_id
      and i.item_type<>'note'
      and private.can_edit_class_subject(u.class_subject_id)
  )
);

drop policy if exists "subject teachers update unit items" on public.subject_unit_items;
create policy "subject teachers update unit items" on public.subject_unit_items
for update to authenticated
using (
  exists (
    select 1 from public.subject_units u
    where u.id=subject_unit_items.subject_unit_id
      and private.can_edit_class_subject(u.class_subject_id)
  )
)
with check (
  exists (
    select 1
    from public.subject_units u
    join public.subject_room_items i
      on i.id=subject_unit_items.subject_room_item_id
     and i.class_subject_id=u.class_subject_id
    where u.id=subject_unit_items.subject_unit_id
      and i.item_type<>'note'
      and private.can_edit_class_subject(u.class_subject_id)
  )
);

drop policy if exists "subject teachers unlink unit items" on public.subject_unit_items;
create policy "subject teachers unlink unit items" on public.subject_unit_items
for delete to authenticated
using (
  exists (
    select 1 from public.subject_units u
    where u.id=subject_unit_items.subject_unit_id
      and private.can_edit_class_subject(u.class_subject_id)
  )
);
